### ISSUE TITLE
Modify climate-pulling code to pull data for full year before and after field sample date from netcdf files

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#101]
Lizzie says that PMP requires one full year of climate data so we need to pull more than what we already have.

**Comment by AileneKane** [comment]
should have the following columns: datasetID, study, lat, long, year, doy, min temp, max temp, field sample date

**Comment by AileneKane** [comment]
This has been added in a new folder called pmp in analyses. within this folder, use the code: pulldailyclim.R , which sources other code, and is found here: https://github.com/lizzieinvancouver/ospree/blob/master/analyses/pmp/pulldailyclim.R.

**Comment by lizzieinvancouver** [comment]
Error in pullclimate_eur_pmp.R:
```
>   mins <- ncvar_get(eur.tempmn,'tn', 
+                     start=c(nlong.cell,nlat.cell,st), 
+                     count=c(1,1,en-st+1) # this is where we move through the 'cube' to get the one vector of Temp mins
+   ) 
Error in Rsx_nc4_get_vara_int: NetCDF: Start+count exceeds dimension bound
Var: tn  Ndims: 3   Start: 23375,124,149 Count: 730,1,1
Error in ncvar_get_inner(ncid2use, varid2use, nc$var[[li]]$missval, addOffset,  : 
  C function Rsx_nc4_get_var_int returned error
> c(nlong.cell,nlat.cell,st)
[1]   150   125 23376
> count=c(1,1,en-st+1)
> count
[1]   1   1 730
```
It happens on i=39. I wondered if maybe it is asking for data after the last year of data?

**Comment by lizzieinvancouver** [comment]
Also, warning in pullcimate_nam_pmp.R: 
`Warning message:
Too many values at 49869 locations: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ... 
> `
I saw this issue here: http://tidyr.tidyverse.org/reference/separate.html and here: https://stackoverflow.com/questions/35260483/splitting-rows-into-columns-in-r-using-tidyr ... will see if the data looks okay next.

**Comment by lizzieinvancouver** [comment]
@AileneKane Looks like I can update E-OBS through 2016, but too big to download now so I am adding it to my todo list (http://www.ecad.eu/download/ensembles/download.php#datafiles)

**Comment by AileneKane** [comment]
@lizzieinvancouver I think i fixed the Error in pullclimate_eur_pmp.R by adding a line of code restricting the pulled climate data to the last year of climate data available
