### ISSUE TITLE
Check the 2 climate datasets

### ISSUE THREAD

**Issue by MoralesCastilla** [lizzieinvancouver/ospree#102]
Find and check climate data and re-download if not in WeldShare

**Comment by MoralesCastilla** [comment]
I have checked the climate datasets and code within the chilling folder. Should I close this issue?
@lizzieinvancouver

**Comment by lizzieinvancouver** [comment]
We should pull the updated data for E-OBS! http://www.ecad.eu/download/ensembles/download.php#datafiles

**Comment by lizzieinvancouver** [comment]
Also, Cat talked to Ben who did not know when livneh would be updated, but will ask his friend (called Ben also?)

**Comment by lizzieinvancouver** [comment]
Nacho and Lizzie updated the E-OBS data to version 15!

Get an update from Cat on this on 5 July and close!

**Comment by lizzieinvancouver** [comment]
No new news, Lizzie will try to remember to ask Ben periodically.
