### ISSUE TITLE
Figure out why we are losing so much data due to chilling

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#103]
Look at how many studies without chilling data are seeds, are more recent data (too recent to be in livenh or eos), are location based; have field sample date missing; or other reasons for losing data. Find out how many rows and how many studies are lost.

**Comment by AileneKane** [comment]
use ospreeclean_withchill.csv to do this

**Comment by AileneKane** [comment]
Overall, 5,404/12,744 rows (in ospree_clean_withchill.csv) are missing chilling data ("Total..." columns).
The primary cause of missing chilling data is lack of field sample date (4,685/12,744 rows).
About half of the data without field sample date (4,685 rows) use seedlings (2372); 870 are cuttings.

In looking at data WITH field sample date, 1,824/8,059 rows are missing chilling data.
Most of these 1173 rows in europe WITHOUT chilling data and 130 in north america without chilling data. Many of these are Zohner (864 rows), and I'm not sure why climate data are not pulled for this site in munich!

**Comment by AileneKane** [comment]
I believe that Zohner climate data is excluded because the year column was left blank (even though the field sample date column is filled in). This seems to be the only study for which year was not entered as a column, even though we have the data. So, we have two choices for a solution that i can think of- we add the year data to the OSPREE database directly, or we add it in some cleaning code somewhere. I'm not sure if there are other procedures that rely on the year column, besides calculating chilling; if not, i can add it to the chilling code.

**Comment by lizzieinvancouver** [comment]
@AileneKane I can add it to the main cleaning file, then re-run everything. Should year be extracted from the field sample date?

**Comment by AileneKane** [comment]
@lizzieinvancouver i think that would work fine! for all other studies is was entered in separately as its own column.
