### ISSUE TITLE
Go through photoperiod column to see where we're losing data

### ISSUE THREAD

**Issue by cchambe12** [lizzieinvancouver/ospree#105]

**Comment by cchambe12** [comment]
Went through all the studies and found missing entries...

For some ambient entries, I was able to use the geosphere package. Using latitude and date I could determine the daylength. How specific should I go with photoperiod entries? Also, daylength varies over the course of the experiment for these, how should we deal with this?

I have a question about schnabel87. Maybe we can go over all of this at our next Ospree meeting!

**Comment by lizzieinvancouver** [comment]
@cchambe12 All sounds good, I think -- for what you are doing -- we just need an average for each treatment (so, if they say ambient -- you could take the average over the days).
Speaking of which I was just about to dig into geosphere myself. Can you point me to any of your code?
Thanks!

**Comment by cchambe12** [comment]
@lizzieinvancouver  excellent I will work on doing that tomorrow!

you can find my code here...
ospree/analyses/bb_analysis/cleaning/clean_photoperiod.R

I only used the 'daylength' command so it may not be terribly helpful! Seems like a cool package though!

**Comment by cchambe12** [comment]
Finished updating using average photoperiod throughout the exeperiment

Not sure what to do with schnabel87 - I fixed it for now but all of the ambient entries are in field comparisons to experiment - do we want to keep those?

**Comment by lizzieinvancouver** [comment]
@cchambe12 I will be working on this and your other query soon! I think we probably don't need to fix schnabel87 ambient just now but if you can give any more detail I will look into it.

**Comment by lizzieinvancouver** [comment]
schnabel87 has a control group of samples with ambient forcing, chilling, photoperiod --- so this is okay.
