### ISSUE TITLE
Try to clean phenstage in respvar.simple!

### ISSUE THREAD

**Issue by cchambe12** [lizzieinvancouver/ospree#106]

**Comment by cchambe12** [comment]
not really much to clean... I can convert 2 studies and it would only add 9 rows total

**Comment by lizzieinvancouver** [comment]
@cchambe12 Please check out my commit ca7cf835d0a16fe06002a422aaaef01638f613f7 (updates to your file and the main bb clean file) and see the notes within the file ... let me know if this works. If so, update the cleanphenstage file and pass back to me.

**Comment by cchambe12** [comment]
@lizzieinvancouver your commit worked! I don't know where it should go in the bb_cleanmergeall.R list though, one of the cleaning files removes the two studies from the list. The clean_phenstage.R script is cleaned if you want to double check it.

**Comment by lizzieinvancouver** [comment]
@cchambe12 
I just pushed a commit that adds this to the main bb cleaning file and I checked the code. Everything looks good, except! we still need to update the comment on line 16:

`# gansert02: we could use budstages 2-3 (QUESTION: Do you mean 2-7 ... that's what the code does) ... fixing gives 3 observations`

This is a discussion between you and me about what budstages we should be using. You wrote budstages 2-3 in your comment here, but your code does stages 2-7. Which is correct? If it's the latter, then update the comment in phenstage.R ... if the former, update the code and bounce back to me to check on last time.

**Comment by cchambe12** [comment]
@lizzieinvancouver 
all fixed! By the definition we are looking for stages 2-3.

**Comment by lizzieinvancouver** [comment]
@cchambe12  
Close, that fixes gansert02! But I then noticed that you say "pagter15: Between budstage 1 and 2 is considered budburst" but don't select just those values, I updated the code to fix this. Can you check this is correct now?

**Comment by cchambe12** [comment]
@lizzieinvancouver  
Looks great! Thanks for the fix! I am going to close this bad boy.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Whoop!
