### ISSUE TITLE
Get going on flowers vs. leaves analysis: Berries!

### ISSUE THREAD

**Issue by dbuona** [lizzieinvancouver/ospree#108]
Investigate data to see whether a fruitful analysis comparing floral to foliate phenological responses is possible

**Comment by lizzieinvancouver** [comment]
"Flowers is not worth anything ... we have maybe, two species. And most of them are blackberries."
~ Dan (5 July 2017)

**Comment by lizzieinvancouver** [comment]
Bring back strawberries.

**Comment by lizzieinvancouver** [comment]
@dbuona Just working on OSPREE and noticed that the spier74 PDF has vegetative and floral budbreak. I haven't checked if we entered both sets of data but worth checking out perhaps?

**Comment by lizzieinvancouver** [comment]
@dbuona Also, random thought -- check the phenstage studies and see if any of the phenstages includes span bb to flowering?

**Comment by dbuona** [comment]
I'm closing this because there isn't enough flowering data to be useful.
