### ISSUE TITLE
Dirty climate data?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#111]
Iñaki noticed some anomalies in our climate data (i.e., tmin>tmax). We might look into cleaning it?

**Comment by lizzieinvancouver** [comment]
Talked with Ben Cook on 30 June 2017; he said E-OBS should *not* be dirty and if it is, we should contact them.

**Comment by AileneKane** [comment]
yikes! so, must be a coding issue...i'll look at this!

**Comment by lizzieinvancouver** [comment]
Hmm, could also be very real!

**Comment by AileneKane** [comment]
I checked the Tmin and Tmax values we pull for north america and eur (found in the tempval list created in step 4 of chillmerge_all) and found no values with tmin>tmax. Let me know if there is anything else that I should check for, or if you want me to check the other climate data you pulled for PMP).
