### ISSUE TITLE
fieldsample.date and year

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#117]
@AileneKane 
We should look into this more, a quick comparison of the year in fieldsample.date with the column year shows many instances where they are not the same. 

Year should have been entered for 'year of experiment' .... so I need to update my work on Zohner and you should check how you used year.

**Comment by lizzieinvancouver** [comment]
Just changed Zohner so year is always 2014 (see commit 4b56122f447893b5cb8384ed2cf72069b87d73d8). Updated all downstream files.

**Comment by AileneKane** [comment]
@lizzieinvancouver this is how we used year in the chilling code:
year was used to select studies for which climate data could be pulled. lat-longs from studies with year after 1950 were used to pull data.

**Comment by lizzieinvancouver** [comment]
Okay! We should be fine then. Thanks! And sorry for the bother.
