### ISSUE TITLE
fix/check testdata for interaction model

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#123]

**Comment by lizzieinvancouver** [comment]
Ailene checked ... seems to be working on the centered data; she will now try changing to uncentered and see if it works.

**Comment by AileneKane** [comment]
Testdata seems to work on uncentered data! model with 2-way interactions recovers main effects and interactions quite well.

 I got a warning (see below), but this warning is apparently not as big a deal as divergent transitions- it i just about effiiency. 

Warning messages:
1: There were 3988 transitions after warmup that exceeded the maximum treedepth. Increase max_treedepth above 10. See
http://mc-stan.org/misc/warnings.html#maximum-treedepth-exceeded 
2: Examine the pairs() plot to diagnose sampling problems
