### ISSUE TITLE
finalize GDD

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#124]
- Need to add for studies without fieldsampledate or lastchill date but WITH experimental forcing .. just  multiple response.time x forcetemp....

**Comment by lizzieinvancouver** [comment]
And make plots? It would be cool to see GDD vs. Chill Hours (or some metric of chilling), color-coded by species with each plot a different range of photoperiods ....

**Comment by MoralesCastilla** [comment]
I have been re-checking the get_GDD code and am not sure we are getting the gdd value to input as a response variable of our bb models. Should I go through this?

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Let's discuss tomorrow!

**Comment by MoralesCastilla** [comment]
Finalize output to be added to Ospree data

**Comment by lizzieinvancouver** [comment]
Make an output file!

**Comment by MoralesCastilla** [comment]
The GDD code generates an output file <bbdata_wgdd.csv> in: (https://github.com/lizzieinvancouver/ospree/tree/master/analyses/output) that can then be utilized to build figures or in subsequent analyses. If that is good enough we can close this issue.
