### ISSUE TITLE
Weinberger analysis

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#126]
Compare field sample method vs. experimental chilling... see also [wiki here](https://github.com/lizzieinvancouver/ospree/wiki/Weinberger-analysis-notes)

**Comment by AileneKane** [comment]
See bb_weinberger.R
There are 2845 rows of data, across 54 studies (17 exp studies and 37 fieldsample) that we can use for this analysis.

**Comment by AileneKane** [comment]
I fit a model in lmer that suggests that study type affects response time (as a main effect AND interacting with chilling, forcing, and photoperiod effects): 

Linear mixed model fit by REML ['lmerMod']
Formula: response.time ~ (Total_Chilling_Hours + forcetemp + photoperiod_day +      studytype)^3 + (1 | bb.taxa)
   Data: bb.study.bb2

REML criterion at convergence: 8862.9

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.2079 -0.3856 -0.0086  0.4066  4.4292 

Random effects:
 Groups   Name        Variance Std.Dev.
 bb.taxa  (Intercept) 191.0    13.82   
 Residual             320.9    17.91   
Number of obs: 1006, groups:  bb.taxa, 67

Fixed effects:
                                                            Estimate Std. Error t value
(Intercept)                                                1.285e+02  3.036e+01   4.232
Total_Chilling_Hours                                      -7.570e-02  1.443e-02  -5.245
forcetemp                                                 -7.016e+00  1.988e+00  -3.530
photoperiod_day                                           -6.305e+00  1.734e+00  -3.636
studytypefieldsample                                      -4.118e+01  2.745e+01  -1.500
Total_Chilling_Hours:forcetemp                             4.521e-03  9.398e-04   4.810
Total_Chilling_Hours:photoperiod_day                       3.685e-03  6.726e-04   5.479
Total_Chilling_Hours:studytypefieldsample                  6.299e-02  7.806e-03   8.070
forcetemp:photoperiod_day                                  3.831e-01  1.123e-01   3.411
forcetemp:studytypefieldsample                             3.085e+00  1.799e+00   1.715
photoperiod_day:studytypefieldsample                       3.974e+00  1.611e+00   2.467
Total_Chilling_Hours:forcetemp:photoperiod_day            -2.304e-04  4.381e-05  -5.259
Total_Chilling_Hours:forcetemp:studytypefieldsample       -3.472e-03  5.093e-04  -6.818
Total_Chilling_Hours:photoperiod_day:studytypefieldsample -5.552e-04  2.499e-04  -2.221
forcetemp:photoperiod_day:studytypefieldsample            -1.379e-01  1.018e-01  -1.354

**Comment by AileneKane** [comment]
Next steps are to:
1) Explore the odd relationships apparent in the data from the figures.
2) Fit in stan, as opposed to lmer

**Comment by lizzieinvancouver** [comment]
@dbuona Will update soon!

**Comment by dbuona** [comment]
@lizzieinvancouver We think we need to change to data so we can directly compare weinberger to more experimentally derived methods:
we want chilling data excluding "fieldest" but not weinberger and run the models again.

**Comment by lizzieinvancouver** [comment]
@AileneKane @dbuona So ... the answers we get are pretty sensitive to whether or not we include partial pooling beyond the intercept. See the compare models xlsx we've been using for some updates.  

Any ideas on how to check what model is actually better for our data or thoughts most welcome!

**Comment by AileneKane** [comment]
@lizzieinvancouver I like the idea of looking at R2. @dbuona be aware that when you remove "fieldest" you lose a LARGE number of studies- perhaps half?

**Comment by lizzieinvancouver** [comment]
@AileneKane We only remove fldest from the non-Weinberger studies. Dan suggested this and I think he is correct; if we do not do this, is it really a good comparison of how weinberger versus experimental chilling works (or, put another way, do we predict/expect a difference between field-chilled and weinberger?).

**Comment by lizzieinvancouver** [comment]
@AileneKane Also, we do show the difference in the compare models. You lose 200 rows of 1500 when you remove fldest ... and it does have a big effect on forcing. It drives the main effect of forcing down and drives up the force*weinberger effect ... again, we have to think of some ways (visualization?) on what models actually work better. I will try some R2 for now.

**Comment by AileneKane** [comment]
ah- i see! Sounds good!

**Comment by lizzieinvancouver** [comment]
@AileneKane @dbuona I made a tab in models_bb_compare to look at some of the models ... I think the next steps would be to re-do the plots (see bb_weinberger_mainplots.pdf) with the model output overlaid to understand what is going on.

**Comment by lizzieinvancouver** [comment]
@dbuona Add R2 for all models (there's R2 code in models_stan.R ... could also find other code for this?). And then plot the model estimates and the data!

**Comment by lizzieinvancouver** [comment]
@dbuona Next steps are to plot the models using the two stan models plotting scripts ... alter the pp plotting script to contrast wein_intpoolonly and weinberger_fewint (lizzie can help if needed!)

**Comment by dbuona** [comment]
@lizzieinvancouver I made some of the above mentioned plots... am not totally sure it is what you had in mind.... 

The figures are in the figures folder with names like "models_WEIN_compare_pp_chill.pdf", and the modified plotting code is in the bottom of the weinberger.R file. Happy to tweak it as necessary.

**Comment by AileneKane** [comment]
@AileneKane will look at the error around species estimates in model with slope and intercept pooling

**Comment by lizzieinvancouver** [comment]
@dbuona Try model in col G (no fldest from nonwein ... intpool only) with chill versus utahj

**Comment by lizzieinvancouver** [comment]
@dbuona Add 50% intervals to a couple major model, add note to xlsx file about which models are best, add a species list.

**Comment by dbuona** [comment]
@lizzieinvancouver I am suddenly getting identical model output in the weinberger.R  when I switch between chill.portions and Utah. I've been doing this by changing use.chillports=TRUE or FALSE. Is there something else I am supposed to do? Would it matter if use.z= is TRUE or FALSE?

**Comment by AileneKane** [comment]
@dbuona I have looked at the code and it's because the weinberger code creates its own datalist (wein.data). It does not rely on the datalists generated in bbstanleadin.R. You will need to use "chillport" rather than "chill" if you want to generate your own datalist within the weinberger code. If you want to use centered data, you will need to source  bb_zscorepreds.R as is done in bbstanleadin.R.
If the code does not make sense to you, let me know and i can update the weinberger file.

**Comment by dbuona** [comment]
@AileneKane Thanks for looking at this. I think I understand, and will make the changes in the script.  Thanks!

**Comment by lizzieinvancouver** [comment]
@dbuona Check out further the experimental design of non-weinberger studies (for matching species)

**Comment by dbuona** [comment]
Can't remember what I was supposed to be looking for exactly on this, but I added the chilling treatment information to the weinburger_summaries.xls file.

**Comment by lizzieinvancouver** [comment]
@dbuona Pots! Would be good to have some like: 
(1) modelscompare.ni.combined.pdf (that is, color coded by species (maybe different symbols for study design?), with the lines plotted on top; fine to use one model and plot two lines: one for non-weinberger studies and one for weinberger studies)
(2) muplotmodelspcomwcrops_expramp... pdf Basically just plot up model estimates!

**Comment by lizzieinvancouver** [comment]
@dbuona I stared at the model summaries more and here are some guesses and what we wanted to look at (or should like):

- Are the amounts of chilling comparable across these w/non-w (plots will do this)?
- Are the amounts of forcing and photo fairly equivalent across w/non-w (again, plotting would do this)?
- Maybe a map of the studies (crude is fine) as w/non-w?

And, hmm, I got nothing on species.

**Comment by lizzieinvancouver** [comment]
@dbuona Nice! Good to add mu plots of all parameters (e.g., muplotmodelspcomwcrops_expramp... pdf). And make plots using the model slopes and intercepts (e..g, modelscompare.ni.combined.pdf). Code for these is in stan models plotting files I believe -- let me know if you cannot find it!

**Comment by lizzieinvancouver** [comment]
@dbuona 
(1) Switch to Utah units
(2) Write up weinberger

**Comment by dbuona** [comment]
The estimates seem to have changed since weinberger_modelsummaries.xls was made. In that doc,  with Utah units, weinber studies had stronger chilling and photo effect and weaker forcing. Now it is the opposite. I'm going to take an nap and then run the model again to double check the it was I did all the flagging right.  It's possible the data changed, but the it is running on the same number of rows as before.

**Comment by AileneKane** [comment]
@dbuona Thanks for getting to this! I am not surprised as, even though the data has not changed since you last ran the model, I remember we had to fix some flags that were incorrect as well as the order that the centering was done in in bbstanleadin, so one of those things likely altered the data that were read into the model. I would trust your new numbers, although it is always a good idea to double check, especially after a nap! Please fill the new numbers in to the manucript, and alter the text as needed, once you have double-checked!

**Comment by AileneKane** [comment]
@dbuona After further thought- it would be good to double check all the flags in the sourced files to make sure that they are selecting the correct data for the weinberger studies. Could you do this, Dan?

**Comment by dbuona** [comment]
@AileneKane  I'll give it a look tomorrow

**Comment by dbuona** [comment]
@AileneKane I think there is a flagging issue, perhaps because I resource bb.zscorepred after making the weinberger columns. Basically if I flag use.chillports=TRUE I get a different model output than when it is false even though I am running the model on utah units in all cases. The discrepancies are listed in the excel file weinberger_modelsummaries.xls. Could you take a look the weinberger.R code and see what output you get?- I've tried to update the comments so it makes as much sense as possible, but let me know if there is anything that is strange or confusing

**Comment by AileneKane** [comment]
@dbuona I added some code to select the chil.lportions.z column instead of utah ("chill.z") units in the weinberger.R code. 
The problem that i ran into with the code is that bb.stan.alt.wein and bb.stan.alt.exponly.wein are used but not defined in the code so i wasn't able to create the following:
bb.stan.alt.matchsp 
bb.stan.alt.exponly

I did run the model with bb.stan.alt and got:
![image](https://user-images.githubusercontent.com/9097640/59539293-72ecfc00-8eb1-11e9-9078-c964f393d96c.png)

**Comment by dbuona** [comment]
@AileneKane ahh, I must have deleted some lines when I was cleaning up the code. I added them back and now the script runs as it should. I just re=ran the model and updated the manuscript accordingly, but it is probably worth giving it one more  glance if that's not too much trouble. Thanks!

**Comment by AileneKane** [comment]
@dbuona I will try to look at them today!

**Comment by AileneKane** [comment]
@dbuona the code looks ok. Could you add a weinberger figure plus legend to the supplement and update the text with these results?

**Comment by dbuona** [comment]
@AileneKane I switched the weinberger figure to be a mu plot to be consistent with the other two supplemental model figures. I also started writing the model, but its not in the correct for yet.

**Comment by AileneKane** [comment]
@dbuona thanks! I'm happy to help work on the model too- let me know!

**Comment by lizzieinvancouver** [comment]
@dbuona Make colors and figure design match the rest of the ms figures and ask @AileneKane to check.

**Comment by lizzieinvancouver** [comment]
@dbuona Rm underscore and italicize species names, fix y labels, check all spp show up ....

**Comment by lizzieinvancouver** [comment]
@dbuona Update code to use new flags and re-run!

**Comment by AileneKane** [comment]
@dbuona Thank you for all your work on this Dan! I think i told you not to worry about a table before, but I changed my mind! Could you make a table for the supplement? Please put it in the ["maketables.forsupp" ](https://github.com/lizzieinvancouver/ospree/tree/master/analyses/bb_analysis/maketables.forsupp) folder. (Use that code also to make your table match the main bb and lat model tables- it should have the same column names and contain the same mean/25/75/2.5/97.5 percentiles from the posterior.)

**Comment by AileneKane** [comment]
@lizzieinvancouver @dbuona we can close this now i think?

**Comment by lizzieinvancouver** [comment]
@AileneKane @dbuona  ... I think so -- it's the eve of the issue's two year anniversary!

**Comment by dbuona** [comment]
Yep!
