### ISSUE TITLE
limiting cues focal species

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#133]
@cchambe12 

Hi Cat!

I think we should pick a focal species from a couple choices, I put up 3 on the [wiki](https://github.com/lizzieinvancouver/ospree/wiki/Limiting-cues) but please add! Could you also add a note on how well distributed the data for leafout/budburst are for each species across time and space (I left a little space for this, maybe include how many datapoints in total, and then a quick assessment of how well distributed the data are across space and years?).

**Comment by cchambe12** [comment]
@lizzieinvancouver 
Sure thing! I would be happy to work on this. I will update the wiki as I go.

**Comment by cchambe12** [comment]
I have ranked them in order of data and spread and added a species to the list... Quercus robar

**Comment by lizzieinvancouver** [comment]
Awesome! Thank you!
