### ISSUE TITLE
daystobudburst versus dayofyeartobudburst

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#134]
Started with issue #127 where we saw multiple studies had this issue ...

**Comment by lizzieinvancouver** [comment]
Basic plan was: 

(1) In cleaning/clean_respvar.R: change daysofbudburst to dayofyeartobudburst
(2) Make the calculation changes in bb_analysis/cleaning/clean_respvarmore.R

See example here: commit dfe391c

**Comment by lizzieinvancouver** [comment]
And should we try checking all responses in the BB folder that are greater than 30 or 60 maybe to make sure this is not an issue in other studies?

**Comment by lizzieinvancouver** [comment]
@AileneKane Should I update the code you committed a week ago to remove the commenting and see if it runs (e.g., referencing clean_respvarmore.R etc.)?

**Comment by lizzieinvancouver** [comment]
@cchambe12 @dbuona @AileneKane @MoralesCastilla 
Hello all! I finally made that file so we can all help check for any more crazy response time issues. Check out my last commit 03c1bd803be00d662572c0f0d03918d74817c262 and also the new folder in bb_analysis/cleaning called: checkresponsetime

Your job:
(1) Open checkmeout_info.csv
(2) Locate your initials and check each paper (see checkresponsetime_README.txt for details)
(3) Fill in Y or N in the last column of checkmeout_info.csv (again, see checkresponsetime_README.txt for details)
(4) Save checkmeout_info.csv as a csv and push your changes.

**Comment by lizzieinvancouver** [comment]
@cchambe12 @dbuona @AileneKane @MoralesCastilla 
Oh, and I don't think it will take too long, I need to go have dinner but each paper so far took me about 2 minutes or less.

**Comment by AileneKane** [comment]
@lizzieinvancouver not quite- i need to move some of code from "clean_respvar.R" to "clean_respvarmore.R" i think, to be consistent. I can do this and commit the other changes, if you like!

**Comment by AileneKane** [comment]
@lizzieinvancouver ok, i just made the commits- it would be great if you could now see if it runs!

**Comment by cchambe12** [comment]
Partanen05 response.time is the date cuttings were transferred to be monitored, doesn't include daystobudburst at all and there is no way to calculate. The study had 16 field sample dates and then monitored budburst for each treatment (of the 16 transfers) 2-3 times per week. Once budburst occurred, they calculated the percentage of terminal buds that had bursted on a particular date but did not record the date that the buds bursted... Not sure how to fix this study in the database but I don't think we should be using it. 

Ramos99 is the same for Figure 1A and 1B, budburst was recorded after "a great and variable number of weeks" - I can fix Figures 1C-F.

**Comment by cchambe12** [comment]
@lizzieinvancouver 
I am fixing ramos99 issues for Figures 1C-F in clean_responsetime.R but I don't know how to make sure Figure 1A and 1B don't get through. To discuss at next Ospree meeting maybe?

**Comment by lizzieinvancouver** [comment]
@cchambe12 
The column `
figure.table..if.applicable.
`
Is a column in OSPREE (all the way back to the original data entry version). Can you just use that column also when you select what to change to make sure you only change what you mean to?

**Comment by lizzieinvancouver** [comment]
@cchambe12 For Partanen05 I assume the respvar is percentbudburst? If so we should delete the entries in response.time in clean_responsetime.R I think. Does that sound reasonable? We can note there clearly the response.time was actually date of transfer.

**Comment by dbuona** [comment]
@lizzieinvancouver I've been working on fixing skre08, but it seems sort of wonky. In one year(2001) they started their forcing at end of January, and in the next year, November(2001) and measured in Julian days (for 2002). When I adjust for this, it give bburst values for 2001 that are low, and 2002 that are very high. There are also a lot of confusing pre-treatments reported in the paper, so I am wondering if I have the date rights. Would you mind taking a look at some point?

**Comment by lizzieinvancouver** [comment]
@dbuona 
Yes, it seems a bit mucky. I don't see anything you have wrong but I have a couple queries: 
(a) Last non-full paragraph of page 255 says "transferring plants Dec 27 2000 and Jan 25 2001 to heated greenhouse" ... Do you understand what they mean by the two dates?
(b) Based on start of first full paragraph on page 256: "experiment repeated in 2001 with a slightly different procedure ..." we could treat each year as a different 'study' -- do we currently do that in OSPREE? It doesn't solve your query though....

Fig. 8 gives Julian day (sic!) of 60-120; I did not check that OSPREE is around there but it would be good to check. That said, given how similar the two panels appear and given that the forcing does seem to start at very different times I am not surprised you are getting very different BB dates!

BTW, Julian days is somewhere beyond 2 million just now. See https://en.wikipedia.org/wiki/Julian_day and use day of year.

**Comment by AileneKane** [comment]
@lizzieinvancouver i did a fix for gunderson12 but i'm not sure its what we want. the study takes place in "temperature-controlled open-top chambers (OTCs)" that were active year-round. not sure if we want to correct for day of year in this case, but if we do, we could pick a date (like march 1, as the study did) to use as a baseline....

**Comment by AileneKane** [comment]
@lizzieinvancouver I have several questions about hawkins12 so i have not fixed it yet. similar to above, as there is no clear start date of forcing. this was a common garden study with northern, central, and southern growing latitudes, as well as many provenances. the study uses feb 1 as a start date to accumulate growing degree days so we could use that as a baseline to convert doy of 50%budbreak to days to budbreak (or just keep things as they are). all the data seem to be from figure 2, which includes two years (1998 and 1999) though the years are mislabeled.

**Comment by lizzieinvancouver** [comment]
@dbuona Could you help me by looking at falusi97? The dates are actually just the days when things went into forcing temperatures so I struggled to figure out how we have 120, 87, 23 as response.time. I found 120 in the text but cannot find 87 or 23. Can you check? Can you also see if you can figure why exp 2 is all 60 when dates are given in table 2?

**Comment by dbuona** [comment]
@lizzieinvancouver For Falusi97. The experiment runs 120 days, so if it starts on September 18 it would end on Jan 16. So the 23 comes from Jan 16-Dec 24 is 23 and Jan 16 -Oct 23 is the 87.
Experiment 2 ran for 60 days, and the values presented were totaled at the end.

**Comment by lizzieinvancouver** [comment]
Closing! Check out ospree/analyses/bb_analysis/cleaning/checkresponsetime for more info!
