### ISSUE TITLE
limiting cues paper: work on pheno data for two species

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#135]
aim for 10-50 overlapping years across range

**Comment by cchambe12** [comment]
I have uploaded two .csv files into a new "input" folder within the "limitingcues" folder. I have also added climate data to a new "output" folder. I have a new script that extracts the climate data but the scripts for the PEP data is in my regional risk repo. I can make copies if we want information on how that data was cleaned. The VPN isn't working right now so I will finish extracting climate data another day!

**Comment by lizzieinvancouver** [comment]
@cchambe12 The csv files look amazing! Thank you!

Could you add a README to limitingcues/analyses called README_PEPdata.txt which covers:
- the names and locations of your scripts for extracting the data (then okay to leave in other repo I think, but link to github also)
- what each BBCH code means

Could you also rename the file names as PEP_betpen.csv and PEP_fagsyl.csv. We generally work with three-letter*2 genus species names, which is must safer than falling back on genus names.

**Comment by cchambe12** [comment]
Fixed the above!
