### ISSUE TITLE
limiting cues: get daily (monthly only if desperate) climate projections 

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#137]
We think we want:
- 2 months before leafout date mean temp (forcing)
- 6-2 months before leafout date mean temp (chilling) e.g., leafout is 1 May, then get Nov-Feb

**Comment by MoralesCastilla** [comment]
I have downloaded monthly climate projections (30 LE from CESM, RCP8.5, can be found within the climatefuture folder in RC). Now am working on a script to extract climate values for each occurrence of the target species, based on leafout dates.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla will get 2 months of min and max temp data for the limitingcues species, and map it across range!

/analyses/limitingcues/output/fagpred.wlatlong.csv
/analyses/limitingcues/output/betpred.wlatlong.csv
