### ISSUE TITLE
photoperiod paper: work on 3d figure of space, time, and photoperiod 

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#139]
We all liked this figure! Add a bit more detail to it

**Comment by lizzieinvancouver** [comment]
Axes are: shifts in time, shifts in geography, photoperiod
Ailene will send: max/min shifts in range; max/min shifts in space

**Comment by AileneKane** [comment]
oops- didn't mean to close! but i did send @MoralesCastilla the estimates.

**Comment by lizzieinvancouver** [comment]
@AileneKane 
Email Isabelle requesting the data (pick one: **FAGSYL**, QUEPET, QUEROB, PINSYL) -- I think we just need leaf unfolding date and fitness estimate at each location in range for 1980 and 2080.

**Comment by lizzieinvancouver** [comment]
Extra note! You will have to convert fitness data to presence/absence (Isabelle or Nacho can suggest methods).

**Comment by MoralesCastilla** [comment]
Make figure as soon as data is uploaded!!

**Comment by AileneKane** [comment]
Isabelle does not have the data here, so i think we need to look for other datasets to use for this, or think about a different way to show this.

**Comment by AileneKane** [comment]
Isabelle said to convert the fitness to presence/absence:
"Using the consensual distribution maps from Duputie et al GEB 2013, we had used fitness threshold of 0.1 for both Fagus and Quercus in the Duputie et al GCB 2014, which provided accuracies of 81% and 83%."

**Comment by lizzieinvancouver** [comment]
We have data on FAGSYL, QUEPET, QUEROB: 1981-2000 means and projections for A1 and B2 for end of century. @AileneKane Will get photoperiod for each leafout date (and will put in projections/phenofit folder in analyses and maybe also make a projections folder in output). @MoralesCastilla Then get climate data and try a figure!

**Comment by AileneKane** [comment]
I have added the photoperiod to each leafout date- it is in the output projections folder

**Comment by AileneKane** [comment]
@lizzieinvancouver @cchambe12 can we delete this issue, as i think it is functionally now a duplicate of  #165 ?

**Comment by cchambe12** [comment]
I'm okay with that!!

**Comment by lizzieinvancouver** [comment]
@AileneKane Me too, delete!
