### ISSUE TITLE
photoperiod paper: Look into and summarize evidence for photoperiod threshold in Arabidopsis flowering

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#142]

**Comment by dbuona** [comment]
To me, it seems the best evidence for a kind of thesh hold comes from the "external coincidence model", which seems to be well supported in the genetics, but really only deals with flowering. Singh et al consider applications to trees
see:

[Singh_et_al-2017-New_Phytologist.pdf](https://github.com/lizzieinvancouver/ospree/files/1315698/Singh_et_al-2017-New_Phytologist.pdf)

[Kobayashi and Weigel.pdf](https://github.com/lizzieinvancouver/ospree/files/1315702/photoperiod_circadian.pdf)

[andrés2012.pdf](https://github.com/lizzieinvancouver/ospree/files/1315704/andres2012.pdf)

**Comment by AileneKane** [comment]
Thanks Dan!

**Comment by lizzieinvancouver** [comment]
@AileneKane Feel free to close if you think this is done.
