### ISSUE TITLE
photoperiod paper: figure showing photoperiod at green-up date globally (er, North America!)

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#144]
This requires:
1) getting the green-up data
2) converting greenup dates to photoperiod
3) making a map
Anyone want to work on some aspect of this?

**Comment by dbuona** [comment]
I might have actually done this...I was messing around to see if I could even possibly be helpful with these kind of data, and  I might have made something that kind of works. It's very very hacky, and it uses NPN spring index maps which might not be what we want, but it could as a start.
I will push it soon.

**Comment by dbuona** [comment]
see commit  5bece41 . Could definitely use improvement and maybe a different data source, but I think it worked. Maybe someone can look at it and see if the code seems to make sense?

**Comment by lizzieinvancouver** [comment]
@cchambe12 Cat will ask Miriam for any possible simple data
@dbuona Dan will change to geosphere and see if map looks the same ...

**Comment by dbuona** [comment]
I made the plot in geosphere (still using NPN SI map as base), and it does indeed look different than the one I made with insol (see commit b652445 ). Day lengths seem more realistic to me given DOY, but the code could use a second look. @cchambe12  Any luck on getting a better base file from Miriam?

**Comment by cchambe12** [comment]
Miriam did get back to me. She suggested we look at MODIS, the NDVI product. Has anyone used this or feel comfortable with this interface? If not, it actually would be handy for me to feel a bit more comfortable with it so if we decide to pursue this option I am willing to take a stab at it!

**Comment by AileneKane** [comment]
I like your new map @dbuona! I looked quickly at the two different packages, and i think that their calculations are based on different equations. the insol package seems focused on calculating sunrise and sunset in moutainous regions and the[ paper](http://www.meteoexploration.com/products/publications/corripio03_ijgis.pdf) its based on says "The performance of the slope algorithm is evaluated using a synthetic surface and real world examples are given for the Mont Blanc Massif, in the French Alps." The paper also says that you may want to double check your times at. http://aa.usno.navy.mil/data/index.php.  The geosphere package, on the other hand, is based on a different [paper](http://www.sciencedirect.com/science/article/pii/030438009400034F) that "calculates the length of the day for a flat surface for a given latitude and day of the year is described." It claims that "Calculated daylengths are within 1 minute of values published in Smithsonian Meteorological Tables and the Astronomical Almanac for latitudes between 40° North and South with a maximum error of 7 minutes occurring at 60° latitude." So, if we trust the authors of the paper, i think this sounds pretty good...
@cchambe12 i have not used NDVI much and i think it would be great if you give it a try!

**Comment by dbuona** [comment]
I found a map that might be helpful... but I can't figure out how to access an actual usable file. Is anyone else familiar with the USFS's ForWarn? It seems like it models phenology based on NDVI not climate information. https://forwarn.forestthreats.org/highlights/917

**Comment by dbuona** [comment]
Update: I also just request data access from USGS to MarK Friedl MODIS stuff which uses a metric Onset_Greenness_Increase to represent start of spring based on NDVI. Maybe this will work

**Comment by lizzieinvancouver** [comment]
@dbuona Try to get North America for 2017 (unless someone has been declaring average years?!)

**Comment by AileneKane** [comment]
I think you already figured out  a good source for data, but i had asked Ben Cook about it last week, before I knew that, and here is what he sent me:
VIP is one option that calculates a variety of satellite phenology indicators:

https://lpdaac.usgs.gov/about/news_archive/nasa_vegetation_index_and_phenology_vip_data_released
https://vip.arizona.edu/VIP_Research.php

**Comment by dbuona** [comment]
@lizzieinvancouver 
The Friedl data only seems like it goes it up 2014. 
Does this: https://www.globalchange.gov/browse/indicators/indicator-start-spring seem like an appropriate basis for choosing an average year? Looks like 2009, 2003 or 2002 could work

**Comment by lizzieinvancouver** [comment]
@dbuona That's a super cool site! I think 2009 would work (if we later decide we want an early and late year 2012 and 2013 look good, but I think it's so hard to say what's early or late *across* the country that something average sounds good).

**Comment by lizzieinvancouver** [comment]
@dbuona Maybe take a quick look also at the two sites Ailene sent? I think the Freidl one seems as good and easier but you might have a better sense than me. ...

**Comment by lizzieinvancouver** [comment]
2012 is early for North America (NA)
2013 is late for NA

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Add version comparing 2012 and 2013 (but keep both versions)

**Comment by MoralesCastilla** [comment]
I am uploading the greenup figure comparing 2012 with that of 2013 (79bde19a5e244c44d028a9a479dd76f043f24a70)

**Comment by AileneKane** [comment]
Thank you for all your work on this @MoralesCastilla and @dbuona! Can we close this issue?

**Comment by lizzieinvancouver** [comment]
No one asked me, but I think so!
