### ISSUE TITLE
limitingcues: get the DOY for the two focal species ....

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#146]
get this done, so Nacho can start pulling correct climate data!

**Comment by cchambe12** [comment]
@lizzieinvancouver my first stab may not be exactly what we're looking for. I have a new script under the /limitingcues folder called "DOY_bb.R". In this script I am just finding the first observation for each individual across all the years and sites, however, that observation could be full individual leaf out. Should I subset down to only the observations that are within BBCH 7-10 ("beginning of sprouting" to "first leaves separated")? Or should we keep more BBCH stages to get a better sense of generally when budburst is?

**Comment by lizzieinvancouver** [comment]
Note to self (and all of us): Our plan from 17 October 2017 meeting was to try to clean up DOY using a hinge model for each site. 

So, I think my next steps are:
(1) count sites with >10 years of data, and >20 years
(2) fit hinge model to each site doy ~ year (hinge at 1980)
(3) find a year most consistent across all sites and predict the DOY at that year ...

**Comment by lizzieinvancouver** [comment]
Should we add [PERPHECLIM](http://www6.inra.fr/projet-accaf-perpheclim/Acces-aux-donnees) data?

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla  

Posting some relevant code output here:

`## Fagus model

> sumerf[grep("mu_", rownames(sumerf)),]
            mean      se_mean          sd        2.5%         25%         50%         75%       97.5%    n_eff     Rhat
mu_a 121.4286445 0.0017590781 0.111253865 121.2064914 121.3535557 121.4296292 121.5047712 121.6484079 4000.000 1.000022
mu_b  -0.3351715 0.0001126711 0.005206469  -0.3453664  -0.3386666  -0.3350543  -0.3316646  -0.3250214 2135.314 1.001959

## Betula

> sumerb[grep("mu_", rownames(sumerb)),]
            mean      se_mean          sd        2.5%         25%        50%         75%       97.5%    n_eff      Rhat
mu_a 113.3650231 0.0017899312 0.113205192 113.1454374 113.2879936 113.365187 113.4450810 113.5755223 4000.000 0.9999512
mu_b  -0.3561193 0.0001237142 0.004720024  -0.3653438  -0.3591735  -0.356077  -0.3530932  -0.3466607 1455.625 1.0028046


> # an example of one outlier from above:
> 
> 
>     which(linfit.fagpred>160)
[1]  103 1526
>     unique(faguse$PEP_ID)[103]
[1] "19666"
>     subset(faguse, PEP_ID=="19666")
     PEP_ID BBCH YEAR DAY National_ID     LON  LAT ALT species YEAR.hin
2291  19666   11 1958 127       21857 15.2167 48.6 593  FAGSYL        0
2405  19666   11 1959 109       21857 15.2167 48.6 593  FAGSYL        0
2603  19666   11 1960 125       21857 15.2167 48.6 593  FAGSYL        0
2745  19666   11 1961 104       21857 15.2167 48.6 593  FAGSYL        0
2886  19666   11 1962 113       21857 15.2167 48.6 593  FAGSYL        0
3060  19666   11 1963 118       21857 15.2167 48.6 593  FAGSYL        0
3214  19666   11 1964 115       21857 15.2167 48.6 593  FAGSYL        0
3370  19666   11 1965 126       21857 15.2167 48.6 593  FAGSYL        0
3542  19666   11 1966 122       21857 15.2167 48.6 593  FAGSYL        0
3640  19666   11 1967 119       21857 15.2167 48.6 593  FAGSYL        0
3765  19666   11 1968 114       21857 15.2167 48.6 593  FAGSYL        0
3967  19666   11 1969 123       21857 15.2167 48.6 593  FAGSYL        0
4062  19666   11 1970 125       21857 15.2167 48.6 593  FAGSYL        0
4187  19666   11 1971 113       21857 15.2167 48.6 593  FAGSYL        0
4308  19666   11 1972 109       21857 15.2167 48.6 593  FAGSYL        0
4492  19666   11 1973 125       21857 15.2167 48.6 593  FAGSYL        0
4653  19666   11 1974 128       21857 15.2167 48.6 593  FAGSYL        0
4754  19666   11 1975 122       21857 15.2167 48.6 593  FAGSYL        0
4915  19666   11 1976 127       21857 15.2167 48.6 593  FAGSYL        0
5056  19666   11 1977 124       21857 15.2167 48.6 593  FAGSYL        0
5216  19666   11 1978 149       21857 15.2167 48.6 593  FAGSYL        0
5426  19666   11 1980 133       21857 15.2167 48.6 593  FAGSYL        0
5559  19666   11 1981 148       21857 15.2167 48.6 593  FAGSYL        1
>     goo <- subset(faguse, PEP_ID=="19666") # note that only one year is later than 1980 and it is a really late year....
>     mean(goo$DAY)
[1] 122.5217
>     mod <- lm(DAY~YEAR.hin, data=goo)    summary(mod)
Error: unexpected symbol in "    mod <- lm(DAY~YEAR.hin, data=goo)    summary"
> 
>     summary(mod)

Call:
lm(formula = DAY ~ YEAR.hin, data = subby)

Residuals:
   Min     1Q Median     3Q    Max 
-5.815 -2.442 -1.145  3.021  8.248 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 124.0286     1.8449  67.228   <2e-16 ***
YEAR.hin     -0.2767     0.1660  -1.667    0.113    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 4.281 on 18 degrees of freedom
Multiple R-squared:  0.1337,	Adjusted R-squared:  0.08557 
F-statistic: 2.778 on 1 and 18 DF,  p-value: 0.1129
`

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver: remember to post models and update code!

**Comment by lizzieinvancouver** [comment]
Have run the models with sites with 10 years of data or 20 years ... see models here: https://drive.google.com/open?id=1Nsl-UJUFrOxHkwCyVq3Quyn-wbXXab_0
They run from DOY_bb.R.

Next steps are:
(1) Do we want 10 or 20 years?
(2) Lizzie needs to add priors to the models and re-run (and check that they do not change).

**Comment by lizzieinvancouver** [comment]
done, see analyses/limitingcues/output
