### ISSUE TITLE
Get photoperiod if at all possible!

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#149]

**Comment by cchambe12** [comment]
I was able to fix...
1. falusi96
2. linkosalo06
3. morin10
4. chavarria09
5. jones12
6. rinne97
7. sanzperez10

Would someone mind checking through that portion of the cod? Then we can close this issue I think!
I collated the new additions to the bottom of the script and added notes  next to most rows for clarity. Most of the changes use the same coding.

**Comment by cchambe12** [comment]
Added the flower studies that I could. I think I can close this issue now!
