### ISSUE TITLE
photoperiod paper: Finish table

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#151]
also, source code in a separate file

**Comment by AileneKane** [comment]
sourcing done! i want to discuss ideas for converting table to figure.

**Comment by AileneKane** [comment]
Try converting table to map. ask lizzie to send lines code

**Comment by AileneKane** [comment]
This is very close to done! Just need to check a couple of weird values in the table...

**Comment by AileneKane** [comment]
I checked/fixed the weird values. Table could be done?

**Comment by lizzieinvancouver** [comment]
@AileneKane Yes, you're lead on photoperiod so I think you can close any photoperiod MS issues you deem closed. Nice work!
