### ISSUE TITLE
update ospree figure

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#162]
- add ER spatially as something lighter going to pole
- add a different symbol for ER temporally

**Comment by lizzieinvancouver** [comment]
Second panel:
* add different symbols for time and space
* color code NA and Europe

**Comment by AileneKane** [comment]
I need Nacho's help with[ this figure ]( analyses/photoperiod/figures/ospree_photopmap.pdf)at this point (for example, it needs a different background map that doesn't cut out entire countries). my code is in analyses/photoperiod/photoshifts_map.R

**Comment by lizzieinvancouver** [comment]
@AileneKane Here is where Nacho has recommended to me to go for maps: http://www.naturalearthdata.com/ and I will email you some files!

**Comment by AileneKane** [comment]
Added legend, Still need to update colors (salmon4=temporal shifts; blue = spatial shifts)

**Comment by AileneKane** [comment]
Done, I think!
