### ISSUE TITLE
what is up with Falusi96 (bbperctodays?)

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#168]
@AileneKane @MoralesCastilla 
Ailene and Nacho, I think you both worked on this code and I am suspicious it’s part of why our bud burst models are failing. I have noticed a lot of the Falusi paper data is coming through with what really looks like multiple response times for identical treatments, when I look closer it looks like these come from % budburst by days to budburst figures where many of the value come through. If I set:

```
# run bb_cleanmergeall.R through step 4 (or 6, if the cleanambient code is working)
b <- d # just creating a reference copy
d <- subset(d, datasetID=="falusi96")
> dim(d)
[1] 425  79
# run the clean_bbperctodays.R code
> dim(d)
[1] 425  83

```
So I really think data should be deleted here, but they’re not. I have worked through the clean_bbperctodays.R but cannot see through it. Can one or both of you take a look?

Thanks!
L

PS: And note that we also have an issue where we need to deal with some studies with multiple material types … but I don’t think that is the problem for falusi96.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 

Lizzie, Ailene, I have been going through bb_cleanmergeall.R. As set the code does not remove the data but instead adds columns. A way to remove the data that are not within targeted values in the code can be done by making the following simple change in line 109:

`d.subset.1<-subset(d,respvar.simple=="percentbudburst" & !is.na(maxperc_bb))`

When you do that and run the clean_bbperctodays.R code:
```
> dim(d)
[1] 299  83
``` 

A second pair of eyes making sure that this works (i.e. is what we actually want) would be great.
I'm happy to give it another go if this does not work.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 

Hi Lizzie,

I have gone through bb_cleanmergeall.R and added a few lines so that it actually removes unwanted rows. It seems that it deals ok with issues a) to c). Also, by tweaking the acceptablerange parameter, we can delete more/less rows, which may help removing repeated rows near to the max budburst values (e.g. 100% percent budburst). 

If we need to make sure that we remove those repeated high values (i.e. 100), we can add a couple lines specifically designed to do so.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
Thanks Nacho! I see what you're saying, but I think what we actually need is not to change the acceptable range (this is an important but separate issue) but to add code towards the end that deals with cases where >1 row is left per treatment and selects the row closest to the targtevalue. I think this is probably what you were thinking above when you wrote 'If we need to make sure that we remove those repeated high values (i.e. 100), we can add a couple lines specifically designed to do so.' Could you implement this?

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
Note though we don't want to deal with just cases where it's 100% we also want a solution that would handle a set of rows of say, 50%, 60%, 70% and just retain the 70% value (as it is closest to 80%, our current target).

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla (cc @AileneKane):

Hi Nacho,

Me again (with apologies for all the messages): could you also make sure in your updated code that all low values are also deleted. For example, at some point we added this to the bb_cleanmergeall.R (I worry I may have done this when not thinking! Apologies, Ailene, for thinking it was you):

`# Now remove any percentbudburst lower than 40% (clean_bbperctodays.R only cleans lines with more than entry per treatment)
d$response.num <- as.numeric(d$response) # only 'timeonly' should be removed here
d <- d %>% filter(!(response.num<39.99 & respvar.simple=="percentbudburst"))#as of 9 apr 2018, deletes 642 rows (8480).
d$response.num <- NULL
`
 And while we *do* want these rows to be deleted we shouldn't start adding code lines to the main cleaning file when they should be handled in another file (in this case, this should happen in clean_bbperctodays.R)  *and* (critically) we need to do it in such a way that it works off our 
`targetvalue <- 80 # we want value closest to this
acceptablerange <- 0.50 # meaning as low as 40% allowed (e.g., 80-80*0.5=40) ## decreasing the acceptable range increases the amount of rows deleted (more values cease to be close enough to targetted values)
`
The code added just used 40% and we don't want a static number like that. I have deleted what was added to bb_cleanmergeall.R for now in hopes we can address this all in clean_bbperctodays.R.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I think it looks good, could you just add some quick notes at the top that say what each of the types do ("add.columns","only.percentBB","BB_analysis")? Once done, could you tag Ailene ...

@AileneKane Once Nacho does the above, could you then triple-check the code? If it looks good I think we can close this!

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla @AileneKane 

Wait! Actually, the code is not working. Try running it on just:
d <- subset(d, datasetID=="falusi90")
And you'll see lots of values still remain that should have been removed. Part of this may be the code I added (to try to remove values BELOW the lowest allowed value), but I am not sure... @MoralesCastilla Can you take a look and let us know?

Thanks!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 

I have made new changes to the code 130e889703efee4832a80a1a7086876461ac943e. Now it does the following:

When a given treatment has >1 records,

- if many records fall within target range, it will only keep the closest to 90.
- if many records fall within target range and one of them equals 90, it will keep that one
- if no records fall within target range, it will keep the closest to 90 (we can delete all these if preferred)

When a given treatment has only 1 record,

- if the record falls within target range, we keep it
- if the record does not fall within target range, we delete it

I have been trying this subsetting d by: 
d <- subset(d, datasetID=="falusi90")

and it seems to work, but again a second/third pair of eyes will help a lot.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I will look at this! I think it sounds close, though have one query. In the first case ('When a given treatment has >1 records') you wrote:

> if no records fall within target range, it will keep the closest to 90 (we can delete all these if preferred)

We should delete ALL records that fall outside the targetrange so I think your code sounds good once we change this. So it should be: if no records fall within target range, it deletes the records. 

Let me know when you have made the change and I will check the code.

Thank you!

**Comment by lizzieinvancouver** [comment]
@AileneKane I think this looks good to me, could you double-check the code one last time for Nacho and me?

**Comment by lizzieinvancouver** [comment]
@AileneKane  I think this looks good to me, could you double-check the code one last time for Nacho and me? Then we can close it!

**Comment by AileneKane** [comment]
@lizzieinvancouver @MoralesCastilla Ok, I have looked at this finally. It looks good except for one thing: in lines 206-210. the "too low" values are not currently being removed because of line 210 (d.subsetted <- d). 
Is this intentional? if so, I wasn't sure why...

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Nacho, when you have a time ... can you check this? It would be good to close this issue, but better to make sure the code is doing what we want!

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Nacho, when you have a time ... can you check this? It would be good to close this issue, but better to make sure the code is doing what we want!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 
Ailene, you were right, I had totally missed that line 210. I have now changed it by `d<-d.subsetted` which I think was the original intention. Now, if we input the subset data for Falusi96 it leaves 219 observations (and not 235). This should be ready to be closed, doesn't it?

**Comment by lizzieinvancouver** [comment]
@AileneKane And ... can you update all the main BB output code with the new change?

**Comment by AileneKane** [comment]
@lizzieinvancouver @MoralesCastilla 
When I try to run step 5a of bb_cleanmergeall.R (source("bb_analysis/cleaning/clean_rampedandexpforcing.R" by @cchambe12 i think), I get the following error:
Error in file(filename, "r", encoding = encoding) : cannot open the connection

Do you get this error too? If so, it should be looked into- it does not run for me and I'm not sure why!

**Comment by AileneKane** [comment]
@MoralesCastilla Otherwise, the falusi issues appears to be solved and I think the bbperctodays code runs fine.
@lizzieinvancouver @cchambe12  I'm hesitant to update all the main BBoutput with this error.

**Comment by lizzieinvancouver** [comment]
I am not getting that error, here's my code:

`> ## housekeeping
> rm(list=ls()) 
> options(stringsAsFactors = FALSE)
> 
> # Set working directory: 
> if(length(grep("Lizzie", getwd())>0)) { setwd("~/Documents/git/projects/treegarden/budreview/ospree/analyses") 
+ } else if
+ (length(grep("Ignacio", getwd()))>0) { setwd("~/GitHub/ospree/analyses") 
+ } else if
+ (length(grep("ailene", getwd()))>0) {setwd("/Users/aileneettinger/git/ospree/analyses")
+ } else 
+   setwd("~/Documents/git/ospree/analyses")
> 
> 
> # Load libraries
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> library(tidyr)
> library(geosphere)
> library(lubridate)

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date

> 
> # 1. Get the data (that has already been cleaned for respvar and chilling)
> d <- read.csv("output/ospree_clean_withchill.csv") # 30 Oct 2018: 12693 
> 
> # 2. Need to deal with thermal time to days
> source("bb_analysis/cleaning/clean_thermaltimetodays.R") # 30 Oct 2018: 12693
Error in eval(ei, envir) : 
  Not an error, thermal time is passed to days now
> 
> # 3. Clean phenstage to get a little more data (a little, but still!). 
> source("bb_analysis/cleaning/clean_respvarmore.R") # 30 Oct 2018: 12152 
> 
> # 4. Select out the highest percentage of budburst only, and remove studies that contain duplicate data in two forms
> source("bb_analysis/cleaning/multiresp.R") # as of 16 July 2017, deletes ~2400 rows (same in May and Oct 2018) 9717 rows
Error in eval(ei, envir) : 
  Not an error, just stopping here to say we have successfully applied multiresp!
> 
> # 5. Clean ambient forcing
> # 5a. Clean up entries where we can estimate the forcing from the paper (e.g., ramped temps or they give monthly temps)
> source("bb_analysis/cleaning/clean_rampedandexpforcing.R")
Error in eval(ei, envir) : 
  Not an error, ambient forcing to days now... getting closer. Also, you can ignore the two warning messages below -- code converts a column to character (twice), but the column is created, used and deleted in this source code and should not (that I can imagine) have any other impact.
In addition: Warning message:
In eval(ei, envir) : NAs introduced by coercion
> `

**Comment by lizzieinvancouver** [comment]
@AileneKane Can you check your paths and that you have the file?

**Comment by AileneKane** [comment]
@lizzieinvancouver ok- found the problem and fixed it! I have updated ospree_withchill_bb.csv

**Comment by AileneKane** [comment]
Ok to close now?

**Comment by lizzieinvancouver** [comment]
@AileneKane Sure! Go for it.
