### ISSUE TITLE
double check some clean_respvarmore code

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#169]
@cchambe12 @dbuona 
Hi Cat and Dan! I think one of you may have worked on this, but do loop in Ailene or Nacho if I am wrong.

I saw a warning in clean_respvarmore.R and in fixing it I worked on this code chunk:

```
## cleaning some phenstages that are daystobudburst
phenstage <- d[which(d$respvar.simple=="phenstage"),]
unique(phenstage$datasetID)
datasets<-unique(phenstage$datasetID)
xx<-d[which(d$datasetID %in% datasets),] # cannell83, gansert02, gunderson12, pagter15, pettersen71, sonsteby13
unique(xx$respvar.simple)
daysto<-xx%>%filter(respvar.simple=="daystobudburst")
```

Could whoever wrote it tell me what it does? And could you confirm that it’s working?

Thanks!
L

**Comment by cchambe12** [comment]
It looks like my code! I think I was just figuring out what studies I needed to focus on... Dan is right, it doesn't change the existing data frame at all.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Okay, I deleted a little of it and left the bit that subsets down to identify which rows to look at (will push this shortly).
