### ISSUE TITLE
work on photoperiod response curves

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#171]
Criteria: study had to have 3 or more photoperiods (and only 3 studies!)

Next tasks:
- divide within each study by the mean response time
- label the differences on each curve

**Comment by dbuona** [comment]
@AileneKane @lizzieinvancouver While I was working on the photo curves I noticed a problem with Caffarra11b. In exp 2, all the treatments produce the same Total Chilling, despite different chilling hours. I reread the paper, and here is how chilling was done. Starting late November (2004), twigs were field chilled for  0, 30, 55, or 95 days, and then forced at different photoperiods. The differential chilling is currently un accounted. We can discuss how/who fixes, I just wanted to share this before I forget.

**Comment by AileneKane** [comment]
I can fix this in the chilling code!

**Comment by dbuona** [comment]
@AileneKane just wanted to remind you about the issue with the chilling in Caffarra11b exp2 above. Now looking at it again, I think there are also weird issues for exp3 in this study too. Maybe be should touch base tomorrow on this?

**Comment by AileneKane** [comment]
Thank you for the reminder! I started to work on this, but got completely confused, as there seem to be many things wrong with this one. The field sample date for all of the cuttings  of caffarra11b is 1-Jun-2004. However, the paper says that "In late November of Year 2, 10 one-year old clones of B. pubescens, kept in a heated greenhouse, were placed outdoors to receive natural chilling."
So, first we need to get the right field sample date, based on the chilling lengths. Then we can pull the appropriate climate data to calculated chilling. It seems to me that for the twigs that received no (0) chilling, it is fine to keep the date at 1-Jun-2004. However, for twigs that received 30 days of chilling, we should make the field sample date Dec 30 (estimating 30 days after "late November"). 

There also seem to be errors in the response column for percent burst in several rows, which should have 0s (not be blank) right?

**Comment by dbuona** [comment]
I agree with you about the field sample date for experiment 2.  I don't see %bb as a response for this study. I am looking at ospree_clean_withchill_BB.csv and "daystobudburst" is the response. However the figure in the paper does have %bb. Should I be looking at an ospree datasheet that is further upstream?

**Comment by dbuona** [comment]
I think I am mostly done, other than tweaks.

**Comment by lizzieinvancouver** [comment]
@dbuona 

- Italicize species names
- Make Fagus like Tilia, make Tilia super fine dots

**Comment by lizzieinvancouver** [comment]
see #180 we're done here.
