### ISSUE TITLE
plots and analyses of species by predictor

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#172]
- make some plots, color-coded by species (complex)
- photo ~ sp ... photo+force+chill~sp (sp as predictor!)

**Comment by cchambe12** [comment]
I made a new script - bb_analysis/collinearity_check.R and some new plots bb_analysis/figures. I'm not entirely confident I did it correctly so I would love to go over it all next meeting! I tried removing any species culprit and the model did work after that but it left us with only 222 rows of data...

**Comment by lizzieinvancouver** [comment]
not needed anymore!
