### ISSUE TITLE
work on figures for limiting cues

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#174]
@cchambe12 @dbuona @AileneKane @chuine @MoralesCastilla 
Any ideas on how to visualize our data would be good. I am struggling with its multivariate nature. Here's the figure notes I am working through ... (numbers are just for reference):

1. Number of studies by year (OSPREE)... How best to show? Such as, by number of species studied by year. Show crops or remove or show separately?
2. Map of studies, color coded or such by which of the three cues they manipulated (then we need 3 maps?!)
3. Variation in treatments across space (photo/chill/force)
4. Variation in treatments across time (graph with year on $x$-axis or divide time in half or such? 
5. Maybe not a figure, but related: X\% of studies manipulated which interacting cues? (i.e., how many studies manipulate 1 cues, 2 cues, 3 cues ... of those manipulating 1 cue, what is the breakdown by cue etc.)

**Comment by lizzieinvancouver** [comment]
Next steps:

1. make 3 panel version of heat map
2. % of studies that manipulated each cue (table)
3. photo x chill map
4. chilling x weinberger: make heatmap version once I have corrected how we count fieldsample dates! (only count sample dates that are two weeks apart)
5. re-make maps and check on lat/long

**Comment by lizzieinvancouver** [comment]
@AileneKane @dbuona @cchambe12 @MoralesCastilla 
Hi all, 
Please review the limitingcues.pdf file within two weeks and also review all the figures ... then suggest which figures should be priorities for the manuscript. 
You can add votes/notes here. 
Thanks!

**Comment by lizzieinvancouver** [comment]
@cchambe12 I really like this suggested figure:

`Figures - for (5) it feels like there is a lot of overlap with those figures... What if we had one figure that had year on the x axis and frequency on the y axis (like you have already `pubyear.pdf') but could we color code the bars by number of cues they manipulated? Maybe we'll see a trend from studies just looking at photoperiod, for example, early on but as time progresses we may see more and more studies manipulating more than one cue. And then a map giving a bit more of a breakdown on which cues and where those studies were done. For the map, were you planning on combing the three into one figure? or stacking the three maps for one figure? Or actually maybe the heat maps will be more useful here? `

Please do work up a version! Thank you!

**Comment by AileneKane** [comment]
@lizzieinvancouver  @dbuona @cchambe12 @MoralesCastilla
Here are my notes on the figures:

1. I really like the heat maps. This is a great way to make the point that we need more combinations of cues to better understand which ones are limiting and under what conditions. I like the idea of having  a summary table to go with them, in the supplement (7 in the list of Figures: "Not a Fgure, but analysis-related: X% of studies manipulated which interacting cues? i.e., how many studies manipulate 1 cues, 2 cues, 3 cues ... of those manipulating 1 cue, what is the breakdown by cue etc.)
2. Maps: I really like these! I need a little help interpreting what they are showing and what the main message is. I like some of the things in the "Doodles" document (a and c), showing winter temperatures (current and future) compared with OSPREE treatments. Can we add this to the map figures?
3. I think it would be helpful to have a figure that supports this key point (from the Abstract): "Show where and how interactive effects of other cues will impact simple linear predictions." After looking at the note at the bottom of the outline "Examples of how cues interact:" I thought a potential figure for this would be showing lines of estimated/predicted days to budburst (y-axis) versus chilling (x-axis), at different photoperiods. 

-

**Comment by lizzieinvancouver** [comment]
Dan and I chatted today, his email is below but the take-homes were:

- heat-maps good
- one time-series figure (the one Cat suggested) is also good
- maybe update the map .... see notes below

map_datasetID: Good addition, but ... any way to show the uniqueness of species? So somehow color or such the points that all does Betula for example? Or heatmap the number of cues instead of showing spp N?

> The main thing I came away with from thinking about limiting cues figures is the question, how essential is it that the reader has a sense of how treatments and studies vary time?
> 
> Unless we are trying to make a claim that we have gotten better or worse over time, I don't see a huge benefit to including figure 6 and 3. Or at least, it seems to me these could be combined, and I do like Cat's idea.
> 
> The figure I think are the coolest are the heat maps. Is that what you meant by figure 4. or were you thinking about geographic maps?

**Comment by cchambe12** [comment]
I just took a stab at the proposed histogram figure. The code is /limitingcues/studydesign_numcues.R and the figure is /limitingcues/figures/studyyearcues.pdf!

**Comment by lizzieinvancouver** [comment]
So cool! What do the NAs mean?

**Comment by lizzieinvancouver** [comment]
@cchambe12 I am running into a similar issue as I see in your figure ... what are the studies that don't manipulate cues doing? Do they do provenance or something else?

**Comment by cchambe12** [comment]
@cchambe make separate color for manipulating just field sample date and then have an `other' category (non-environmental? - think of how to label it!)

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver 
Work on code to figure out cues and fix sections 4-5.

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver See task above and work on heat maps and PEP figure.
@cchambe12 Work on map figure
@dbuona Work on regressions with latitude.

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver needs to work on density curves for PEP725 comparisons

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver Will get the densities for the PEP725 figure today hopefully.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Okay, I added the data for the density lines to add to limiting cues PEP 725 histograms:

Please add two lines to each histogram -- one for all species and one for the particular species (except for FAGSYL min temps as we have no chilling temp treatments on FAGSYL), here are the files. 
- all spp for forcing (max temps), see analyeses/limitingcues/output/cueschilltemo.alldiffs.csv
- all species for chilling (min temps), see cueschilltemp.alldiffs.csv
- each species for forcing (max temps) and chill (min), see analyeses/limitingcues/output/cues_fagben.csv

Let me know if you have any questions or anything looks wrong.

Please also recolor histograms so blue is negative changes only...

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla The new figure (Fig1_noblues_densities.png) looks great! I have only one question -- shouldn't the black (assuming black are all species) density lines be the same for Fagus and Betula?

**Comment by lizzieinvancouver** [comment]
Notes for Lizzie:
- Made in ggplot but nice and multi-paneled: [see here ](https://jcoliver.github.io/learn-r/006-heatmaps.html)
- Some customizations of base f(x): [see here](https://www.r-graph-gallery.com/215-the-heatmap-function/)

**Comment by lizzieinvancouver** [comment]
See also issue #394 for info on spann04, granhus08 and rinne94

**Comment by lizzieinvancouver** [comment]
This seems also covered! See also issues #394, issue #395 and issue #408
