### ISSUE TITLE
check studytable

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#175]
@cchambe12  Hi Cat!
Can you check your code for studytype_table.csv and see why biasi12-exp1 has two lines of data? It says on one there are 14 sampling dates and for the other it says 18 (from the paper I think 18 is correct) ... I want to make sure our code is doing what we think it is.
Thank you!

**Comment by cchambe12** [comment]
@lizzieinvancouver  it looks like there were two species and one species was sampled 14 times (grapes) whereas the other was sampled 18 times (kiwis)! Do you want me to change it somehow or leave it as is?

**Comment by lizzieinvancouver** [comment]
@cchambe12 Ah! Thanks for catching that. I think we're all set. I will open a new issue if I decide we need to change it or have other issues pop up. Thanks!
