### ISSUE TITLE
What is up with freeze.treatment.temp_night?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#176]
@dbuona @AileneKane 
I am working on what to do with studies with other treatments. ... in doing this I got to looking at falusi90 where we list values listed under 'freeze.treatment.temp_night' in looking at this I started wondering if this is how we should  have correctly entered this. And then in looking further I wondered if anything in these columns is correctly entered ... 

Could you each **independently** check this column and the below papers, then discuss and let me know what you think? 

Check also ...
biasi12
basler12
falusi90

But see ...
cook05

**Comment by lizzieinvancouver** [comment]
# Read this later ....

I went back to a really old commit: https://github.com/lizzieinvancouver/ospree/commit/70e8cf156049061210a088f76715a40d467439ff
And downloaded growthchambers_litreview_2016-01-15.csv ... in this file we had column: response   (pre-treatment) ... and I wonder if something was messed up in Excel conversions ....

**Comment by AileneKane** [comment]
Ok @dbuona I have looked at these and have my theories about them. Can we discuss sometime before our next OSPREE meeting? Email me to set up a time!

**Comment by AileneKane** [comment]
Dan and I looked at this independently and discovered a couple of different types of mistakes in the data in this (and all freeze.treatment) columns. The mistakes include: data getting shifted over by one or more columns from its correct column (basler12 and biasili12), and data that simply doesn't belong in those columns (spann04,ruesink). We now have 2 questions:

1. should we clean the data in these columns, given that we are not using them (currently)?
2. should we use any of the data? for example, the basler12 data in this column appears to be chilling data, pre- and post- collection, not freezing. should we compare this to our chilling estimates in the chilling column?

**Comment by AileneKane** [comment]
@dbuona 
I have added most of the required cleaning to aalyses/cleaning/clean_misc.R. Could you check my code and add biasi12? You seemed to have a better handle on what needed to be done with that study.

Still to do: incorporate the chilling data from basler12 into ospree_clean_withchill.csv

**Comment by dbuona** [comment]
@AileneKane 
I fixed most biasli12 columns in analyses/cleaning/clean_misc.R. No freeze treatment were actually applied. 1 column remains dirty (d$freeze.treatment.temp_day) because I think it would need to be migrated later in the chilling calculations, but I wasn't sure where exactly. See note in line 95-96 of clean_misc.R and we can discuss where it makes sense to put this.

**Comment by AileneKane** [comment]
Ok, I added the biasli12 columns to totachillcalc.R! I think this is all set, but Dan, could you check the ospree_clena_withchill file to make sure that it looks ok to you?

**Comment by dbuona** [comment]
@AileneKane to me it doesn't look like anything in ospree_clean_withchill changed for biasli12.

**Comment by AileneKane** [comment]
That's super weird- you checked the Field_Chilling_Hours and Total_Chilling_Hours columns? In my file versions that are no longer NAs, they are filled in with the data previously in the freeze.treatment.temp_day column. Perhaps you try pulling again and check?

**Comment by dbuona** [comment]
@AileneKane I pulled on my arb computer and now it looks good. I'll have to figure out why it seems my laptop isn't updating from github.

**Comment by AileneKane** [comment]
@dbuona @lizzieinvancouver Can we close this issue?

**Comment by lizzieinvancouver** [comment]
@AileneKane It's slated to be closed at the meeting next week after a quick check-in!

**Comment by AileneKane** [comment]
@dbuona @lizzieinvancouver I realized that I never posted my question about basler12, related to this. I was not able to add the chilling data from the paper to ospree because the paper reports the chilling in "chilling days" (the number of days since 1 November with daily mean temperature≤5 ◦C). I don't think we can convert this to any of our chilling metrics, can we?
