### ISSUE TITLE
Write legend and summary of methods for Figures 4-5 in photoperiod ms

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#179]
Phenofit estimates of current/projected with ospree comparisons for Fagus and Quercus

**Comment by cchambe12** [comment]
first stab in /analyses/photoperiod/PhenofitFigs_methods_caption.txt !

**Comment by AileneKane** [comment]
Thanks Cat! Could you add a bit more detail to the methods, including:

1. Which warming scenario was used
2. How the temporal shifts were quantified (within only cells that that were in both current and projected range right?)

**Comment by cchambe12** [comment]
Oh right the projections! Sure thing, I'll add that now. And yes, I only looked at cells that were in both ( (I will also add that now...) but we ended up just doing Days to Budburst rather than calculating any shifts so it ended up being pretty straight-forward.

**Comment by AileneKane** [comment]
one more thing related to this figure- perhaps we should combine the two two-paneled figures in to one four-paneled one with fagus on the top, and quercus on the bottom?

**Comment by cchambe12** [comment]
Yes, I envisioned that as well! And honestly, I'm not even sure if we need Quercus as well if we feel figure heavy. Also, I just added a bit to the caption to cover those 15 extra data points!

**Comment by lizzieinvancouver** [comment]
@AileneKane @cchambe12 I would keep in Quercus! Fagus is often considered a weird outlier so it's better to show more species in this case.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Work on the caption and close.

**Comment by AileneKane** [comment]
@cchambe12 These plots look good! I did notice one small thing, in addition to adding more details to the caption: in panel B the symbols for "OSPREE" and current are incorrect. Could you write more detail on how projected ranges  were projected, and how you estimated "expected shifts in phenology" This may be more detail than we would ideally have in a legend, eventually, but it seems like a good place to put it for now- we can always move it to a supplemental methods section. Thank you!

**Comment by AileneKane** [comment]
Thanks for doing that, @cchambe12!
