### ISSUE TITLE
Write legend and methods paragraph for photo experiments fig photoperiod ms

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#180]
Plant responses to changes in daylength figure (across populations/latitude)

**Comment by AileneKane** [comment]
You can close this if you are done with it, Dan!

**Comment by lizzieinvancouver** [comment]
@dbuona Make some changes to figure ... change a and b to zoom, make lines thicker etc. and then close. Write a better captions!

**Comment by AileneKane** [comment]
@dbuona your photocurves figure looks great! Could you add some detail to the legend: 1) Cite the studies included in this figure here in the caption.2) Make the lines in the legend a bit longer, so that you can see the difference between the dashed lines (Tilia?) and solid lines (Betula) 3) Explain that the different lines within same chill treatment are different populations (perhaps adding latitude if they differ by latitude?).  4) note that studies include different daylengths, for different lengths, and/or varying vs contant photoperiods (if relevant)

Please add it directly in the Sweave document. Thanks!
