### ISSUE TITLE
chill units: should we switch to dynamic model chill portions?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#183]
How much data do we lose? Does it alter the answer (in the centered models)?

**Comment by AileneKane** [comment]
We lose a little data, but not too much:
Rows of data: 4608 for utah, 4490 for chill portions
Num spp: 85 for both units
Num studies: 63 for utah, 61 for chill portions

I have fit models using chill portions and utah units, for comparison. Here are the coefficients from models without interactions:
![image](https://user-images.githubusercontent.com/9097640/42178882-f0c31876-7dff-11e8-85a6-4f06a0cf42af.png)

**Comment by AileneKane** [comment]
Here are the coefficients from models WITH interactions and WITH study id as a random effect:
![image](https://user-images.githubusercontent.com/9097640/42182312-c91b5dea-7e0b-11e8-8129-227749248bbf.png)

**Comment by AileneKane** [comment]
Utah units (range=-1304.5-4724) , mean=1192.415) look more normally distributed than chill portions (range=0-180,mean=67)...my code exploring these is here

**Comment by lizzieinvancouver** [comment]
@AileneKane what is the R2 for each model?

**Comment by AileneKane** [comment]
R2 is higher for the chill portions model:
![image](https://user-images.githubusercontent.com/9097640/42241295-0f1ba1ac-7ed8-11e8-92f8-1fbbff901785.png)

**Comment by lizzieinvancouver** [comment]
@AileneKane Will update with news models.

**Comment by AileneKane** [comment]
I fit our standard model with utah units and with chill portions (with and without crops for each). Here are comparisons:
![image](https://user-images.githubusercontent.com/9097640/49681020-203d0e00-fa50-11e8-8ce2-d9e23acea42e.png)

**Comment by lizzieinvancouver** [comment]
@AileneKane Thanks! What do the "" without numbers mean for the utah.wcrops?

And what R2 did you use? I am thinking I should perhaps check it for the weinberger models that I am working on ...

**Comment by lizzieinvancouver** [comment]
@AileneKane No need, I thought as much!

**Comment by AileneKane** [comment]
here is the code from ChillR, showing how they estimate chilling with the chilling function:
> chilling
function (hourtemps = NULL, Start_JDay = 1, End_JDay = 366, THourly = NULL, 
    misstolerance = 50) 
{
    if (is.null(hourtemps) & !is.null(THourly)) 
        hourtemps <- THourly
    if ((length(names(hourtemps)) == 2) & ("hourtemps" %in% names(hourtemps))) {
        QC <- hourtemps$QC
        hourtemps <- hourtemps$hourtemps
    }
    else QC <- NULL
    if (Start_JDay < End_JDay) {
        hourtemps[which(hourtemps$JDay >= Start_JDay & hourtemps$JDay <= 
            End_JDay), "sea"] <- hourtemps[which(hourtemps$JDay >= 
            Start_JDay & hourtemps$JDay <= End_JDay), "Year"]
    }
    else {
        hourtemps[which(hourtemps$JDay >= Start_JDay), "sea"] <- hourtemps[which(hourtemps$JDay >= 
            Start_JDay), "Year"] + 1
        hourtemps[which(hourtemps$JDay <= End_JDay), "sea"] <- hourtemps[which(hourtemps$JDay <= 
            End_JDay), "Year"]
    }
    if (Start_JDay < End_JDay) {
        relevant_days <- Start_JDay:End_JDay
    }
    else {
        relevant_days <- c(Start_JDay:366, 1:End_JDay)
    }
    normal_lines <- which(!(hourtemps$JDay == Start_JDay & hourtemps$Hour == 
        0))
    normal_lines <- normal_lines[which(normal_lines > 1)]
    hourtemps <- hourtemps[which(!is.na(hourtemps[, "Temp"])), 
        ]
    CH_range <- which(hourtemps$Temp <= 7.2 & hourtemps$Temp >= 
        0)
    hourtemps[, "CH_weights"] <- 0
    hourtemps[CH_range, "CH_weights"] <- 1
    hourtemps[, "CH"] <- 0
    Utah_range_0.5 <- which(hourtemps$Temp <= 2.4 & hourtemps$Temp > 
        1.4 | hourtemps$Temp <= 12.4 & hourtemps$Temp > 9.1)
    Utah_range_1.0 <- which(hourtemps$Temp <= 9.1 & hourtemps$Temp > 
        2.4)
    Utah_range_min0.5 <- which(hourtemps$Temp <= 18 & hourtemps$Temp > 
        15.9)
    Utah_range_min1.0 <- which(hourtemps$Temp > 18)
    hourtemps[, "Utah_weights"] <- 0
    hourtemps[Utah_range_0.5, "Utah_weights"] <- 0.5
    hourtemps[Utah_range_1.0, "Utah_weights"] <- 1
    hourtemps[Utah_range_min0.5, "Utah_weights"] <- (-0.5)
    hourtemps[Utah_range_min1.0, "Utah_weights"] <- (-1)
    hourtemps[, "Utah_Model"] <- 0
    seasons <- as.numeric(unique(hourtemps$sea))
    seasons <- seasons[!is.na(seasons)]
    e0 <- 4153.5
    e1 <- 12888.8
    a0 <- 139500
    a1 <- 2567000000000000000
    slp <- 1.6
    tetmlt <- 277
    aa <- a0/a1
    ee <- e1 - e0
    hourtemps[, "TK"] <- hourtemps$Temp + 273
    hourtemps[, "ftmprt"] <- slp * tetmlt * (hourtemps[, "TK"] - 
        tetmlt)/hourtemps[, "TK"]
    hourtemps[, "sr"] <- exp(hourtemps[, "ftmprt"])
    hourtemps[, "xi"] <- hourtemps[, "sr"]/(1 + hourtemps[, "sr"])
    hourtemps[, "xs"] <- aa * exp(ee/hourtemps[, "TK"])
    hourtemps[, "ak1"] <- a1 * exp(-e1/hourtemps[, "TK"])
    hourtemps[1, "interE"] <- 0
    memo <- new.env(hash = TRUE)
    posi <- 1
    assign(x = paste(1), value = 0, envir = memo)
    E = 0
    xs <- hourtemps[, "xs"]
    xi <- hourtemps[, "xi"]
    ak1 <- hourtemps[, "ak1"]
    S <- ak1
    S[1] <- 0
    E <- S
    options(scipen = 30)
    for (l in 2:nrow(hourtemps)) {
        if (E[l - 1] < 1) {
            S[l] <- E[l - 1]
            E[l] <- xs[l] - (xs[l] - S[l]) * exp(-ak1[l])
        }
        else {
            S[l] <- E[l - 1] - E[l - 1] * xi[l - 1]
            E[l] <- xs[l] - (xs[l] - S[l]) * exp(-ak1[l])
        }
    }
    hourtemps[, "interE"] <- E
    hourtemps[which(hourtemps$interE < 1), "delt"] <- 0
    hourtemps[which(hourtemps$interE >= 1), "delt"] <- hourtemps[which(hourtemps$interE >= 
        1), "interE"] * hourtemps[which(hourtemps$interE >= 1), 
        "xi"]
    Stress <- 1
    Tb <- 4
    Tu <- 25
    Tc <- 36
    hourtemps[, "GDH_weight"] <- 0
    hourtemps[which(hourtemps$Temp >= Tb & hourtemps$Temp <= 
        Tu), "GDH_weight"] <- Stress * (Tu - Tb)/2 * (1 + cos(pi + 
        pi * (hourtemps[which(hourtemps$Temp >= Tb & hourtemps$Temp <= 
            Tu), "Temp"] - Tb)/(Tu - Tb)))
    hourtemps[which(hourtemps$Temp > Tu & hourtemps$Temp <= Tc), 
        "GDH_weight"] <- Stress * (Tu - Tb) * (1 + cos(pi/2 + 
        pi/2 * (hourtemps[which(hourtemps$Temp > Tu & hourtemps$Temp <= 
            Tc), "Temp"] - Tu)/(Tc - Tu)))
    chillout <- data.frame(Season = paste(seasons - 1, "/", seasons, 
        sep = ""), End_year = seasons)
    if (End_JDay >= Start_JDay) 
        dt <- sapply(seasons, function(x) difftime(ISOdate(x - 
            1, 12, 31) + End_JDay * 86400, ISOdate(x - 1, 12, 
            31) + Start_JDay * 86400))
    if (End_JDay < Start_JDay) 
        dt <- sapply(seasons, function(x) difftime(ISOdate(x - 
            1, 12, 31) + End_JDay * 86400, ISOdate(x - 2, 12, 
            31) + Start_JDay * 86400))
    chillout[, "Season_days"] <- dt + 1
    chillout[, "Data_days"] <- sapply(seasons, function(x) length(which(hourtemps$sea == 
        x))/24)
    for (sea in seasons) {
        if ("no_Tmin" %in% names(hourtemps) & "no_Tmax" %in% 
            names(hourtemps)) 
            chillout[which(chillout$End_year == sea), "Interpolated_days"] <- length(which(hourtemps[which(hourtemps$sea == 
                sea), "no_Tmin"] | hourtemps[which(hourtemps$sea == 
                sea), "no_Tmax"]))/24
        chillout[, "Perc_complete"] <- NA
        chillout[which(chillout$End_year == sea), "Chilling_Hours"] <- sum(hourtemps[which(hourtemps$sea == 
            sea), "CH_weights"])
        chillout[which(chillout$End_year == sea), "Utah_Model"] <- sum(hourtemps[which(hourtemps$sea == 
            sea), "Utah_weights"])
        chillout[which(chillout$End_year == sea), "Chill_portions"] <- sum(hourtemps[which(hourtemps$sea == 
            sea), "delt"])
        chillout[which(chillout$End_year == sea), "GDH"] <- sum(hourtemps[which(hourtemps$sea == 
            sea), "GDH_weight"])
    }
    if ("no_Tmin" %in% names(hourtemps) & "no_Tmax" %in% names(hourtemps)) 
        chillout[, "Perc_complete"] <- (chillout[, "Data_days"] - 
            chillout[, "Interpolated_days"])/chillout[, "Season_days"] * 
            100
    else chillout[, "Perc_complete"] <- chillout[, "Data_days"]/chillout[, 
        "Season_days"] * 100
    chillout <- chillout[which(chillout$Perc_complete >= 100 - 
        misstolerance), ]
    return(chillout)
}
<bytecode: 0x11e19de28>
<environment: namespace:chillR>

**Comment by lizzieinvancouver** [comment]
@AileneKane Change the default in models_stan.R to chill portions.

**Comment by lizzieinvancouver** [comment]
@AileneKane Fit the basic models and add to bb compare. Spcomplex no crops expramped fp and all species with expramped.fp

**Comment by AileneKane** [comment]
Add model output to compare document (spcomplex. no crops, all sp with expandrampedfp). give up on exponly.fp.

**Comment by lizzieinvancouver** [comment]
add to models compare file...

**Comment by AileneKane** [comment]
I have added model summaries for crops and no crops (with sp complex and expramp.fp) to bb compare. I will run the not z-scored models tomorrow!

**Comment by AileneKane** [comment]
Because we found better fit with chillportions and because this unit seems to be more stable and recommended (according to ChillR authors), we have switched to using chillportions for our chilling units.
