### ISSUE TITLE
impute (statistical methods)

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#184]
(1) impute with mean of study means (not grand mean of data)
(2) impute with mean of each study if there is one
(3) ...model imputation?

**Comment by AileneKane** [comment]
I have started on this imputation in [analyses/bb_analysis/testdata_impute.R](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/testdata_impute.R)

**Comment by lizzieinvancouver** [comment]
@AileneKane Will update notes here and close.

**Comment by AileneKane** [comment]
I abandoned this effort because we opted not to use brms to fit our models, favoring the flexibility of writing our own stan code. We also discovered that a lot of the data imputation we had done for photoperiod and forcing actually led to some model-fitting problems.
