### ISSUE TITLE
what is up with BRMS being a little different?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#185]

**Comment by dbuona** [comment]
I haven't made much progress in actually understanding these code differences, but I have created some files that might help better STANers than me wrap their heads around this. In the bb_analysis/brms folder there are now 3 new files:
--m2l.winsp.brms_codeextract.txt (This is the stan code used under the brm() "hood")
--ospree_brms_stan_param_comp (This is direct comparison of the parameter block between our stan and brms model)
--make_standata4_m2lwinsp.brms.txt (This is the output from the make_stancode() function discussed on this thread that Lizzie sent out previously(http://discourse.mc-stan.org/t/understand-how-brms-parametrizes-random-effects/4668))

**Comment by lizzieinvancouver** [comment]
Lizzie extract the parameters to start and look into slope/intercept correlation.

**Comment by lizzieinvancouver** [comment]
@AileneKane will add BRMS output to models_bb_compare.xlsx 
@cchambe12 will add rstanarm output

Model is a[sp]+f[sp]+p[sp]+c[sp] + 2 way interactions.

**Comment by lizzieinvancouver** [comment]
You know, a lot of things. It definitely fits a covar between random slopes and random intercepts, it handles the random effects a little differently than we do but we did not dig in to find out why. So, now we just use Rstan! More coding, more fun!
