### ISSUE TITLE
check Ribes ...

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#192]
Why is delaying with forcing?

**Comment by cchambe12** [comment]
[Rplot.pdf](https://github.com/lizzieinvancouver/ospree/files/2163600/Rplot.pdf)

**Comment by cchambe12** [comment]
The most frequent forcing temperature used for the Ribes studies is 20 degrees (
[Ribes_ForceTX.pdf](https://github.com/lizzieinvancouver/ospree/files/2163612/Ribes_ForceTX.pdf)) whereas the rest of the studies have an evenly distributed range of forcing temps 5-30 (
[AllBB_ForceTX.pdf](https://github.com/lizzieinvancouver/ospree/files/2163614/AllBB_ForceTX.pdf). 

If I look at say _Fraxinus excelsior_, which has a stronger advancing forcing cue, the histogram is less extreme than Ribes (
[Frax_forceTX.pdf](https://github.com/lizzieinvancouver/ospree/files/2163622/Frax_forceTX.pdf))

**Comment by lizzieinvancouver** [comment]
@cchambe12 Interesting! Could you try plotting the overall response time versus force, photo and chill (3 graphs) for Ribes versus Fraxinus or any other one easy to grab?

**Comment by cchambe12** [comment]
Here they are! 
[Main_respPlots.pdf](https://github.com/lizzieinvancouver/ospree/files/2170884/Main_respPlots.pdf)
I can add more species after I get back if we want them!
 it's also in bb_analysis/figures/Ribes/Main_respPlots.pdf..

**Comment by lizzieinvancouver** [comment]
@cchambe12 
- check if >200 obs of high force are all one study and should be entered correctly
- check Balser and Laube and see if they say anything.

**Comment by cchambe12** [comment]
Of the 260 observations with forcing at 20 degC
jones12: 21 observations
pagter15: 42 observations
sonsteby14: 197 observations

All of the sonsteby14 response times are low and seem great. The pagter and jones seem  a bit high. 

pagter15: starts applying forcing temperatures very early in the year (February or even November in some cases) so very little chilling. 

jones12: also manipulated chilling - duration and temperature - and found different cultivars have varying sensitivities to chilling but all require enough chilling and chilling is more important than forcing according to this study

**Comment by lizzieinvancouver** [comment]
Pagter15 and Jones12 had high forcing and no chilling ... only one study had multiple forcing levels. So response could be an artifact of study design, will double-check one study with multiple forcing levels.

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver should check again....

**Comment by lizzieinvancouver** [comment]
Yeah, Ribes is a crop with tons and tons of data on it, with weird treatment. It is now part of the crops list and thus generally excluded (also Vitis, Malus, Kiwi).
