### ISSUE TITLE
Write photoperiod paper!

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#193]

**Comment by AileneKane** [comment]
I started the intro, which I feel is quite short currently. I would love ideas for additional important points to include...

**Comment by AileneKane** [comment]
I have a very rough version done, and it needs help! 

Specifically,
1. Let me know where you think additional detail/explanation/examples are needed (right now it is very short!).

2.  If you have ideas about the particular details/explanations/examples that would be strong, please add them to the sweave file or post them on git/email them to me!
It would be great to have your feedback within a week (September 18)- i will make an issue (Github seems to be experiencing problems this morning…)

**Comment by lizzieinvancouver** [comment]
@AileneKane I just added some comments in commit 1adc8ee827982458a5dc041a16a8bb1319f102b2 ... I think it's a great start but there are a lot of ways I think we could all push harder to remember and spell out why this paper is important!

**Comment by AileneKane** [comment]
@dbuona @MoralesCastilla @lizzieinvancouver Please check out the latest draft of this- looking forward to getting feedback on it! (Thank you @cchambe12 for yours!)

**Comment by lizzieinvancouver** [comment]
@AileneKane  I have comments written on the paper form that I will try to scan and email you tomorrow (I am in the Okanagan now). Generally it seems much improved!

**Comment by MoralesCastilla** [comment]
@AileneKane 
I have pushed my comments to the ms., which btw is looking great Ailene!

**Comment by AileneKane** [comment]
I've incorporated changes based on comments from the retreat. I don't think anyone needs to read it again now, unless you're really excited to. I have asked 1 or 2 of you for specific things related to it. otherwise, let's all take a break from it for a bit and focus on the other ospree tasks!

**Comment by lizzieinvancouver** [comment]
Start with NCC, then GCB, then maybe New Pyht or some plant journal ....

**Comment by AileneKane** [comment]
Ailene needs to:
1. make paths relative in sweave file
2. incorporate feedback from NOAA presentation
3. Add to supplement
4. Send to friendly reviewers

**Comment by AileneKane** [comment]
Sent to Heather Kharouba!
