### ISSUE TITLE
what is up with Atlantic lat/long?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#194]

**Comment by AileneKane** [comment]
I think this error was because ospree (not ospree_clean) was used...does that sound right? Could you point me to the code for the map so i can double check?

**Comment by lizzieinvancouver** [comment]
@AileneKane It's in limitingcues/figures/maps/map_photo_sppn.pdf ... which uses ospree_clean.csv

**Comment by AileneKane** [comment]
the lat/long in the middle of the atlantic is from chavarria09, which is supposedly in south america, so i think the latitude is missing a negative sign! I added a line to clean it in the clean_latlong.R file.
