### ISSUE TITLE
ground-truth new data and species

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#196]
@dbuona Can you ground-truth the added species (4 I think)? Make sure they meet all our requirements and that they are being properly parsed in bbstanleadin.R and within that within speciescomplex.R.

@AileneKane Can you pull some of the old datafiles (from github) and compare to the new ones and make sure what has changed makes sense to you?

**Comment by AileneKane** [comment]
I have done some comparisons between the current ospree_clean_withchill_BB.csv file, as well as a version of it in July and in March. between march and now, we have gained chilling data (this may have been responsible for adding 5 new species), lost forcing data from the forectemp column (this makes sense- erroneous schnabel and basler12 data), and lost photoperiod data (from erroneous schnabel data). 
Side question that i want to make sure to ask: do we use the avg_bbtemp column at all? It doesn't look like it from the model code that i have checked, but perhaps i'm missing it. i think there are some studies with NAs for forcetemp that we have data in this column...

**Comment by lizzieinvancouver** [comment]
@AileneKane Will rerun the data, then Lizzie will re-run the model, then back to Dan....

**Comment by dbuona** [comment]
I think there are definitely problems with the complexes. It seems we have 2 files, one which we update complexes manually and one through code. Our current models source a list that was made manually and hasn't been updated, since summer 2017.

I think I have a more sophisticated version almost running, but Cat and I will take a look at it together today, and once it is good, we can discuss where in cleaning we should put it so it is automatically updating when the data updates.

**Comment by cchambe12** [comment]
@dbuona I made some small tweaks to your code, I think it's all fixed! Do you mind checking through it again and if it's okay can you write a new .csv file using the last line of code before the break?

**Comment by AileneKane** [comment]
II have updated the data, and Lizzie has updated the model graphs etc.- she noted that they still appear to have the same weird FP interaction etc.

**Comment by lizzieinvancouver** [comment]
@dbuona @cchambe12 Nice work! Once we're happy with it we need to clean it up so it's a ready-to-go source file (delete any setting of working directory and deal with the conflicts tidyverse is creating  ... do we need tidyverse or can we get by with less? It conflicts with rstan ....). Let me know if I can help.

**Comment by lizzieinvancouver** [comment]
Here are the current conflicts ...

```
> source("source/speciescomplex.R")
── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──
✔ tibble  1.4.2     ✔ purrr   0.2.4
✔ tidyr   0.8.0     ✔ dplyr   0.7.4
✔ readr   1.1.1     ✔ stringr 1.3.0
✔ tibble  1.4.2     ✔ forcats 0.3.0
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ tidyr::extract() masks rstan::extract()
✖ dplyr::filter()  masks stats::filter()
✖ dplyr::lag()     masks stats::lag()
```

**Comment by dbuona** [comment]
Cat, The loop looks good to me and the output makes sense to me (thanks for doing it!). Perhaps tomorrow we can all discuss how to best integrate this in to the workflow.

**Comment by lizzieinvancouver** [comment]
@dbuona @cchambe12 source the new speciescomplex in bbdataplease ... updated bbdataplease and delete source of speciescomplex in bbdataleadin....

**Comment by lizzieinvancouver** [comment]
@dbuona @cchambe12 @AileneKane I updated the models today ... and they are still wonky (and actually not fitting super well when you check the n_eff). But I am not sure the complexes is working. Some examples:
- Prunus persica: only one factor varies and it looks like one study (see M1inter_collinear.pdf for what I am looking at, I checked these against the data in the bb.stan object too)
- Picea glauca looks like one study
- Pyrus_complex one study, same for Pyrus_pyrifolia, Rhododendron_complex, Tilia_complex, Sorbus_complex, Sorbus_commixta

Note that tidyr overwrites rstan commands still conflict. If we can write it without tidyr that would be great... if not, let me know and I will take a look to make a work-around. 

Also, I am not sure we ever wrote down how we decided what is required to be in the model as a species or complex, but it's in your code.... can you please add some notes at the TOP of the file of what it does in a way that makes it clear what the method was. 

Let's try to get this fixed soon so we can move on with the model issues, let me know what I can do to help! And thanks for all the work on this!

PS: I think we should use require for packages in source code? See here: https://www.r-bloggers.com/difference-between-library-and-require-in-r/

**Comment by lizzieinvancouver** [comment]
@AileneKane Can you add these studies to those we double-check? I wanted to make sure we have not corrected papers into being wrong when they were right to begin with:

- schnabel87
- guerriero90
- morin10
- hawerroth13
- linkosalo06
- hawkins12
- cronje03
- devries82
- heide15
- thielges75
- ghelardini10
- ashby62
- caffarra11b
- basler12
- ruesink98
- spann04

By the way, here are the explicit instructions about how to do spot-checks (please include these when you get the list out and add anything you can think of):

- Check BOTH the original OSPREE file (ospree.csv) and ospree_clean_withchill_BB.csv 
- Look at any differences between the two files and make sure they make sense
- Check the levels reported and the tables/figures cited
- If you believe there is an error, start an issue ... do not make any changes yet.
- Check carefully! I think we almost all now have suggested to correct a paper that WAS correct upon closer inspection.

**Comment by cchambe12** [comment]
@lizzieinvancouver I will fix the `require' issue now - that's good to know. I always wondered what the difference was!

As for the issues, I think I may know what's going on... I think we forgot to take out the ones that only manipulated one cue. I will work on this today and try and finish it by the end of the day so we're all caught up. Thanks for catching this!

**Comment by cchambe12** [comment]
@dbuona I _think_ we should be good to go now. Would you mind double checking everything to make sure it looks okay? I added code to make sure that we were including studies that manipulated more than one cue and I also moved the source code around. The biggest issue was I had it set up to make the species list first, before subsetting the data to just daystobudburst and percentbudburst so many more species were being added to our list. After these changes, there are 40 species/complexes included in our model (soon to be 41, I saw a misspelled species that I fixed in the cleaning code so after Ailene updates the files we should have at least one more species). Thanks!

**Comment by dbuona** [comment]
@cchambe12 The speciescomplex.R code looks good to me, and the integration with the rest of it seems to mostly make sense. I am a little confused about how we go from bb.noNA (line 26) to bb.noNA.wtaxa (line 35). It seems to me like we aren't really using bb.noNA (lines 23-28) in the generation of our working data. Am I correct about this and is this intentional?

**Comment by cchambe12** [comment]
@dbuona the way I tried to set it up (please check to make sure!)... is that I used the bb.noNA in the speciescomplex.R source code. So the first two source codes are used and create a new dataframe (which ultimately is called `d') and then that is used in the speciescomplex.R code

**Comment by AileneKane** [comment]
@dbuona @cchambe12 Should I go ahead and update ospree_clean, ospree_cleanwith chill, etc?

**Comment by cchambe12** [comment]
@AileneKane I think you can go ahead! Thanks!

**Comment by lizzieinvancouver** [comment]
Okay! I finally sat down for a while on this today. Prepare yourself ....

First, I pulled the ospree_clean_withchill_BB.csv from two previous dates: 8 Jun and 2 July 2018 ...
Then I ran the models now and then:


```
  | now_ni | now_wi | jul_ni | jul_wi | jun_ni | jun_wi
-- | -- | -- | -- | -- | -- | --
a_sp | 76 | 81 | 74 | 74 | 72 | 94
mu_b_force | -1.6 | -1.5 | -1.4 | -1.1 | -1.1 | -1.9
mu_b_photo | -0.2 | -0.2 | -0.3 | 0.3 | -0.6 | -1.2
mu_b_chill | -2.6 | -4.6 | -2.5 | -5 | -2.8 | -6.8
cf |   | 0.05 |   | 0.1 |   | 0.1
cp |   | 0.07 |   | 0.1 |   | 0.1
fp |   | -0.03 |   | -0.06 |   | 0.002
nrow | 2253 | 2253 | 2061 | 2061 | 1899 | 1899
unique_sp | 41 | 41 | 39 | 39 | 36 | 36

```

**Comment by lizzieinvancouver** [comment]
Next I spent a while trying to compare the data then and in June. This was hard, as there are A LOT of differences, but in looking at the two files in FileMerge, I realized the main things to worry about are our changes in forcetemp, photo and chill so I built some smaller datasets to help me compare them:

`nowd<- read.csv("~/Documents/git/projects/treegarden/budreview/ospree/analyses/output/ospree_clean_withchill_BB.csv")

nowdsm <- subset(nowd, select=c("datasetID", "ID_chilltreat", "study", "photoperiod_day", "forcetemp", "Total_Chill_portions")) 

befd <- read.csv("~/Documents/git/projects/treegarden/budreview/ospree/analyses/output/older/ospree_clean_withchill_BB8Jun2018.csv")

befdsm <- subset(befd, select=c("datasetID", "ID_chilltreat", "study", "photoperiod_day", "forcetemp", "Total_Chill_portions"))

write.csv(befdsm, "~/Desktop/before.csv")
write.csv(nowdsm, "~/Desktop/now.csv")

# Does not help ...
# try <- merge(nowdsm, befdsm, by=c("datasetID", "ID_chilltreat", "study"), all.x=TRUE, all.y=TRUE, suffixes=c(".now", ".before"))

library(dplyr)
tryagain <- anti_join(nowdsm, befdsm)

unique(tryagain$datasetID)

# Now I write out the simple forms of the data and look at the datasets/rows that tryagain says do not match ... 
write.csv(befdsm, "~/Desktop/before.csv")
write.csv(nowdsm, "~/Desktop/now.csv")
`
And here's what I found:

8 Jun 2018 versus today ...

chavarria09 (Prunus) -- added photoperiod (was ambient)
falusi96 -- added previously missing photoperiods
guak98 -- added photoperiod (was ambient)
jones12 -- added photoperiod (was ambient)
rinne97 -- added photoperiod (was ambient)
sanperez10 -- added photoperiod (was ambient)
caffara11b -- changed chill portions
gansert02 -- added photoperiod (was ambient)
gianfagna95 -- added previously missing photoperiods
gomory15 -- added photoperiod (was ambient)
granhus09 --- can't figure out
heide12 -- added a few chill rows (chill_portions--55.84854)
lam37 -- added photoperiod (was ambient)
linkosalo06 -- added photoperiod (was ambient)
morin10 -- added photoperiod (was ambient)
nishimoto95 -- added previously missing photoperiod
partanen01  -- corrected some photoperiods (19.1673 and 10.1675 etc.)
partanen98 -- corrected some photoperiods (similar to above)
schnabel87 -- added photoperiod (was ambient)
sonsteby13 -- added photoperiod (was ambient)
sonsteby14  -- added photoperiod (was ambient)
yazdaniha64 -- added photoperiod (was ambient)

**Comment by lizzieinvancouver** [comment]
@AileneKane @cchambe12 @dbuona @MoralesCastilla 

I just updated this issue! 

Please check out my two recent posts on this. I think we may have inadvertently just tested our hypothesis that you can't estimate photoperiod effects given ambient photoperiod?! I posted some of the needed files if you want to look also in my commit: 7d7a9a76aa844c4366e7e1cae43946cd48bebe9b

What to do next? Let's discuss at the next meeting (this week) and think about models to test this .... I suggest we also start adding some columns to help us flag chilling, photoperiod and forcing that was ambient or was somehow not experimentally manipulated. @AileneKane @cchambe12  Could you coordinate and work on this? And let us know how we can help!

**Comment by lizzieinvancouver** [comment]
We covered this ... in meetings and wrapped up at the retreat. Adding ambient photoperiod is just hot a super idea when you are otherwise working on EXPERIMENTAL photoperiod. Want more evidence of this? Try making your ramped treatments sort of ambient.
