### ISSUE TITLE
continue excellent efforts on species ranges in OSPREE

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#197]
I suggest starting with fagsyl and betpen and try to calculate some of the metrics we're interested in:

- geographical position within (or beyond) range of each species in each study
- climatic position within (or beyond) range of each species in each study
- distance to coast

See how far you get ..

**Comment by lizzieinvancouver** [comment]
As discussed on 10 October 2018: First steps could be:
1. Get a list of all species in OSPREE that are in more than two papers
2. Also get a list of all species in OSPREE in any one paper that manipulates all three cues (I suspect this is not many)
3. Pull range maps for said species!

**Comment by lizzieinvancouver** [comment]
Update: Progress ongoing at the 2018 Dec Retreat!

**Comment by lizzieinvancouver** [comment]
@AileneKane Will send a couple lines of code for calculating chill portions using mean (and for min and max), then @MoralesCastilla will try to add.

**Comment by AileneKane** [comment]
@MoralesCastilla @cchambe12 Below is some code to calculate chilling with ChillR, starting with fake climate data that has a Tmin and Tmax (Step 2, using functions in ChillR to create hourly data specific to a latitude) and then with climate data that has just Tmean (not using the ChillR functions to create hourly data, but using ChillR to estimate chliling). For the values that i picked, the two approaches yield the same chilling estimates.  Let me know if you have questions!

#Code to calculate change in chilling using ChilR
#By Ailene
#12 December, 2018

# housekeeping
rm(list=ls()) 
options(stringsAsFactors = FALSE)

# load libraries
library(chillR)

# Setting working directory. Add in your own path in an if statement for your file structure
if(length(grep("lizzie", getwd())>0)) { 
  setwd("~/Documents/git/treegarden/budreview/ospree/bb_analysis") 
} else if (length(grep("ailene", getwd()))>0) {setwd("/Users/aileneettinger/Documents/GitHub/ospree/analyses/bb_analysis")
}else if(length(grep("Ignacio", getwd()))>0) { 
  setwd("~/GitHub/ospree/analyses/bb_analysis") 
} else if(length(grep("catchamberlain", getwd()))>0) { 
  setwd("~/Documents/git/ospree/analyses/bb_analysis") 
} else if(length(grep("danielbuonaiuto", getwd()))>0) { 
  setwd("~/Documents/git/ospree/analyses/bb_analysis") 
}else setwd("~/Documents/git/projects/treegarden/budreview/ospree/analyses/bb_analysis")

#1. Create data frames of fake climate data
days<-31 #number of days of climate data
yr<-2018#year of climate data
JDay<-seq(1:days)#DOYs- in January in this case
Year<-rep(yr,length(JDay))
lat<-45.5#latitude

#2. Estimate chilling using Tmin and Tmax
#use min and max daily temp to create fake climate data frame for January 2018 
Tmin<- -5
Tmax<-10
minmaxdaily<-data.frame(Year,JDay,Tmin,Tmax)

#Convert daily tmin and tmax data to hourly data, using packaged functions in chillR
hrly<-stack_hourly_temps(latitude=lat,make_hourly_temps(lat, minmaxdaily, keep_sunrise_sunset = FALSE))$hourtemps

#Chilling calculations for lat and time period of interest (January 2018 in my example)
chillcalc <- chilling(hrly, hrly$JDay[1], hrly$JDay[nrow(hrly)]) 

#3. Alternative: estimate chilling using one mean temperature

#use constant mean daily temp to create fake climate data frame for January 2018
Tmean<- 2.5
meandaily<-data.frame(JDay,Year,Tmean)
#convert mean daily temperature data to hourly data
hrly.temp =
    data.frame(
      Temp = c(rep(meandaily$Tmean, times = 24)),
      Year = c(rep(meandaily$Year, times = 24)),
      JDay = sort(c(rep(seq(1:length(JDay)), times = 24)))
      )

chillcalc.mn<-chilling(hrly.temp, hrly.temp$JDay[1], hrly.temp$JDay[nrow(hrly.temp1)])

**Comment by cchambe12** [comment]
@MoralesCastilla  See Chill portions code in ospree/analyses/bb_analysis/PEP_climate/fagsyl_climate_prep.R (you can change it from `Chill_portions' to `Utah_Model' to compare) starting at line 207

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Will update the posted data, then @dbuona will lead efforts on next steps.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Will expand to 6 species we think we have decent data on...

**Comment by lizzieinvancouver** [comment]
Next steps are some simple models ... [see here](https://github.com/lizzieinvancouver/ospree/wiki/Ranges) : Take species-level means from posterior for chill and forcing cues ... and then look for basic tests of relationship.... Should get a bigger team working on this at a retreat or such.

**Comment by dbuona** [comment]
for brms model: chilling effect size ~ (mean SD of GDD) + (mean SD of chill portions)
Population-Level Effects: 
            Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
Intercept        -9.39    9.28   -25.55     9.10       1523   1.00
meanSDchill    0.55    0.39    -0.12       1.34       1224   1.00
meanSDforce  0.00    0.07    -0.16       0.13       1097  1.00

Family Specific Parameters: 
      Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
            sigma     1.81      1.58     0.62     5.49        672 1.00

**Comment by lizzieinvancouver** [comment]
@dbuona Will update notes and report back tomorrow (Friday).

**Comment by lizzieinvancouver** [comment]
Goal to have species list and all range climate info in hand for retreat @dbuona @MoralesCastilla

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Will send @dbuona some code that does a couple example species, then @dbuona will take over pulling ranges and related climate data. Please have update on progress towards this by 30 Oct. Thanks!

**Comment by dbuona** [comment]
@MoralesCastilla  From the Caudullo 2017 paper I was guided to here (https://www.fs.fed.us/nrs/atlas/littlefia/#Introduction) and  was able to find shape files for 13 of our ospree North America trees. Do you know of any other places we might be able to find good north American range maps?

**Comment by MoralesCastilla** [comment]
@dbuona Hi Dan, the best repository for shapefile maps of northamerican species (that I'm aware of) is:
[https://github.com/wpetry/USTreeAtlas](url)
I have not checked it much recently, but for NA species in ospree that are not there, I guess we would need to use GBIF?

**Comment by lizzieinvancouver** [comment]
Making a reference to this in our wiki pages and closing!
