### ISSUE TITLE
Cross-check photoperiod and other treatments 

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#201]
@lizzieinvancouver @cchambe12 @dbuona @MoralesCastilla 
I created folder called "checkphotoperiod" that contains a file with assignments for files to check for two things:
1) That all forcing, chilling, and photoperiod columns in ospree_cleanwithchill_BB.csv are correct and consistent with the paper. Also check that ospree.csv is correct and consistent with the paper.
2) Note which studies that manipulate photoperiod found significant effects of photoperiod on phenology. 

Your tasks are to:
1) Read the checkphoto_README.txt file. Let me know if you have questions/concerns about your tasks.
2) Look at the checkphoto_info.csv to see which papers you are assigned to check.
3) Check your assigned papers for the two things listed above and fill in the checkphoto_info.csv. Push/sync your changes to the file.
4) When you do note  inconsistencies between your papers and ospree, create an issue on git for the problem.

We each have 6-10 papers to check.

**Comment by AileneKane** [comment]
@cchambe12 Thank you for all your work on your papers! I have a favor to ask, if it is not too much trouble: in the "photo.eff.description" column, for studies in which there was a significant effect of photoperiod, could you add specifically what the effect was? For example, instead of  "especially when coupled with low chilling" as is currently written for hawkins12, it would be more helpful if you said "longer days reduced the number of days to budbreak, especially with lower amounts of field chilling"
@dbuona @MoralesCastilla please keep this in mind when you enter your studies too!

**Comment by cchambe12** [comment]
Done! @AileneKane let me know if I need to further clarify any notes in particular!

**Comment by AileneKane** [comment]
Thank you @cchambe12! looks great!

**Comment by AileneKane** [comment]
Thank you everyone! Yay!
