### ISSUE TITLE
Paper check: basler12

### ISSUE THREAD

**Issue by cchambe12** [lizzieinvancouver/ospree#202]
basler12 photoperiod is wrong. Initial photoperiod is used in our dataframe but they increased photoperiod by 3-4min per day in the experiment

**Comment by lizzieinvancouver** [comment]
@cchambe12 Okay, this is not necessarily wrong but a really tricky one. What do you suggest we change photoperiod to? Average over the time from start to budburst? This gets messy fast....

**Comment by cchambe12** [comment]
@lizzieinvancouver 
ahh right! I seemed to remember when this came up in the past we would use the photoperiod at budburst, which I can calculate if we want to do this!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Let's discuss at the meeting. We should only change OSPREE data that is really wrong. I am not sure this is.

**Comment by cchambe12** [comment]
@cchambe12 Clean in clean photo for budburst analysis only and just do what you have been (photo at budburst).
