### ISSUE TITLE
Paper check: hawkins12

### ISSUE THREAD

**Issue by cchambe12** [lizzieinvancouver/ospree#203]
nothing was inputted to ospree.csv for all three cues from hawkins12. This needs to be updated! They do an entire photoperiod experiment

**Comment by lizzieinvancouver** [comment]
@cchambe12 
I see there is mention of a photoperiod experiment in the paper, and I see data across populations entered in the ospree database. But I don't see the data on the photoperiod experiment that we could actually extract ... could you please specify where the data are in the paper that should be extracted?

**Comment by cchambe12** [comment]
@lizzieinvancouver 
Under `Methods & Materials' on pg 510 under a subheading _Photoperiod experiment_
"On 8 January and again on 20 February 2001,
five trees from each population were placed in two
controlled environments: long days (LD) 16/8 h D/N
and short days (SD) 8/16 h D/N with 218C
day temperature and 128C night temperature."

**Comment by lizzieinvancouver** [comment]
@cchambe12 Okay, so what figures/tables does this match up with?

**Comment by cchambe12** [comment]
@lizzieinvancouver Figure 5

**Comment by lizzieinvancouver** [comment]
@cchambe12 Okay, it's unclear if that figure is entered in OSPREE, it's hard to tell as the figure numbers are not entered, but the only data entered are for 1998 and the photoerperiod treatment happened in 2001 so I highly doubt it. Unless you think these data are entered, these are unentered data and I would go with the original data enterer's decision not to enter them.

**Comment by cchambe12** [comment]
@lizzieinvancouver  
Okay! I was hopeful we could get some additional data from this study but that makes sense. Good catch with the year!

**Comment by lizzieinvancouver** [comment]
Closing issue as no evidence there's anything wrong, but there's potentially more data in the paper ...
