### ISSUE TITLE
make a new column for type of chilling

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#207]
I made this up, change as you see fit!
exp: experimental only
fc: field chilling
exp.fc: experimental and field chilling
none: no chilling (just leave empty?)

**Comment by lizzieinvancouver** [comment]
It also occurred to me we should make clear if this info is general (then we would have this info for some studies where we don't calculate field chilling as we don't have climate data) or only applies to our chilling calculation columns. Doing the former would be more complete but I am HAPPY to do the latter if it's easier.

**Comment by AileneKane** [comment]
I did the latter for now, in totalchillcalc.R,  as it was easier to do. It shouldn't be too hard to add a new category for sites that we have no information because there are no climate data available, if we want that. The categories are:
### 6 types: 
           ### NA (no info on chilling); 
           ### exp (experimental chilling only)
           ### fldest (our estimate of field chilling, based on climate data from the provenance lat/long)
           ### fldrep (field chilling that the study reported)
           ### bothrep (both experimental and field (our estimate) chilling)
           ### bothest (both experimental and field (reported by study)

**Comment by AileneKane** [comment]
@lizzieinvancouver I believe this is done, but it would be helpful for someone to check...

**Comment by AileneKane** [comment]
@dbuona could you check the code?

**Comment by dbuona** [comment]
this code all looks right to me!

**Comment by AileneKane** [comment]
great! I think we can close this
