### ISSUE TITLE
Bibtex issues I am working on

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#21]
sonsteby09a and sonsteby09b but only one bibtex (strawberry paper, Tim and Dan are still working on)

DO NOT ADD: Myking 1999, in bibtex, no data -- there's really no data, delete from bibtex for now ... see comment far below I think this paper presents data we already have from other Myking papers

OKAY: webb78 -- actually a 1977 paper (leave as webb78) 

FIXED: darrow36 vs Darrow 1927 -- Strawberry paper, not worrying about anymore; deleted BIBTEX entry

FIXED: guerriero90 vs Guerriero 1991 -- Wrong paper, changed to: Should be Chilling effect on inhibition removal in Kiwi removal

FIXED: heide93 vs heide93a and heide93b -- updated to heide93 and heide93a (Fagus paper) only

FIXED: jones12 versus Jones 2013 -- Bib entry was wrong, it is a 2012 paper (fixed bibtex)

FIXED: lyndon77 vs Lyndon 1978 -- Wrong paper, changed to: Should be Interacting processes in development at the shoot apex 

OKAY: pettersen71 versus pettersen 1972 -- Paper is actually in 1972 (leave as pettersen71) 

OKAY: thielges75 vs Thielges 1976 -- Paper is actually 1976 (leave as thielges75)

**Comment by danfbflynn** [comment]
sonsteby09a is not clear. Data shows two varieties, both Korona and Florence. Paper and citation that we have as 2009a is only for Korona.

Other 2009 paper (2009b) is 
@article{sonsteby2009environmental,
  title={Environmental control of flowering and runnering in three contrasting populations of Fragaria chiloensis},
  author={S{\o}nsteby, A and Heide, OM},
  journal={The Journal of Horticultural Science and Biotechnology},
  volume={84},
  number={3},
  pages={267--272},
  year={2009},
  publisher={Taylor \& Francis}
}

**Comment by danfbflynn** [comment]
myking99 looks like one we could potentially add, not in data set now.

**Comment by lizzieinvancouver** [comment]
Okay, we could add myking99 -- but it appears to be a review paper of previous experiments -- you cannot tell when these experiments were done (at least I could not) so you cannot tell how much they overlap with other studies and the authors state:

The present paper gives a brief synopsis of recent studies of winter dormancy release in Scandinavian Betula pendula and B. pubescens ecotypes, with emphasis on clinal variations in the timing of this property and on different temperature and daylength effects on dormancy release and budburst.

And then at the start of the methods:
Details concerning material and methods are properly described in previous papers (MYKING & HEIDE 1995, MYKING 1997a).

So, I am not going to try to enter this paper. If someone really wants it, s/he needs to *carefully* check what is in this paper versus the 3 other Myking papers already entered.
