### ISSUE TITLE
partanen98 question

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#214]
for this study, nearly all of the photoperiods should be ramped (some are lengthening and some are shortening) if they are not ambient. in ospree.csv only the starting photoperiod is used.  
@cchambe12 i think you changed these values to the photoperiod on the day of budburst. 
2 questions:
1) @cchambe12 is this correct?
2) @lizzieinvancouver Is the approach we want to use? (alternatively, we could use the mean...or perhaps there are other ways to deal with this?)

**Comment by lizzieinvancouver** [comment]
@AileneKane Doesn't it say in other.treatment that they are ramped? I am not sure how we should handle it but I think it should happen in the bb cleaning and we should discuss it.... @cchambe12 
I think you tried to standardize to one method for the BB cleaning, right?

**Comment by cchambe12** [comment]
@lizzieinvancouver @AileneKane 

Yes, I changed these values to the photoperiod at the day of budburst. And yes, I used this same method across ramped studies or ambient studies - found the photoperiod for the day of budburst.

**Comment by lizzieinvancouver** [comment]
All set!
