### ISSUE TITLE
chilling for viheraaarnio06

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#216]
this study had no chilling. the chilltemp and chilldays columns are blank. should we change chilldays to 0?

**Comment by lizzieinvancouver** [comment]
@AileneKane Can you check for whether we ever entered chilling as zero and let me know? I don't think we did ... so if we start doing it now, we should think carefully about that.

**Comment by lizzieinvancouver** [comment]
@AileneKane add to clean_misc.R  ... but make a big note that we inconsistently did this when we first entered data so other entries may be 0 also but not listed as such

**Comment by AileneKane** [comment]
I've done this.
