### ISSUE TITLE
check for studies with thermoperiodicty versus photoperiodicity!

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#220]

**Comment by cchambe12** [comment]
added a new script /bb_analysis/thermovsphotoperiodicity.R with notes.
Partanen01: seems to be the real only example with different forcing temperatures from day and night cycle. Only studies _Picea abies_. 

Myking97: may be another example - either has constant forcing or fluctuating forcing but it as little less descriptive.
