### ISSUE TITLE
build on the photoperiod conceptual diagram

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#221]
@MoralesCastilla let me know if you have any questions! here is the file https://github.com/lizzieinvancouver/ospree/blob/master/analyses/photoperiod/figures/photocondiag2.ai

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Graciously offered to work on next steps... clean up photodiag4_EMW.ai ... maybe call it 5?!

**Comment by MoralesCastilla** [comment]
I have now made a couple 'cleaned' versions of the figure. The bottom right panel still needs work. I'll see what suggestions you guys have later today.

**Comment by AileneKane** [comment]
@MoralesCastilla I made some tweaks to this after talking with Lizzie. Thanks so much!
I also closed issue #204

**Comment by AileneKane** [comment]
Ailene will make colors higher contrast, make model x.axis be temperature and forecast x.axis be year
