### ISSUE TITLE
Photoperiod check - Schnabel87

### ISSUE THREAD

**Issue by MoralesCastilla** [lizzieinvancouver/ospree#224]
I´m marking the treats.okay column (checkphoto_info) as an N for this study, because of some non-numeric values in the forcetemp night and photoperiod columns. I'm guessing you're aware of this. Double-checking just in case.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Cat will look into!

**Comment by cchambe12** [comment]
There were a couple of rows of data that were ramped. I fixed this to follow the new ramped protocol in clean_photoperiod.R. That said, it's a Vitis study, which is currently removed.
