### ISSUE TITLE
gamma and inv_gamma models

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#226]
@cchambe12   Try running our main Stan models with gamma (or inv_gamma) ... maybe try adding small numbers to zeroes (i.e., compare adding 1 versus 0.01 to ALL DATA)

**Comment by cchambe12** [comment]
I started working on this: 1) only Gamma works - not inverse 2) we need to use centered data (uncentered model output was comical) 3) The results are pretty wonky but the posterior predictive checks and R hats are really nice.

**Comment by lizzieinvancouver** [comment]
@cchambe12 I think you have to back convert the numbers! For the negative binomial I have running the numbers make sense if I exponentiate them but I think it's more gymnastics for the gamma. Maybe see if you can find some vignettes online?

**Comment by dbuona** [comment]
Don't work.
