### ISSUE TITLE
get a phylogeny of all species (200 now)

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#228]

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 
My first stab at getting a phylogeny for the species in ospree is now pushed (49e31d3708cc725a16be5b27013c1cfbb38f139b). It contains 211 species, to encompass as many species as possible from the global dataset. My next step is to prune this tree and produce an `ospree.clean.phylo.tre` with only 200 species.

**Comment by lizzieinvancouver** [comment]
Table S2: Chill units in the field before harvest (January 2015), until 1 April and 1 May 2015 at each site, and in growth chamber conditions (including field chilling experienced before cuttings entered the chambers).
 Site
Harvard Forest
St. Hippolyte
Treatment
Field chilling until collection Field chilling to 1 Apr
Field chilling to 1 May
Field chilling + 4.0 àC x 30 d Field chilling + 1.5 àC x 30 d Field chilling until collection Field chilling to 1 Apr
Field chilling to 1 May
Field chilling + 4.0 àC x 30 d Field chilling + 1.5 àC x 30 d
Chilling Hours 892 1153 1449 2140 2140 682 796 1166 1930 1930
Utah Model 814.50 980.00 1360.50 2062.50 1702.50 599.50 653.50 937.00 1847.50 1487.50
Chill portions 56.62 79.37 99.94 94.06 91.17 44.63 63.55 83.83 82.06 79.18

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla We decided it would be best to do models with fixed effects for species using ONLY studies where they manipulated both forcing and photoperiod at once. For this we can also include Flynn experimental data....

Cat (@cchambe12)  added some info on which OSPREE data meet this criteria and I added an ugly format of the Flynn data (sorry); I think I gave all the treatment info you need to add it into the OSPREE data, but shout if not.

Once all the data together we think the model should be:
resp ~ sp + force + photo + chill + force*sp + photo*sp + chill*sp

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla So next step would be to format the Flynn data so it can be added early in the phylogeny/source/bbstanleadin.phyla.R code, then that code should give you data to work with for the phylogeny!

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I chatted with Jonathan and he says ...
(a) You should not fit a model to get estimates of each cue and then look at phylogenetic signal (pagel's lambda) on the cues, instead you should fit a phylogenetic mixed model in BRMS and it will give an equivalent estimate of lambda (I will try to send some papers).
(b) You should use a decent tree, but Jonathan thinks if you have common species you can just prune the Zanne tree published a few years back. No need to use phylogenerator (he said it is easy to screw up if you don't curate it carefully and we probably do not need it)

**Comment by lizzieinvancouver** [comment]
Way to go!
