### ISSUE TITLE
run models

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#231]
**Please try to finish your models by noon PDT on 29 November! If you are not done then, please post what you have.**

1. Make an R file similar to models_stan_normal.R
2. Be sure to edit bbstandleadin.R so it produces any form of the data you need (do NOT create a new bbstanleadin.R, just ask it to output what you need)
3. You should run three main types of models as outlined in models_stan_normal.R (see 'Overview of the models run below' in that code).
4. You should run each model type on FOUR versions of species: all species; spcomplex species; spcomplex.onecue species; spcomplex.nocrops (Cat is working on this last one)
5. So, you probably need to run 12 models! 

Now, for each model:

1. Test your model code works, but using testdata_generate.R 
2. Work on generated   quantities and better PPC than I have done! Side note: push your Stan code, but do NOT push any of the big model output files. 
3. Add data as OSPREE_compare_yourwork
4. Save this tab as   OSPREE_compare_YOURNAME.csv … so save as a CSV.
5. Push just the CSV mentioned in B to   git! This way, we should have no conflicts.
6. checkout master of this file, or in   some other way, don't edit it.

Who is doing what?
@cchambe12 is doing a couple negative binomial models (rstan) and gamma models (brms)
@MoralesCastilla is doing experimental forcing and experimental photoperiod data (use all chilling types) in Rstan
@dbuona is doing experimental *and* ramped forcing and experimental photoperiod data (use all chilling types) in Rstan
@AileneKane is doing all types of photo and forcing data (use all chilling types) in Rstan

@AileneKane Can you help collate CSV files into OSPREE_compare tab as they come in?

**Comment by AileneKane** [comment]
@lizzieinvancouver  Yes, I will help collate CSV files into OSPREE_compare tab as they come in?

**Comment by AileneKane** [comment]
@lizzieinvancouver I wanted to confirm that we should all use centered data? (use.zscore=TRUE)?

**Comment by dbuona** [comment]
I was using z.score=TRUE.

**Comment by cchambe12** [comment]
Sorry everyone, the no crops code is now uploaded! Please pull from git to get the new code. I won't have models until the end of the day, my potting took a lot longer than anticipated.

**Comment by dbuona** [comment]
@cchambe12 
Hi Cat and all, I am using the data bb.stan.nocrops from bbstanleadin.R that I think you just made.
There are 35 unique species in complex (numbered 1-37, and skipping  complex 5 and 19).
When I run models, they are estimating values for complexes 5 and 19, which as you might guess, are very close to the global means.

Basically from a modeling perspective, is this okay?

**Comment by cchambe12** [comment]
@dbuona That seems really weird to me. I'll look into it now.

**Comment by cchambe12** [comment]
@dbuona I removed the crops earlier in the code and that seems to fix the issue! Nice catch and sorry about that. Should be all set now

**Comment by AileneKane** [comment]
Sorry- I will not be able to post the rest of mine until tomorrow! My computer died this morning and it slowed me down considerably.

**Comment by AileneKane** [comment]
What about using a truncated normal distribution? i think we've talked about this before.
https://discourse.mc-stan.org/t/declaring-constrained-parameters/1539

**Comment by lizzieinvancouver** [comment]
This was a useful exercise, we've moved on .. see issue #232 and see wiki: comparing models.
