### ISSUE TITLE
pull and clean trait data, as possible

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#233]
Trying ... 
- BIEN 
- TRY
- [ARGON](https://pearselab.github.io/argon/)

**Comment by lizzieinvancouver** [comment]
TRY data are 90K lines of data. They do not seem to want to authorship, but we have to cite them and acknowledge that we used that.

**Comment by lizzieinvancouver** [comment]
**Goal to have obtained trait data for updated species list and have all new and previous data clean by retreat.**

**Comment by DeirdreLoughnan** [comment]
We have pulled trait data from TRY and BIEN for 101 species and 11 traits!
