### ISSUE TITLE
check for new papers

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#234]
search Google Scholar and ISI ... but first must find our old search criteria! @cchambe12 @dbuona @AileneKane .... I know I have seen it but can now not find it ...

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan @DarwinSodhi We just pulled some more notes on our methods, see ospree/notes/litreviewnotes/ and please add a new TXT (use TXT, not doc!) with your updates.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan @DarwinSodhi Update the files so no merge conflicts, update the file (lit.rev.notes.Dec2018) on where to put unprocessed papers and put them there (google drive) and then but alert @lizzieinvancouver that the papers are ready.

**Comment by DeirdreLoughnan** [comment]
@DarwinSodhi I updated the file and created a folder in the google drive to upload the new papers to (OSPREE papers-->Papers_2016_2018). Could you upload your papers as well?

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver Should check the papers in the folder and write an update!

**Comment by lizzieinvancouver** [comment]
**Of the 13 papers noted, these two would not be included in OSPREE:**

- Zohner et al. 2016 is already included (yay!).
- Sønsteby et al. 2016 is on strawberries, so should technically not be included, but maybe we should since we accidentally included so many strawberry studies?

**Of the rest:**

These focus on crops:
- Anzanello & Biasi 2016 (peach and plum cultivars I believe)
- Anzanello et al. 2018 (Vitis)
- Ramos et al. 2017 (olives)

Studies using ambient temperature and/or photoperiod:
- Fu et al. 2018 (GCB) Is similar to a Fu paper in OSPREE in that it uses (I believe) chambers to raise ambient temperature +1 to +5 C ... which we do not use in the budburst analysis. 
- Man et al. 2017 is a chilling experiment (<0) using ambient photo and forcing so would not make the cut for our budburst analysis; species are: _Populus balsamifera, Populus tremuloides, Betula papyrifera, Picea mariana, Picea glauca, Pinus banksiana, Pinus contorta)._
- Richardson et al. 2018 (SPRUCE experiment): similar to Fu, also need to check if they actually measure budburst or just something else via cameras. 
- Vitra et al. 2017: ambient photoperiod (_Carpinus, Prunus, Fagus, Quercus_) 
-Prevey & Harrington 2018: _Alnus rubra_ study of 'pre-treaments' of 4 C, 9C and ambient conditions, then all put in ambient greenhouse conditions.

Leaving these that may be useful for budburst work:
- Flynn & Wolkovich 2018 is obviously brilliant work, that should be included. 
- Malyshev et al. 2018 does ramped forcing and Weinberger style with constant photoperiods on the following species: _Abies alba, Picea abies, Quercus robur, Acer pseudoplatanus, Sorbus torminalis, Tilia cordata, Larix decidua_
- Nanninga et al. 2017: Interesting chilling study with constant photoperiod and semi-steady temps (21 °C day/16°C night), species were from Cedar Creek: _Acer rubrum, Larix laricina, Populus tremuloides, Quercus ellipsoidalis, Betula papyrifera, Rhamnus cathartica._

**Comment by lizzieinvancouver** [comment]
I think we should get started on this soon so we can move ahead on traits, ranges and phylogeny this summer (aim to have this ready by end of June or mid-July meeting?). Steps would be:

1. Someone who entered OSPREE data originally would create an empty version of this: https://github.com/lizzieinvancouver/ospree/blob/master/data/ospree.xlsx
2. Divvy up new papers
3. Enter data
4. Clean it!

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi @DeirdreLoughnan will check again!

**Comment by DeirdreLoughnan** [comment]
I checked for new papers in WOS and created a new notes document with the number of search results for each combination of search terms. I found one additional paper and added it to the OSPREE papers folder.

**Comment by lizzieinvancouver** [comment]
See issue #268
