### ISSUE TITLE
non-numeric chilltemps in ospree_clean

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#24]
check chilltemp column- there are many non-numeric values there that may be useful. they are currently excluded from the experimental chilling calculations in Field_Exp_Chilling_Calc.R

**Comment by AileneKane** [comment]
I added a file that summarizes the studies/papers and values that need to be checked:

**Comment by danfbflynn** [comment]
All 'ambient' in the chilltemps and chillphotoperiod are deleted to be left blank; chilling is now calculated manually for these studies.

chilldays had dates for a number of studies; those have now been moved to fieldsampledate.

Others are harder to deal with, haven't fixed them all yet

**Comment by AileneKane** [comment]
There are definitely still non-numeric values in the "chilltemps" column so we need to write some cleaning code to deal with this I think.

**Comment by AileneKane** [comment]
The file that needs to be updated for this is cleaning_chilltemp.R in the chilling folder.

**Comment by cchambe12** [comment]
okie11: can we change to -0.5? seedlings were chilled for one month at -3, and one month at 2, took the average

li05: can we change to 3.25? seedlings were chilled for 3 weeks at 6, and 3 weeks at 0.5, took the average

jones12: "Cuttings were exposed to either a 6-week or a 12-week chilling period, with each period split into three equal parts at one of the treatment temperatures (-4, 0, 4 or 8C). - took average 

granhus09: no idea what to do with this one...
"Chilling treatment at 0.7 \xb1 0.7 C interrupted by mild spells of 14 days duration at a constant temperature of 8 or 12 C"

falusi90: either put in heated greenhouse at a minimum temp of 16degC or left outside for ambient chilling - not sure what to do here

**Comment by cchambe12** [comment]
up to Ailene and Lizzie to fix

**Comment by AileneKane** [comment]
What is the deal with this study- Cat, do you know? 
d[which(d$chilltemp=="Chilling treatment at 0.7 \xb1 0.7 C interrupted by mild spells of 14 days duration at a constant temperature of 8 or 12 C"),]#granhus09

**Comment by lizzieinvancouver** [comment]
@AileneKane I think I entered this study!

**Comment by AileneKane** [comment]
@lizzieinvancouver ok- let's look at it (and other questions...) while you're here for our "microworkshop"!

**Comment by AileneKane** [comment]
There are two papers that have chilldays that need to be looked at in the paper: 
skuterud94: "40,55,60 (mean across these presented)"
