### ISSUE TITLE
work on marginal effects for main models

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#242]
See also #241 ...
@AileneKane Will work on climate data to estimate how much 1-5 degree warming over spring (Mar-May) and winter (Oct-Feb) months alters mean spring temp (force) and chill portions.
@lizzieinvancouver Will redo her code to work off the posterior.

**Comment by AileneKane** [comment]
I did find this article that forecasted future chilling (and GDH). I haven't found their code or forecasts available online yet, but I have contacted the authors. [https://link.springer.com/article/10.1007/s10584-018-2337-5](url)

**Comment by lizzieinvancouver** [comment]
Okay, we can also keep moving by using:

1. past climate data (i.e., pull 5 years from one site for a start, or just one year) and add 1 degree of warming to Oct-Feb or Mar-May or Oct-May .... 
2. monthly mean projections (Nacho has I suspect)

**Comment by AileneKane** [comment]
Here is my first attempt at a forecasting plot for one site in germany [https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/tempforecast.pdf](url)
Next: try multiple sites, using coefficients for Betula and Fagus. 
@cchambe12 could you point me to BBDOY estimates for  Betula and Faga from PEP data?

**Comment by AileneKane** [comment]
Updates for these model are: [here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/tempforecast_bothspp_PEPBB_wdl.pdf),  [here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/tempforecast_betpen_minmaxlat_PEPBB.pdf), and [here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/tempforecast_fagsyl_minmaxlat_PEPBB.pdf)

**Comment by AileneKane** [comment]
[Here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/bbmod_3dplot_4panels.pdf) is a 4-panel figure showing marginal effects over the range of experimental data for chill portions and utah units, 2d and 3d versions. Looking forward to getting your feedback!

**Comment by AileneKane** [comment]
I think we can close this!
