### ISSUE TITLE
update chill x force figure: Utah and Chill portions

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#243]

**Comment by lizzieinvancouver** [comment]
Also, could check intpool only model for fc

**Comment by lizzieinvancouver** [comment]
Simple linear regression across all data ... force and utah are correlated (slope of -0.07; rsq 0.017) and force and chill are twice as correlated (slope of -1.1; rsq 0.035)

```
> summary(lm(chill.ports~force, data=bb.stan))

Call:
lm(formula = chill.ports ~ force, data = bb.stan)

Residuals:
    Min      1Q  Median      3Q     Max 
-65.875 -24.590   4.887  28.784 118.138 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  82.3037     2.2486  36.602  < 2e-16 ***
force        -1.0772     0.1431  -7.525 8.97e-14 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 33.55 on 1522 degrees of freedom
Multiple R-squared:  0.03587,	Adjusted R-squared:  0.03524 
F-statistic: 56.63 on 1 and 1522 DF,  p-value: 8.974e-14

> summary(lm(chill~force, data=bb.stan))

Call:
lm(formula = chill ~ force, data = bb.stan)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.8442 -1.9198 -0.1761  1.9677 15.4140 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  6.04142    0.21954   27.52  < 2e-16 ***
force       -0.07184    0.01398   -5.14  3.1e-07 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.275 on 1522 degrees of freedom
Multiple R-squared:  0.01706,	Adjusted R-squared:  0.01642 
F-statistic: 26.42 on 1 and 1522 DF,  p-value: 3.1e-07

```

**Comment by lizzieinvancouver** [comment]
see also: quick_forcechill_portions.pdf and quick_forcechill_utah.pdf
and
cues.pdf versus chillports.cues.pdf ... compare Pseudotsuga plots (more correlated with chill ports) and Sorbus (more correlated with Utah)

**Comment by AileneKane** [comment]
Relatedly, I hate to reopen an issue, but I think we had decided to use the Chill Portions model in the main text, with utah in the supp but I'm wondering if we should switch these around. My reasoning is that, atleast for the nonz model, the chill portions model has 2 species estimates that are positive (this is weird, and diverges from the findings of the original papers from which we took the paper). 
the [utah model ](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/muplotmodelspcompexprampfputah_nonz.pdf)does not have these weird positive effects of chilling

**Comment by lizzieinvancouver** [comment]
We focus on Utah, we mention Dynamic model and include in tables.
