### ISSUE TITLE
get cold tolerance trait data?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#244]
@MoralesCastilla Will get list from his database @cchambe12 will get a list from Sakai, Larcher & Lenz

**Comment by cchambe12** [comment]
There are a LOT of species listed in Sakai and Larcher. Mostly they are from Japan so I listed any species that may be related to our OSPREE list. LTi = incipient frost damage; LT0 = no damage, damage limit; LT50 = 50% lethality.

Genus | Species | Tmin | min_metric
-- | -- | -- | --
Abies | balsamea | -70 | LT0
Acer | crataegifolium | -25 | LT0 for xylem
Alnus | firma | -25 | LT0 for xylem
Betula | ermani | -70 | LT0 for xylem
Carpinus | tschonoskii | -25 | LT0 for xylem
Cornus | controversa | -40 | LT0 for xylem
Fagus | crenata | -25 | LT0
Fraxinus | mandshurica | -40 | LT0 for xylem
Liquidambar | styraciflua | -25 | LT0
Liriodenron | tulipifera | -25 | LT0
Nyssa | sylvatica | -25 | LT0
Picea | glauca | -70 | LT0
Populus | maximowiczii | -70 | LT0 for xylem
Prunus | spinulosa | -8 | LT0
Psuedotsuga | menziesii | -45 | LT0
Quercus | glauca | -18 | LT0 for xylem
Quercus | ilex | -15 | LT50
Quercus | robur | -27 | LTi for buds
Quercus | rubra | -45 | LTi for xylem
Quercus | macrocarpa | -46 | LTi for xylem
Quercus | pubescens | -33 | LTi for xylem
Salix | sachalinensis | -70 | LT0 for xylem
Sorbus | sargenti | -35 | LT0 for xylem
Tilia | japonica | -35 | LT0 for xylem
Vaccinium | myrtillus | -35 | LT0

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi agreed to transcribe these data in to a CSV file and make a plain text readme file to explain where the data come from (and reference this issue).

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver Data + Read me put into trait folder under Ospree_analysis_traits

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi Nice work! Thanks.
