### ISSUE TITLE
How best to plot/visualize variation in climate data across space?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#246]
For everyone on the budburst paper: We see variation in how winter versus spring waring affect budburst depends a lot on the local climate data. So how can we deal with this?

1. Change the plots to show more sites?
2. Visualize variation across sites more than across warming amount?
3. Other ideas?

**Comment by AileneKane** [comment]
[Here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/forecasting/forecastbetpenPEPBB_mapwgradient.pdf) is a heat map showing change in budburst across a subset of sites (still waiting for chilling estimates to finish for full range of betpen in PEP)

**Comment by lizzieinvancouver** [comment]
Done! See issue #262
