### ISSUE TITLE
Request usage of PEP725 data?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#247]
I think we may need to let them know if we're using it for something outside of the originally requested project? I am not sure, but we should check!

**Comment by cchambe12** [comment]
Looks like we do! I'll reregister now and let them know what we're up to.[ Here](http://www.pep725.eu/data.php) is a link to the PEP725 data use policy here so we have it. Should I put it in the ospree repo at all? 

`PEP725 Data Attribution Policy
6) Acknowledgement: The following acknowledgement must be included in either the main text or Acknowledgments section of all publications using PEP725 data. Acknowledgment: “Data were provided by the members of the PEP725 project”
7) Bibliographic information should be provided to the PEP725 project management (pep725@zamg.ac.at) for all manuscripts using PEP725 data immediately after their publication
8) Citation: All PEP725 data sets must be cited following the example below: Templ, B., Koch, E., Bolmgren, K., Ungersböck, M., Paul, A., Scheifinger, H., et al. (2018). Pan European Phenological database (PEP725): a single point of access for European data. Int. J. Biometeorology. doi: 10.1007/s00484-018-1512-8
Data set accessed YYYY-MM-DD at http://www.pep725.eu

PEP725 Database Access Requirements
Access to all Data Sets available from the PEP725 database is subject to compliance with this policy document to enable Data Set Owners and the PEP725 project management team to track usage, evaluate its impact in the community, and confirm Database Users'
agreement with the PEP725 Data Use Policy. The following information is required directly or by proxy prior to the release of any Data Set:
• Registration
o Name
o Affiliation
o Email Address
o Full Contact Information
• Acceptance of the Terms and Conditions of the PEP725 Data Use Policy
• A Statement of Intended Use that is compliant with the above agreements. Such statements may be submitted via the data access portal interface.
The information on Database Users will be available to the PEP725 project management and the Dataset Owners. PEP725 project management and Dataset Owners will not sell, trade, or pass on this information to any third parties.`

**Comment by cchambe12** [comment]
I used the temporalecology@gmail.com address for our registration for anything OSPREE! Not sure where to keep a record on the password and login information... to discuss tomorrow!

**Comment by cchambe12** [comment]
@cchambe12 email PEP725!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Will add a README regarding where the original PEP data live in the ospree/data file (maybe start a pep725 folder?) and also include the info regarding PEP's policy on using their data and a copy of the email she sent them (time and date-stamped) ... then close this issue!

**Comment by cchambe12** [comment]
I added a new folder to the ospree/data folder and added a README

**Comment by lizzieinvancouver** [comment]
@cchambe12 Thanks! Can you point me to the README? I can't seem to find it.

**Comment by cchambe12** [comment]
@lizzieinvancouver well that's because I saved it in a totally random repo on accident! haha I've now moved it to ospree/data/pep725
