### ISSUE TITLE
Lit review of chilling units

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#251]
@lizzieinvancouver @AileneKane @dbuona @cchambe12 @MoralesCastilla 
I have assigned each of you to read a couple of papers on chilling units. Please read your papers and summarize them in the chillunits.litreview.csv  [spreadsheet](https://github.com/lizzieinvancouver/ospree/blob/master/notes/chillunits.litreview.csv) 

You can find the full reference for each paper in the budburst outline [here](https://github.com/lizzieinvancouver/ospree/blob/master/docs/budburst/budburstoutline.pdf). If you have trouble finding the paper or need help/have questions, let me know!

**Comment by lizzieinvancouver** [comment]
@AileneKane @MoralesCastilla @cchambe12 @dbuona 
If you have extra notes you want to make, you can also add them [to our wiki here](https://github.com/lizzieinvancouver/ospree/wiki/What's-the-story-with-all-this-chilling%3F)

**Comment by lizzieinvancouver** [comment]
@AileneKane Can you add a README or such? I don't recall what all the columns mean:

strength_utah
weak_utah
thresh_utah
strength_chillport
weak_chillport
thresh_chill
species
test_utah_cp
other_notes

**Comment by AileneKane** [comment]
Great idea, @lizzieinvancouver ! Sorry about the confusion! I have added a readme. Also, here:
chillunits.litreview.csv READ ME
<><><><><><><><><><><><><><>


The goal of this lit review is to summarize differences in how chilling is measured/estimated/quantified and the implications of these differences. 

The spreadsheet contains the following columns:
strength_utah= strengths/benefits of using Utah units to quantify chilling, as outlined in the study
weak_utah= weaknesses/challenges of using Utah units to quantify chilling, as outlined in the study

thresh_utah=threshold temperature(s) to count as chilling, using Utah units (e.g. <0 degrees C).

strength_chillport= strengths/benefits of using Children Portions to quantify chilling, as outlined in the study
weak_chillport= weaknesses/challenges of using Children Portions to quantify chilling, as outlined in the study

thresh_chill=threshold temperature(s) to count as chilling, using Children Portions (e.g. <0 degrees C).
strength_chillport

species= names of species included in the study

test_utah_cp= yes/no; was the difference between utah and chill portions actually tested?

other_notes= any other relevant notes.

**Comment by AileneKane** [comment]
@lizzieinvancouver @AileneKane @dbuona @cchambe12 @MoralesCastilla please add your chilling units paper to the google driver [here](https://drive.google.com/drive/u/2/folders/1KE3IUhW8RH1vY9XxeOyFq9-5UzIAqHqv)

**Comment by AileneKane** [comment]
I have added my papers [here](https://drive.google.com/drive/u/2/folders/1KE3IUhW8RH1vY9XxeOyFq9-5UzIAqHqv)

**Comment by AileneKane** [comment]
@lizzieinvancouver "Also, can you update your README to explain what children units are?" by this do you mean that i should define chill portions and utah units in the readme file?

**Comment by lizzieinvancouver** [comment]
@AileneKane Ah, I think I just mean a typo ... **Children** portions is chill portions? Maybe then just correct spelling and add chill portions (dyanmic model) at the first mention of chill portions?

**Comment by AileneKane** [comment]
@lizzieinvancouver got it! this is done!

**Comment by AileneKane** [comment]
@AileneKane @MoralesCastilla @cchambe12 @dbuona
Please put your chilling paper summaries here if you haven't already!

**Comment by dbuona** [comment]
Not sure if people are already aware of this, but I just stumbled across this paper[Problems in standardizing methods for evaluating the chilling requirements for the breaking of dormancy in buds of woody plants](https://journals.ashs.org/hortsci/view/journals/hortsci/38/3/article-p347.pdf) which is a nice short summary of how the chilling models were developed and a bit of a comparison between them

**Comment by lizzieinvancouver** [comment]
@dbuona Yes! I agree this seemed super nice. This is the paper I said everyone doing cutting experiments should read and I think it's the best one I have read for us to cite as it states you should not assume the models measure chilling so much as measure a hypothesis or something that stands in okay for chilling, at least when parameterized to a specific plant species.

**Comment by AileneKane** [comment]
@lizzieinvancouver shall i close this now?

**Comment by lizzieinvancouver** [comment]
@AileneKane I wanted to work up some notes on this before we close ... can you point me to any notes and wiki pages on this and I will do it so we can close this? Thanks!

**Comment by AileneKane** [comment]
Sure! Here are links to the relevant files:

1. [wiki page: ](https://github.com/lizzieinvancouver/ospree/wiki/What's-the-story-with-all-this-chilling%3F)
2. [chillunits.litreview.csv](https://github.com/lizzieinvancouver/ospree/blob/master/notes/chillunits.litreview.csv)
3. Papers we looked should be [here ](https://drive.google.com/drive/folders/1KE3IUhW8RH1vY9XxeOyFq9-5UzIAqHqv)
