### ISSUE TITLE
Lit review of cues and their effects

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#252]
@lizzieinvancouver @AileneKane @dbuona @cchambe12 @MoralesCastilla
I have assigned each of you to read a couple of papers on about forcing, chilling, and photoperiod cues. Please read your papers and summarize them in the cue.litreview.csv [spreadsheet](https://github.com/lizzieinvancouver/ospree/blob/master/notes/cue.litreview.csv)

You can find the full reference for each paper in the budburst outline [here.](https://github.com/lizzieinvancouver/ospree/blob/master/docs/budburst/budburstoutline.pdf) 

If you have trouble finding your papers or need help/have questions, let me know! Many are OSPREE papers. I put two of the non-ospree papers on google drive: https://drive.google.com/drive/u/0/folders/1N11KpnwUb3DME5bNmZ3cehCrY5WZwBzw

**Comment by AileneKane** [comment]
@lizzieinvancouver @AileneKane @dbuona @cchambe12 @MoralesCastilla I should have been a bit more clear about directions for this. Please put the direction of each effect (i.e. negative, positive, ns, or NA if not tested) in the column of each cue. You can also add caveats/interactions in each cue column. the "most.impt" column should list what the authors interpret to be the most important cue.

**Comment by AileneKane** [comment]
@lizzieinvancouver @AileneKane @dbuona @cchambe12 @MoralesCastilla 
Please add whether or not the study used the weinberger method (add yes/no to the "wein" column) and also separate our different experiments included in the paper- these should be in different rows and the "study" column should correspond to the experiment in ospree (e.g. "exp1") (@dubuona I split out your caffarra experiments into different rows but please check!)

**Comment by lizzieinvancouver** [comment]
@AileneKane I am lost on what Caffarra paper you want me to review Caffarra2011(IJB) *is an OSPREE paper.* It's cafferra11a ... @dbuona What paper did you review?

**Comment by lizzieinvancouver** [comment]
@AileneKane @dbuona ... Okay, I think:
Ailene wanted Dan to do this one `Modelling the timing of Betula pubescens budburst. II. Integrating complex effects of photoperiod into process-based models', which is NOT in OSPREE as best I can tell, but she labelled it cafferra11a, so instead Dan did this one: The ecological significance of phenology in four different tree species: effects of light and temperature on bud burst (which is cafferra11a). 

And Nacho did this one: Modelling the timing of Betula pubescens budburst. I. Temperature and photoperiod: a conceptual model, which is caffarra11b. 

So I will do this one: 
Modelling the timing of Betula pubescens budburst. II. Integrating complex effects of photoperiod into process-based models ... and @AileneKane can you double check and sort this out once I push?

Thanks everyone!

**Comment by lizzieinvancouver** [comment]
@AileneKane Me again (sorry)!

Okay, so this paper is actually comparing different models, it is not introducing new experimental data ... so I am not sure it fits in your cue review. The data it uses are in the paper Nacho entered and it also uses some PEP data to help parameterize the models.

That said I think it would be a good paper for your photoperiod review. First it shows: "Firstly, photoperiod, in interaction with temperature, affects the course of dormancy induction. Secondly, photoperiod modifies the response to temperature during the phase of forcing."

And, more importantly, it does what we suggest in the conceptual figure: 

> The experiments by Caffarra et al. (2011) showed that the critical photoperiod for dormancy induction (DLcrit) in the IPG birch clone was >12 h and <14 h. We thus fixed DLcrit (indicating the photoperiod above which the rate of dormancy induction is low or zero) to 13 h. Parameter dF could be measured directly from experimental results and set to –0.174 (Caffarra et al. 2011). The range of values that could be adopted by the parameters Dcrit (critical state of dormancy induc- tion), Ccrit (critical state of chilling) and cC (upper threshold of chilling temperatures triggering a chilling rate of ≥0.5) were restricted using the information available in the literature. Dcrit was bounded between 30 and 60, as dormancy induction in birch was reported to be triggered after 30 – 60 short days (ShDs) (Caffarra et al. 2011). Ccrit was bound between 30 and 80, as birch dormancy was reported to be at least par- tially released after around 50 chilling days in experi- mental conditions (Caffarra et al. 2011) and before the beginning of January in field conditions (Skre et al. 2008, Murray et al. 1989). The parameter cC was bound between 10 and 15, after Caffarra et al. (2011), and to the experimental studies on the subject, sug- gesting an upper threshold for active chilling tempera- ture between 10°C (Sarvas 1974) and 12°C (Myking & Heide 1995). As parameters DLcrit and dF were fixed before parameterisation, it was necessary to fit 9 para- meters rather than 11.

**Comment by AileneKane** [comment]
@lizzieinvancouver Thank you for pushing ahead and doing it! Will definitely incorporate into photoperiod! I will fix the names in the spreadsheet. thank you!

**Comment by lizzieinvancouver** [comment]
@AileneKane I suggest you check answers you've received against notes [here](https://github.com/lizzieinvancouver/ospree/issues/235) and against countintxns code ... for example, only these papers seem to have f x p interactions are:

```
> osp.fpintxn[order(osp.fpintxn$datasetID),]
      datasetID study intxn
5      basler14  exp1     2
19      heide05  exp1     2
64      heide05  exp2     2
20      heide08  exp1     2
86      heide08  exp3     2
21      heide11  exp1     2
66      heide11  exp2     2
87      heide11  exp3     2
23      heide93  exp1     2
69      heide93  exp2     2
70     heide93a  exp2     2
71       okie11  exp2     2
74  pettersen71  exp2     4
42 Sanz-Perez09  exp1     2
```

So I think the studies that give effects for photo and forcing in one row don't necessarily mean that study manipulated both at once.

**Comment by AileneKane** [comment]
@AileneKane will write a summary of these plus the nonospree papers we reviewed on the [wiki.](https://github.com/lizzieinvancouver/ospree/wiki/Interacting-Cues)

**Comment by AileneKane** [comment]
@lizzieinvancouver  i have added a short summary, so i think i can close this? please let me know if i should add more detail. https://github.com/lizzieinvancouver/ospree/wiki/Interacting-Cues
