### ISSUE TITLE
finish pep sims

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#255]
I need to:
(1) check var versus SD in both files (the sims and the pep climate)
(2) add SE to % estimates 
(3) Make sure diffs are taken the same way across the files (the sims and the pep climate)

**Comment by lizzieinvancouver** [comment]
@cchambe12 One more request! Can you again read the PEP sims section in the supp (Potential statistical artifacts in declines of temperature sensitivity in observational long-term data)? Especially the new last paragraph ... and make sure I am accurately describing everything. 

@AileneKane Can you add the clark ref to the supp where requested (near gusewell ref).

... then we can close this I think!

**Comment by AileneKane** [comment]
@cchambe12 @AileneKane Great! I will work on this and other edits today and pass off to Cat tomorrow!

**Comment by cchambe12** [comment]
@lizzieinvancouver I think you did a great job explaining everything! I have added a [lit review](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/pep_sims/pepsimslitreview.txt) and I agree with everything you have said.
