### ISSUE TITLE
help me with the treatment heat maps!

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#256]
@cchambe12 @MoralesCastilla @dbuona @AileneKane 

I need help finishing my heatmaps. Specifically I need help to:
(1) Adjust the font size and spacing on axes, plot titles etc.
(2) Figure out how to change the label on the color bars.

The code is [here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/studydesignplotsbb.R) and the problematic figure is [here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/studydesign_heat3panel.pdf). Please shout if you can help so we don't duplicate effort.

**Comment by cchambe12** [comment]
I'm happy to take a stab at this! I'll work on it tomorrow and pass along my final touches to see if anyone wants to take over after that.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Awesome! Thank you!

**Comment by cchambe12** [comment]
@lizzieinvancouver I worked on the heatmaps. I wasn't sure how you wanted to label the legends and if I adjusted as you wanted but I would be more than happy to keep working on it if you have other tweaks in mind.

**Comment by lizzieinvancouver** [comment]
@cchambe12 
(1) Make 1 row, 3 columns.
(2) Make axes test much bigger.
@lizzieinvancouver 
Check what we did with NAs!

**Comment by cchambe12** [comment]
@lizzieinvancouver I fixed #1 & #2, let me know if you want any further tweaks!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Awesome! But, I am missing it somehow ... can you point me to the new figure?

**Comment by cchambe12** [comment]
@lizzieinvancouver I should've added a link! [Here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/studydesign_heat3panel.pdf) ya go!

**Comment by lizzieinvancouver** [comment]
Just updated this to allspp and main model figures and wrote in new paths to supp ....
