### ISSUE TITLE
Add model equation to budburst supplemental

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#258]

**Comment by lizzieinvancouver** [comment]
I did this, could someone volunteer to check for the current recommended ways to reference Stan and update the bib file for that and R? Also, @AileneKane I left in some XX around the equations we should fill in.

**Comment by AileneKane** [comment]
I need to fix alignment of lat and weinberger model equations  still

**Comment by AileneKane** [comment]
Done- thank you @lizzieinvancouver !
