### ISSUE TITLE
Email Title ideas to Ailene

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#259]

**Comment by AileneKane** [comment]
Below is a list of title ideas received so far (requirements are  96 chars including spaces (Science, 90 for Nature):

1. Cold winters cue temperate trees, but more so in growth-chamber experiments (char: 75)
 
2. Cold winters cue temperate trees, but more so in experiments (60)
 
3. Cold winters cue temperate trees more than warmth and daylength, in experiments (79)
 
4. Chilling cue temperate trees more than forcing and photoperiod, but only in experiments (87)

5. Chilling dominates spring phenology in experiments but does not explain observed declining sensitivities with warming in Europe (127)

6. Chilling dominates spring phenological responses across experiments (67)

7. Chilling dominates spring phenological responses (48)

8. Chilling dominates spring phenological responses in experiments and complicates forecasts in natural systems (108)

9. Chilling dominates phenological responses to warming in experiments but not natural systems (90)

10. Chilling dominates in experimental phenology research but not natural systems  (78)

11. Strong chilling, forcing and daylength cues are prevalent across woody species (78)

12. Meta-analysis of phenological experiments shows strong chilling, forcing and daylength cues (across woody species) (112/92)

13. Chilling, forcing and daylength underlie (spring) phenological responses to warming (across woody species) (103/78)

14. Chilling drives spring phenology across experiments and complicates forecasting (79)

15. Prevalence of chilling, forcing, and daylength cues in woody plant phenology complicates  forecasts (with warming) (112/100)

**Comment by lizzieinvancouver** [comment]
@AileneKane We should be careful to not be too close to other titles (e.g., Laude 'Chilling outweighs photoperiod in preventing precocious spring development') so may want to google titles before we pick top ones.

**Comment by AileneKane** [comment]
**Top contenders**
Chilling dominates phenological responses to warming in experiments but not natural systems (90)
Chilling dominates spring phenological responses (48)
Strong chilling, forcing and daylength cues are prevalent across woody species (78)
Chilling drives spring phenology across experiments and complicates forecasting (79)
Winter temperatures dominate spring phenological responses (49)

**Comment by lizzieinvancouver** [comment]
Counts of some phrases in titles of Nature/Science papers (ISI):

winter temperature* -- 6 but ONLY once were words published together (e.g., 'Mechanisms of Age-Dependent Response to Winter Temperature in Perennial Flowering of Arabis alpina')

chilling -- 16 but only TWO apply to plants I think ('GENETICALLY ENGINEERED ALTERATION IN THE CHILLING SENSITIVITY OF PLANTS' or 'PROTOPLASMIC STREAMING IN PLANTS SENSITIVE AND INSENSITIVE TO CHILLING TEMPERATURES')

forcing is published a lot and is mainly about climate forcing ... so another good reason not to use it.

**Comment by AileneKane** [comment]
**Final contestants:**
Chilling dominates spring phenological responses (48)
Chilling drives spring phenology across experiments and complicates forecasting (79)
Winter temperatures dominate spring phenological responses (49)

**Comment by AileneKane** [comment]
Note: we realized that its unclear what the responses are to. to fix this, these would be:
Chilling dominates spring phenological responses to warming (50)
Chilling drives spring phenology across experiments and complicates forecasting (79)
Winter temperatures dominate spring phenological responses to warming (51)

**Comment by lizzieinvancouver** [comment]
If we use `responses' we may need `to warming' or some other explanation of responses to what

**Comment by lizzieinvancouver** [comment]
@AileneKane Jonathan likes `Winter temperatures dominate spring phenological responses to warming' ... he says 'a lot more.'

**Comment by AileneKane** [comment]
@lizzieinvancouver thanks for getting his perspective! We can all mull it over and discuss again prior to submission

**Comment by lizzieinvancouver** [comment]
@AileneKane Another option ... 'Chilling temperatures dominate spring phenological responses to warming' though doesn't have the cool winter-spring contrast.

**Comment by AileneKane** [comment]
ok, @lizzieinvancouver @cchambe12 @dbuona @jsamaha @tsavas @dflynn-volpe 
A head to head vote: Please send me am email with your top choice of these two titles:
1. Winter temperatures dominate spring phenological responses to warming
2. Chilling dominates spring phenological responses to warming

**Comment by AileneKane** [comment]
@lizzieinvancouver @cchambe12 @dbuona @jsamaha @tsavas @dflynn-volpe
FYI: the winnter is 1. Winter temperatures dominate spring phenological responses to warming
