### ISSUE TITLE
Make map of OSPREE study locations

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#261]

**Comment by MoralesCastilla** [comment]
I have made a first attempt at it (see 9382b4da20b333484b576bd8da437f8431c9df02)... not super happy about it yet, so any suggestions are welcome (make the points smaller? use other color scheme? add species symbols and colors according to other figures in the ms.?)

**Comment by AileneKane** [comment]
@MoralesCastilla Awesome! Thank you! Looks great! I think it would be good to make the points slightly smaller. Also, if we want people to be able to patch up the point with the name, then i think we will need to add more contrasting colors or different shapes. perhaps we can make them shapes based on their chilling treatment method (weinberger vs experimental chilling)? or different shapes based on whether they experimentally manipulated forcing, chilling, photoperiod, or different combinations? (I'm trying to think of other messages that we want to get across with this paper that we could use this map as a chance to showcase).

**Comment by MoralesCastilla** [comment]
@AileneKane 
new versions ready see (6573fa70ff53a6dc69079f96d8e329a233989a16), haven't applied different symbols yet, do you think we need that?

**Comment by AileneKane** [comment]
@MoralesCastilla Awesome! Thank you so much! It looks great! I think we will want to use different symbols, but we should discuss how to decide on their symbols. I will think on it as I work on the revised draft and would like to talk it over with @lizzieinvancouver, @dbuona, and @cchambe12 too.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla @AileneKane I think they look great! One thing I think we should do before we switch symbols (which we may need to do for clarity) is subset to the largest dataset we'll actually use in the paper. @MoralesCastilla Can you make sure you subset down to flags [we use here](https://github.com/lizzieinvancouver/ospree/blob/master/notes/snippet_for_ns.R)?

**Comment by AileneKane** [comment]
@MoralesCastilla Thank you again for your work on this map- it looks great! I have a few requests:

1. Please make sure that it is only showing the sites included in the bb_analysis. We can include the maximum number of studies of any budburst model, which is the all species model with the following flags:
## set up the flags
use.chillports = FALSE
use.zscore = FALSE
use.allspp =TRUE # for the main model this is false
use.multcuespp = FALSE
use.cropspp = TRUE
# Default is species complex use  alltypes of designs
use.expramptypes.fp = FALSE
use.exptypes.fp = FALSE
use.expchillonly = FALSE

2. Could you add a black circle around the sites included in the Main budburst model, i.e. the one with the following flags:

## set up the flags
use.chillports = FALSE
use.zscore = FALSE
use.allspp =FALSE# for the main model this is false
use.multcuespp = FALSE
use.cropspp = FALSE
# Default is species complex use  alltypes of designs
use.expramptypes.fp = TRUE
use.exptypes.fp = FALSE
use.expchillonly = FALSE

3. It would also be nice to vary the shape of the symbols by whether chilling was manipulated or not. This will be a bit of a pain but I think would be really nice to have. I will post post a follow-up comment directing you to the code that will best do this.

**Comment by AileneKane** [comment]
@MoralesCastilla To do Item 3 you can use the studytype_withBB.csv table. Studies that have manipulated chilling will have >1 in the "chill" OR "chilltime" columns OR have 1 in the "wein" column. Let me know if you have questions!

**Comment by lizzieinvancouver** [comment]
@AileneKane @MoralesCastilla  As of yesterday afternoon you can just use analyses/output/bbstan_allsppmodel_utahzscore_wcrops_allfp_allchill.csv for the all spp model or the simply:
```
use.flags.for.mainmodel <- FALSE
use.flags.for.allsppmodel <- TRUE
use.yourown.flagdesign <- FALSE
```
in models_stan.R

For the main text model:
bbstan_mainmodel_utah_allsppwcrops_allfp_allchill.csv
```
use.flags.for.mainmodel <- TRUE
use.flags.for.allsppmodel <- FALSE
use.yourown.flagdesign <- FALSE
```

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Okay! Check output/bbmapdata.csv -- it has the info you need for the maps (though you need to merge in the lat/long for each datasetID/study) ... please make a map with each location labeled by (just) datasetID. Use different symbol for yes/no for chill.manipulated and outline in black those studies where mainmodel==yes.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 
I just pushed a new version of the map to the `analyses\bb_analysis\figures` folder. I'm still not super happy about it (it should be a quite simple map to do, but I'm not quite there yet). Any suggestions about using different symbols, colors, sizes are welcome!

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Awesome! Few more tweaks
- change 'Study in main analysis' to 'Study in main model'
- change 'Chilling treatment' to 'Chilling manipulated'
- Use triangles instead of asterisks (with circles)
- Cut off (trim) some of Asia so rest of map can be bigger

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 
New tweaked version uploaded to the figures folder `ospree_locations5thin.png`. Still not perfect but looking better.

**Comment by AileneKane** [comment]
@MoralesCastilla I like it! One small thing- if it is not too difficult. Instead of putting circles around the sites that are in the main model and manipulate chilling, could you use a triangle outlined in black? (in other words, instead of having a triangle with a circle around it, could you have triangles outlined in black)? Thank you so much! Otherwise, it looks great!!!

**Comment by MoralesCastilla** [comment]
@AileneKane 
Great idea!! I think it looks better (less weird) now. See the new version in `analyses\bb_analysis\figures` and let me know if there are more changes you'd like.

**Comment by AileneKane** [comment]
@MoralesCastilla  I think it looks great! The new triangle version looks like the only sites that manipulated chilling are studies that are included in the main model- is this true? In your earlier map, it looked like some sites should be circles in a black outline too (i.e., they are included in the main model but do not manipulate chilling). As an example, I think spann04 (in Florida- I think that's the right study) should be a green filled in circle (because it does not manipulate chilling) and have a circle outline around it. Thus, the black outline (whether around circles or triangles) is what indicates whether or not the study is included in the main model. I hope this makes sense! I'm happy to set up a call to talk about it if that would help. Thank you so much!

**Comment by MoralesCastilla** [comment]
@AileneKane 
Sorry Ailene, this comment had slipped my mind. I have now used framed circles and triangles to distinguish among studies in/not main analysis, and studies manipulating chilling (or not). I hope it is clearer now. Let me know if you'd change some other aspect of it (the new version is in the figures folder).
