### ISSUE TITLE
Improve Ailene's start on a map of forecasted changes in budburst and chilling

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#262]

**Comment by AileneKane** [comment]
current code is here: https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/forecasting/forecast_heatmaps.R

**Comment by lizzieinvancouver** [comment]
@Morales Can you make it look like Figure 3 from our NCC wine paper from 2018 (where you show the elevation a little)?

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla  Can you make it look like Figure 3 from our NCC wine paper from 2018 (where you show the elevation a little)?

**Comment by MoralesCastilla** [comment]
@AileneKane 

Ailene, in line 31 of the script `forecast_heatmaps.R`:

spests <- read.csv("..//output/betpen_for3dplot/betpen.forecast.forheatmap.csv", header=TRUE)

However, I can't find that file. Could you please push it again or re-direct me to that file (or its replacement?). Thank you!!

**Comment by AileneKane** [comment]
I added the file! Sorry about that! I'm still updating it to include more points.  Let me know if you have questions about the code!

**Comment by MoralesCastilla** [comment]
@AileneKane 
I've given a first shot at mapping the forecasts (88b56900c5cf1e7f2e89136f745f65698f69e1c8). Still need to work on it more because I have added the topography through R, and I don't love the hillShade. I could add the topography to other surrounding countries, but the topography for Germany (which is pretty flat BTW) and Austria is going to be almost fully covered by points, regardless whether we add transparency. Any ideas/suggestions are super welcome!!

**Comment by AileneKane** [comment]
@MoralesCastilla This looks great! and SO MUCH better than mine! Thank you! There are a few little things I'd suggest:
1. I updated the betpen_for3dplot/betpen.forecast.forheatmap.csv file to include more lat/longs.
2. If it doesn't look too weird (too wide), I'd like it to be just 2 rows- one for chilling, and one for budburst. It would make it easier to compare the chilling changes to the budburst changes because you could look directly above or below. 
3. To the legend, could you add the units for Changes in budburst  (days) and order it from -2 to -11 (top to bottom)?
4. Perhaps we can round the chilling units in the legend so that they are not so strange? I know that its my quick and dirty code that made them be such unround numbers...

**Comment by MoralesCastilla** [comment]
@AileneKane 
new version ready (6573fa70ff53a6dc69079f96d8e329a233989a16). I've tried to follow your suggestions and it looks better now (I think). I'm happy to hear more recommendations.

**Comment by AileneKane** [comment]
@MoralesCastilla I love it!!! could you tell me how many sites are included on this map? I was having some discrepancies and problems getting all the lat/longs in the file and want to check that they all made it in.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Just adding that I think it looks amazing -- thank you!

**Comment by MoralesCastilla** [comment]
@AileneKane 
Ailene, I've been checking and there are 3072 sites included in these maps. Let me know if that is ok and/or if I need to re-do the maps. Thanks!

**Comment by AileneKane** [comment]
@MoralesCastilla Great! The only thing that I'd love to have added now is a points for the 2 sites that are used to showcase budburst responses  to chilling and forcing with warming for Betula in 3d plots. If you could add black symbols (or something that shows up on top of the different colored dots you've already mapped) so that readers can see where the 3d plots are from. The two sites are: lat 46.8167, lon=12.8000 and lat 48.3167, lon=15.8167.

**Comment by MoralesCastilla** [comment]
@AileneKane 
Hi Ailene, I guess we'll need to discuss about Sarah's suggestion to include this figure in the main text including a third line for GDD. If/when we decide to go for it, I will prepare a final version including the 3d plots locations.

**Comment by MoralesCastilla** [comment]
@AileneKane 
I have updated the maps, please let me know if this version would work.

**Comment by cchambe12** [comment]
@AileneKane I found the elevations for these sites

46.8167 x 12.8 is 659m
48.3167 x 15.8167 is 210m

**Comment by AileneKane** [comment]
Thanks @cchambe12 !

**Comment by AileneKane** [comment]
@MoralesCastilla I think the heatmaps look great!
