### ISSUE TITLE
new latitude figure

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#265]
@AileneKane 
To show photoperiod x latitude effects ... try FagSyl and maybe just show both winter and spring warming ... with and without photoperiod added to model.

**Comment by lizzieinvancouver** [comment]
In supp now, tweak:

- remove titles
- bigger fonts
- BB to budburst
- add degree sign
- change colors
- be sure to define both warming
- check intervals are 50%
- in caption reference mu_plot figure

**Comment by AileneKane** [comment]
This figure has been added! the supp just needs to be recompiled to include it.
