### ISSUE TITLE
check versus non-linear model

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#266]
@lizzieinvancouver Will find old non-linear code and pass to @dbuona to run/work on (this is hopefully supp material).

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
Check out: nointer_2level_interceptonly_sigmoid.stan and models_stan_supp.R ... let us know how it goes!

**Comment by cchambe12** [comment]
@dbuona @MoralesCastilla we're curious if either of you have any updates on the nonlinear model?

**Comment by dbuona** [comment]
Sorry, I forgot about this. I'm running the nonlinear model now

**Comment by lizzieinvancouver** [comment]
@dbuona Thanks! Could you check the rsq? And then plot the parameters for chill? You can set up a fake set of chilling by making a vector from low to high chill values in small increments and then calculate Y (using the equation in Stan) -- you can then plot Y versus X...

`fakechill <- seq(from=0, to=1000, by=0.1)
`

**Comment by dbuona** [comment]
with proper flagging:
12 divergent transitions
b_force -0.9385382
b_photo -0.2641393 
a_chill 10.0604101
b_chill  4.9189167

Rsq= 0.34

**Comment by dbuona** [comment]
@lizzieinvancouver  as for the plotting, I think I might be misunderstanding what you are looking for. What is the the Y in this case? Is this the Stan equation you mean: (1 / ( 1 + exp(a_chill*(chill[i]-b_chill)) ) )?

**Comment by lizzieinvancouver** [comment]
@dbuona Hmm, I think we could do both:
ychill = (1 / ( 1 + exp(a_chill*(chill[i]-b_chill)) ) 
ypred = mu_a+b_force*force + b_photo * photo + (1 / ( 1 + exp(a_chill*(chill[i]-b_chill)) ) 
... for the latter you have to equally build fakeforce and fakephoto.

**Comment by lizzieinvancouver** [comment]
@dbuona Also, can you do the same and report the parameters from nointer_2level_interceptonly.stan (which I just pushed and may need to be tweaked to run)?

**Comment by dbuona** [comment]
linear model:
b_force -0.9258096 
b_photo -0.2860911 
b_chill -2.2256866
with rsq of .40

...still working on the plots

**Comment by dbuona** [comment]
I just pushed a figure bb_analysis/figures/nonlinearplotbad
It looks weird. I can't tell if the I am misunderstanding the talk at hand or something in my fake data loop is bad: (available for critique below or on lines 239-250 of models_stan_supp.R). I i will keep poking at this in the morning, but any helpful tips would be much appreciated.
fakechill <- seq(from=0, to=1000, by=0.1)
a_chill<-summary(m2l.nisig)$summary[c("a_chill"),1]
b_chill<-summary(m2l.nisig)$summary[c("b_chill"),1]
dfnonlin<-data.frame(ychill=numeric(),fakechill=numeric()) 

for(i in c(1:length(fakechill))){
ychill<-(1 /( 1 + exp(a_chill*(fakechill[i]-b_chill)) ) )
dfhere <- data.frame(ychill=ychill,fakechill=fakechill[i])
dfnonlin <- rbind(dfnonlin, dfhere) 
}

**Comment by lizzieinvancouver** [comment]
@dbuona I think we're doing something wrong, but not sure what  ... see page [40 (PMP User Guide: Sigmoid)](https://drive.google.com/file/d/18Fzl-s4kadf1FkdHNgTxqzfoI5sA-F9h/view?usp=sharing)  ... when I try to re-create their figures I cannot.

**Comment by dbuona** [comment]
using the loop and the parameters in listed in the user guide I was able to reproduce the figure when I included negative chilling values.
 So it must be that our parameter estimates from the model are wonky.

**Comment by lizzieinvancouver** [comment]
@dbuona Nice work! But too bad on the model ... I have seen this in Isabelle's papers once or twice ... if we know a needs to be negative and b positive (or vice versa) we could try to set the priors for that.

**Comment by AileneKane** [comment]
dan did it with 10,000 iterations and got some divergent transitions and weird estimates. We decided to try the allspp flags in hopes that more data will help with model fitting. If that doesn't work we can try changing the priors.

**Comment by dbuona** [comment]
I ran allsps flags with 12,000 iters and 10,500 warm up with adapt delta of .999. It ran.
still gives weird parameters with a low n_eff 770.6552 for b_force. Rsq is .53 
b_force -0.8548461
b_photo -0.1356331 
a_chill 10.9176383 
b_chill  5.0590263
The plots look the same.

**Comment by lizzieinvancouver** [comment]
@dbuona Thanks Dan! The force and photo are not so weird, but yeah, weird on the chilling ... I think this is *close* to enough for us to say in the supp that we tried sigmoidal models for chilling and they ran, but gave non-intuitive results. 

Couple more requests:
- Can you run the equivalent data on the linear model with just sp on the intercept (the one you reported above) and give values and R sq?
- Can you try the above-data and model (allsps flags with 12,000 iters and 10,500 warm up with adapt delta of .999) with an a prior that does not include positive numbers and report on what happens?

**Comment by lizzieinvancouver** [comment]
linear model with allspp  (runs fast):
```
b_force -0.8314967
b_photo -0.2460295
b_chill -1.8853129
```

**Comment by lizzieinvancouver** [comment]
Here's the adjusted model ...

```
m2l.nisig.adja = stan('stan/nointer_2level_interceptonly_sigmoid_adjchilla.stan', data = datalist.bb,
               iter = 15000, warmup=12000, control=list(adapt_delta=.999)) 

b_force -0.8520394
b_photo -0.1322117
a_chill -4.9075567
b_chill  1.9231490 

n_eff and Rhat not okay on b_chill
5.763544    1.5613323
```
R sq (multiple or adjusted): 0.53

**Comment by lizzieinvancouver** [comment]
Just so we have it:

```
m2l.nisig = stan('stan/archive/nointer_2level_interceptonly_sigmoid.stan', data = datalist.bb,
               iter = 15000, warmup=12000, control=list(adapt_delta=0.999))
b_force -0.8532694
b_photo -0.1343176 
a_chill 10.8426215
b_chill  5.0502812
```

Rhats are 1.000 and lowest n_eff is b_chill at 1285 (b_force is 1545, b_photo is 4463 and a_chill is 9449).

R sq is still 0.53 compared to 0.57 for m2l.nib.

**Comment by lizzieinvancouver** [comment]
@AileneKane (@dbuona) Could you please add something like this to the supp?

As our focus is on experiments, which by design often impose high variation in phenological cues, we expected a linear model for chilling, forcing and photoperiod may be most appropriate. Non-linear models, however, are often most appropriate for phenological cues, especially in nature where chilling may always be very high or extremely short photoperiods are rarely experienced. Thus we tested a non-linear (sigmoidal) model on the OSPREE data (citePMP users manual). As chilling was the least experimentally manipulated in our database, we examined whether a sigmoidal curve for chilling would be more appropriate, but found that it was a poorer fit than a comparable all-linear model (R sq of 0.53 versus 0.57), did not dramatically alter estimates of forcing (-0.83 versus -0.85) or photoperiod (-0.25 versus -0.13) and led to non-biologically relevant values of chilling. Fitting non-linear models to experimental data may require more data, and/or data at very high and low chilling, forcing and photoperiod values, than currently available. 

Let me know if you need anything else. If not, I think we can close this issue.

**Comment by AileneKane** [comment]
@lizzieinvancouver I added this paragraph to the supplement. I will close this!
