### ISSUE TITLE
Update numbers for species/studies etc. for budburst ms

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#267]
@AileneKane Figure out another (more species model) to also report in supp and then put the flags for this (versus the main model) and the species and study numbers you're getting here for @MoralesCastilla @lizzieinvancouver tasks!

**Comment by AileneKane** [comment]
the snippet of code i use to get numbers of species, studies, and experiments is [here](https://github.com/lizzieinvancouver/ospree/blob/master/notes/snippet_for_ns.R)
to get the highest number of species and studies, I modified the main model flags to include crops and all species with the following flags:
use.chillports = FALSE
use.zscore = FALSE
use.allspp = TRUE#for the main model this is false
use.multcuespp = FALSE
use.cropspp = TRUE
# Default is species complex use  alltypes of designs
use.expramptypes.fp = FALSE
use.exptypes.fp = FALSE
use.expchillonly = FALSE

**Comment by AileneKane** [comment]
I believe this can be closed, if everyone agrees with the flags I used...

**Comment by lizzieinvancouver** [comment]
@AileneKane Okay, so we'll report the model that comes from these flags in the supp?

**Comment by AileneKane** [comment]
Yes- I will add this to the supp. could be zscored or not i suppose.

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver Check intxns of cue numbers are updated!

**Comment by AileneKane** [comment]
@lizzieinvancouver hopefully when you update intxns code this will be fixed but there is currently a discrepancy between the number of studies in bbstan_mainmodel_countinxns.csv (38) versus by doing unique(bb.stan$datasetID) with the main == true (30). Similarly, the unique number of studies in the full ospree_clean_withchill_BB.csv is 49, but in bbstan_allsppmodel_countinxns.csv this is listed as 66. Any idea why?

**Comment by lizzieinvancouver** [comment]
@AileneKane My code is updated! I was just waiting on you to put in all the #s and then planned to check the numbers and close this issue. 

I think you may just be confusing studies versus papers though? My numbers are all for paste(df$datasetID, df$study) ... the calculations for what I am doing have to be done at the study level. So is that the discrepancy?

**Comment by AileneKane** [comment]
@lizzieinvancouver this is so helpful to know! I will go through the manuscript and be clear in the wording as currently we use the word "study" to refer to both "experiments" and "papers"

**Comment by AileneKane** [comment]
I have gone through and checked both the ms and the supp to make sure that we are consistent about study (which now means experiments within papers).
