### ISSUE TITLE
prep to enter new papers

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#268]
@cchambe12 will work up new excel file (Lizzie can review), @dbuona will work up how-to doc (Cat and Lizzie will review) and then @lizzieinvancouver will assign new papers (see also #234 ).

**Comment by cchambe12** [comment]
I have loaded a new empty dataframe in ospree/data/ospree_newpapers.xlsx. I will work on adding in the papers Deirdre and Darwin found into the 'source' sheet. There were no columns that were never filled so I left all columns from the original ospree.xlsx sheet.

**Comment by cchambe12** [comment]
Alright all set! All papers have been added to the source tab

**Comment by dbuona** [comment]
@cchambe12 @lizzieinvancouver I started a Rnw and pdf file in ospree/notes/howtoscrape/howtoscrapejune2019. I am not sure that my synthesis is very helpful, as the only data I ever entered in ospree is Zohner which was not scraped from a paper. 

It seems like at some point Tim created screen shot videos about how to use Image J for scraping, but the links from howtoscrape_withnotes.pdf are broken. Does anyone know if we have these anywhere else? Please feel free to supplement  what I made so far...I fear it isn't so helpful as is.

**Comment by cchambe12** [comment]
@dbuona I added a video from Tim that I found in the W drive, I think it's the same as the broken link and it seems very helpful. I put it in the same folder... notes/howtoscrape/Data Scraping Tutorial.mp4. 

I modified your .Rnw slightly and compiled a new pdf. I copied pieces from the howtoscrape.txt that Lizzie made in 2017. And I think we should add a note about the difference between response and response.time. If the respvar is "daystobudburst" response is 1 and response.time is the value correct? And you say to follow Tim's instructions from lab meeting but is that lab meeting available somewhere, I couldn't find it.

**Comment by lizzieinvancouver** [comment]
@dbuona I have access to the 'how to scrape link' ... here's what's included:


To to W: drive > WeldShare > Wolkovich Lab > Budburst Review > meta_analysis_labmembers > your folder

In your folder, you'll find a zip file for ImageJ; install this. Add the Figure_Calibration.class, which will help for giving x and y calibrations to images.

You each have an Excel workbook to add data to. Tim and I will manually merge data afterwards.

meta_general - metadata for each sheet

source - list of the paper we are working with. Bibliographic information and notes on usefulness for our purposes.Note the "ToDo" column, which tells you which figure or table to focus on. You may find other figures are better, these were from our initial quick read. Also pay attention to datasetID column, which tells you how you should enter the identifying information for each paper.

study - Details on each experiment within each paper; possibly only one line for a paper, if only one experiment is relevant. This sheet is useful for our overview of what kind of experimental manipulations were done.

data_simple - Aggregated data on each experimental treatment combination.

data_detailed - Detailed data for the experiment, with all relevant information filled out.

Responses may be pre/post treatment, time, or other. Temporal responses, such as days to 50% budburst, are fairly common. An example of an other type of response would be percent budburst, again fairly common.
scratch - For temporary formatting and manipulating data scraped from ImageJ.

The two most important tabs to fill out are study and data_detailed. We can aggregate data down to get the data_simple version later.

Open your PDF and find the designated figure or table as noted in the source tab of the worksheet. Also note the datasetID column in source; use this as you fill out data_detailed and study.

Take a screen shot and import into ImageJ, following Tim's instructions from lab meeting. Use the scratch tab to get data into the right format, and then copy into data_detailed. Fill out the study tab as best as possible to describe the experimental treatments used in each study within each publication.

For a screen share walk-through on this process, see these tutorials:

**Comment by lizzieinvancouver** [comment]
@cchambe12 @dbuona Thanks for your work on this! I have now:
- changed the name of the xlsx (because what is 'new' could change)
- added the info from the link, you should review the files I uploaded as they have A LOT of questions and answers I did not post above that are relevant
@dbuona Can you review the new files and update yours? And change as Cat requested (I believe she is correct unless you find notes to the contrary)
@cchambe12 Can you review the info in the xlsx again? A quick glance showed references to dropbox and other things we don't need.
Let me know when you're both done and I will kick into gear on this again.

Cat, can you give one last search of the W drive for the other mp4? I could not find it.

**Comment by cchambe12** [comment]
@dbuona to add relevant links for folks to reference when inputting data
@cchambe12 to go through .xlsx and find extra mp4

Then... bounces to @lizzieinvancouver to check through and assign papers

**Comment by cchambe12** [comment]
I updated the .xlsx and removed the reference to Dropbox by updating it with a reference to the Google Drive folder. I also went through the W drive very thoroughly and did not find the missing .mp4

**Comment by lizzieinvancouver** [comment]
I made some changes to the file to enter data (now called ospree_2019update) in ...

- There is no data_simple tab so I deleted all the meta-data about it.
- added details to meta tab for what to put in continent
- 'entered by' said 3-5 letter acronym, I changed to 'your initials (2 or 3 capital letters, no punctuation)' ... I also adjusted this a bit in the list of columns for source tab

**Comment by lizzieinvancouver** [comment]
And then I updated the Rnw file with some URL links and again removed data_simple and references to it (we did used to have this, but it seemed pointless so we removed it).

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan  I recall you perhaps saying you checked for new papers but I cannot find the notes ... can you re-post them here and also give the exact date you checked?  If you only checked one database, can you and @DarwinSodhi check them both on the same date? Thanks! And Sorry I am being lame on finding the notes I know you posted.

**Comment by lizzieinvancouver** [comment]
Could you each enter a paper following the [howtoscrape guidelines](https://github.com/lizzieinvancouver/ospree/wiki/Entering-new-Data-2019-and-Beyond) and update/improve them if needed? As I would like to get this done *quickly* I have picked two data-lite papers (I think).
@dbuona Fu_et_al-2018-Global_Change_Biology
@cchambe12 Richardson et al. 2018
If it's possible to do this by end of the day Tuesday, I would appreciate it ... if not let me know.

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I checked Web of Science on June 10, and the notes can be found [here](https://github.com/lizzieinvancouver/ospree/blob/master/notes/litreviewnotes/lit.rev.notes.June2019.txt). I will coordinate with @DarwinSodhi to check them on the same date this week.

**Comment by dbuona** [comment]
I am having issues getting the Figure_Calibration plug in. It seems like there is a bug for me to download Java (I've downloaded it many times, but the installer never shows up). I am trying to figure out how to do it through terminal, but haven't had any luck yet...Cat did you have any of these problems?

**Comment by cchambe12** [comment]
I didn't have these issues for some reason! Have you checked security preferences to make sure it isn't being blocked? I know Java is constantly updating so developers frequently have issues with them, I hope that isn't the deal here.

**Comment by dbuona** [comment]
Okay, I got Java going by blindly following someones github instructions and hoping it did't give me viruses. Now I have the plugin and am ready to scrape

**Comment by dbuona** [comment]
I haven't finished entering this paper, but I've done enough to make some modifications to the how to scape instructions. I will finish it off after baby goes to sleep, but I don't anticipate needing to change the guide at all.

**Comment by lizzieinvancouver** [comment]
@dbuona @cchambe12 Thank you both! I will start assigning papers ... now.

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver Deirdre and I looked for new papers today and I have updated the notes to reflect this!
