### ISSUE TITLE
Ailene and Cat coordinate climate and PEP data used

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#269]
underlying data should be the same. Ailene uses a wider range of sites. Differences summarized here: https://docs.google.com/spreadsheets/d/1MXhI_82W3AC81sSdoUZFvB3CRn483aqYkGaGC9MBk5o/edit#gid=0

**Comment by AileneKane** [comment]
We discovered that cat was using mean temps to calculate chilling whereas i was using min and max temps (as we had done for main model). we were also using different versions of the EOBs data (though this likely had less of an effect). Cat will switch to using the tmin/tmax approach and update her files and figures.

**Comment by lizzieinvancouver** [comment]
@cchambe12 @AileneKane Awesome work! @cchambe12 ping me when things are updated and I will update my PEP sims code....

**Comment by lizzieinvancouver** [comment]
We discussed how we calculate chill (1 Sept to 30 April and force is 1 March to 30 April) and we feel okay with this.
