### ISSUE TITLE
check cp z model and bbstandleadin

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#270]
@lizzieinvancouver @cchambe12 @dbuona @MoralesCastilla Could someone run the chill portions z model and check the mu_sp_ests? In making the model table for the [supp](https://github.com/lizzieinvancouver/ospree/blob/master/docs/budburst/budburst_supp.pdf) I noticed that the cp.z model has chill estimate that is smaller than forcing and photoperiod. seems odd to me and i didn't remember that from earlier model runs. I have looked at the code of bbstanleadin and models_stan, and didn't see anything wrong but would love another set of eyes. Thanks!

**Comment by lizzieinvancouver** [comment]
@AileneKane 

I did these flags:

```
## set up the flags
use.chillports = FALSE
use.zscore = TRUE # see query below!
use.allspp =FALSE#for the main model this is false
use.multcuespp = FALSE
use.cropspp = FALSE
# Default is species complex use  alltypes of designs
use.expramptypes.fp = TRUE
use.exptypes.fp = FALSE
use.expchillonly = FALSE
```

and got this:
> m2lni.sum[grep("mu_", rownames(m2lni.sum)),1]
      mu_a_sp mu_b_force_sp mu_b_photo_sp mu_b_chill_sp 
    29.955191     -4.368213     -3.152990     -8.856283 

Am I looking at the wrong thing? Let me know, I am happy to take a look.

I did notice one weird thing though ... if you use the flag use.zscore = TRUE you get 37 spp and 1729 rows, but as FALSE it's 41 species and 2129 rows. That doesn't make sense that we should lose data when using the z-score so I think we should check the z-score code or can someone explain it to me?

**Comment by lizzieinvancouver** [comment]
Reviewed, this seems fine ... and we fixed the z-score error!
