### ISSUE TITLE
Adjust caption for PhenoFit in photoperiod paper

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#272]
@cchambe12 Can you add info on how we calculated budburst date from OSPREE data to the PhenoFit/OSPREE figure in the photoperiod paper. 

Also, @cchambe12  and @AileneKane I asked Isabelle about the figure and she seemed fine with it but felt we could make the point of what we are trying to get the reader to see clearer.

**Comment by AileneKane** [comment]
@lizzieinvancouver thank you for checking with her! That's good news and helpful feedback!

**Comment by cchambe12** [comment]
@AileneKane I updated the caption, would you mind checking it over? Thanks!
