### ISSUE TITLE
3D figures debate

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#273]
@AileneKane Jonathan suggested you could make your 3D figures 2D as heatmaps: spring warming on X or Y, winter warming on X or Y and days to buburst as color. I think we *should* have alternative figures of some sort in the supp... but I am still pretty pro-the 3D figures for various reasons we can discuss more in the coming days.

**Comment by lizzieinvancouver** [comment]
@AileneKane Add to supp ... Put in old-style 2D figures (spring-only, winter-only, both warming but clean up):

- remove titles
- add site info and daylength to caption
- remove param estimates
- keep 50% intervals
- add degree symbol
-Days to budburst (not BB)
- make sure legend on only one panel

**Comment by AileneKane** [comment]
I have added the 2D figures to the supp and am closing this issue
