### ISSUE TITLE
Better define our chill models

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#275]
In supp, say we used chill R and positive Utah and Dynamic Chill  ... and give brief overview of how this works (high temps can remove accumulated chilling in that season, chilling is generally higher above X and below y) and add refs within chill R if possible. (Ailene says she has article.)

**Comment by cchambe12** [comment]
Added! Let me know if I should add more detail!

**Comment by AileneKane** [comment]
I think this is done!
