### ISSUE TITLE
what is up with E-OBS tg versus txtm

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#277]
[Here's the ref for E-OBS that is usually used](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2008JD010201)

And here's [another ref to check](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/jgrd.50444)

And it should be somewhere in their basic info... [which should be here](https://www.ecad.eu/download/ensembles/ensembles.php) somewhere...

**Comment by cchambe12** [comment]
I think these issues only arise for certain months but the issues eventually even out. What I mean by this... in January (or in colder months) the Tmin values can draw down the mean temperature but in warmer months the Tmax can pull up the mean temperature. However, these discrepancies are [minor](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/PEP_climate/figures/comparing_tg_tntx.pdf)! Which means, after all of this, I think I have issues with my code - phew!! I will track down the issues on this and update.

**Comment by cchambe12** [comment]
Fixed! It was a coding issue all along, sorry for the false alarm!

**Comment by lizzieinvancouver** [comment]
Wait, what was it in the end? I want to know so I don't make it (if I ever get better at climate data).

**Comment by cchambe12** [comment]
I accidentally called on Tmin twice rather than Tmin and Tmax! So I was essentially reporting Tmin values rather than the average of Tmin and Tmax.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Totally something I could do, glad you caught it!
