### ISSUE TITLE
misc supp issues to address

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#279]
- Be sure to explain standardizing and ref Gelman and Hill for it being okay to do. -- NEEDS a little more, see comment in text. 
- Explain 14 days for field sample dates (I think this is done in explaining chill model?)
- % budburst (and which were our thresholds) @cchambe12  @lizzieinvancouver  ... done, but someone should check Lizzie's work!
-  For the use.expramptypes.fp==TRUE flag, we should say: ``The model we present in the main text uses Utah units for chilling and includes studies that experimentally manipulated forcing and photoperiod. Studies include a mix of methods to apply temperatures: constant temperatures, varied day/night temperatures and ramped temperatures." --- Semi-done, NEEDS work, see issue #290 
- more about what days to budburst means (it's days since forcing) versus field day of budburst -- Done as of Monday night (put it in the equations and again mentioned it in section on applying to Central European data), NEEDS a little work. 
- Check Cat's stuff on chilling, ???
- mention why we do not fit interactions -- done (Modeling limitations based on experimental designs)
- mention non-linear model (maybe) -- done (Modeling limitations based on experimental designs)
- explain why we show the main model and not allspp in main text (partly we do not want to show taxa estimates for taxa for low sampling due to how hierarchical models work) -- done but NEEDS work
- constant versus variable chill temps (artifacts of chambers) ... should be in supp in chill section (should be ref-ed in Fig 2 main text) --- NEEDS work
- We say 201 papers in supp, 193 in the supp main text (we actually contradict ourselves in the supp on almost the same line) ... which is it? I think we should give the total and/or the total - Fragaria.  --- NEEDS work

**Comment by lizzieinvancouver** [comment]
@AileneKane I called out your name in a couple places in the supp for help (search for 'Ailene') ... thanks for checking them.

**Comment by AileneKane** [comment]
@lizzieinvancouver Great! I will work on this and the main text today and pass off to @cchambe12 tomorrow!

**Comment by AileneKane** [comment]
@lizzieinvancouver I fixed the places you called my name out. @cchambe12 as you work on the supp, please check these and I will do a second check after!

**Comment by lizzieinvancouver** [comment]
@AileneKane I think we can close? Please do quick review and close if possible.

**Comment by AileneKane** [comment]
I checked these and we can now close!
