### ISSUE TITLE
fix captions in budburst

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#280]
- Fig 1 caption: results consistent across other model formulations, including non-standardized units and other models of chill 
- Can we ref the 203 species model (and that is is similar) in the mu figure? We need to connect that number clearly since we have it in supp.
- remember to rm Utah and OSPREE when possible!
- new Fig 2 and 3 captions should help readers understand why we used 3D

Figure 2: How chilling and forcing temperatures determine budburst, as predicted by a meta-analysis of experiments. Using our model results (see Fig 1) we predict budburst timing based on forcing temperature and estimated chilling converted to a mean temperature (see XX section of supp). Note that days to budburst is relative to experimental methods and thus not comparable to day of year in the field.

**Comment by AileneKane** [comment]
These changes have been made!
