### ISSUE TITLE
do cross referencing of supp and main text figures

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#281]
Whoop!

**Comment by lizzieinvancouver** [comment]
@AileneKane And make sure they are all referenced somewhere ... we should not present any tables or figures we do not reference (I think we need all of them, we just also need to reference them!)

**Comment by AileneKane** [comment]
having trouble getting this to work! I have referencesd everything somewhere, I believe, but we might want to reference the supp more in the main text

**Comment by lizzieinvancouver** [comment]
@AileneKane Do you mean the cross-ref isn't working? You do need to (1) compile the main text (leave all aux etc. files) then (2) compile the supp (leave all aux etc. files), then repeat 1-2 a couple times ... If that doesn't work you can try to find the error message about it (search through your log for 'xr') and google anything you find ... if none of that works I can try to take a look tomorrow at the errors if you want ... ?

**Comment by AileneKane** [comment]
@lizzieinvancouver I will try repeating 1 -2 more and see if that works! I think i only did it once each. I'll let you know if it is still not working.

**Comment by lizzieinvancouver** [comment]
@AileneKane You definitely it have do it more than once ... the first time through builds the aux files that yields has the labels each other file needs, the second time through each file can read the other aux file so once should basically never work ... same for bibtex and other such things often. Don't assume compiling once is enough. Let me know how it goes ... if it still fails please send me a text or reply here and we can look through .log files together or I can try running it.

**Comment by AileneKane** [comment]
@lizzieinvancouver I think I got it to work. I usually compile in rstudio, but if i compile in TexShop it seems to work. I tried for a test set, so i will convert all and try again. thanks!

**Comment by AileneKane** [comment]
Done!
