### ISSUE TITLE
misc main text fixes

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#283]
Main text:
- double check papers with forcing and chill to make sure they do not compare these cues
- be stronger somewhere that "Korner and Basler hypothesized this but everyone (except you) lacks the evidence to support it, you have now analyzed the experimental data necessary to confirm this hypothesis, etc"

**Comment by lizzieinvancouver** [comment]
- Make sure everyone has addresses. Jehane is still UBC I think so I added that ... Tim is MIT ([see here](https://www.media.mit.edu/people/tsavas/overview/)) and is Harvard and U.S. DOT Volpe National Transportation Systems Center and Nacho is University of Alcala, which I added also (check my accents there compile and do not break the Rnw!).

**Comment by lizzieinvancouver** [comment]
@AileneKane If we want to shorten the Weinberger we could switch to this:

`\par Progress on developing chilling models for wild species is especially slow, as only a small portion of studies (\Sexpr{totexpchill} of the total \Sexpr{nst} studies) manipulate chilling directly. Instead many studies (\Sexpr{weinchill} out of \Sexpr{nst}; the remaining studies did not not appear to manipulate chilling) estimate chilling effects through sequential removal of tissue from the field followed by exposure to `forcing' conditions \citep{weinberger1950}, with the assumption that tissues collected later experience more chilling. We found, however that chilling and forcing estimates varied between these two approaches (see Fig. S4), suggesting a study's design of chilling impacts both forcing and chilling estimates. An improved understanding of chilling could in turn alter our understanding of forcing. Although researchers often define `chilling' and `forcing' treatments based on temperatures, physiologically plants appear to accumulate forcing mainly after chilling requirements have been met,  thus identifying processes plants undergo when accumulating chilling versus forcing will be critical for the most accurate forecasts \citep{chuine2016}.`

And then add this to supp:
`This method benefits from more natural chilling conditions but introduces other challenges: first, chilling duration may not always co-vary with the magnitude of total accumulated chilling \citep{dennis2003}, and, second, photoperiod and other factors also change over time. Indeed, we found that sequential-removal studies tended to result in later budburst, weaker effects of forcing and stronger effects of chilling compared to estimates from studies that directly manipulated chilling \citep[Fig. 4S][]{weinberger1950,polgar2013}...`

**Comment by AileneKane** [comment]
@cchambe12 @dbuona @MoralesCastilla @jsamaha @tsavas @dflynn-volpe  I have updated affiliations so please check and let me know if yours is correct or how you'd like it changed (for example, some of you could be affiliated with the arboretum AND OEB I think? Please let me know your preference)

**Comment by dbuona** [comment]
@AileneKane I think I'd like to be both arboretum and OEB. Also, in your (or others' )opinion. Is there an advantage to including a middle initial too? I notice that you and Lizzie tend to do so...

**Comment by lizzieinvancouver** [comment]
@dbuona I think middle initials were (perhaps) originally used just to differentiate names (back when only English men with boring names published, maybe?). Now I think you can use the name you like, but you should try to pick one you want to stick with through time. 

I also personally do just first initials because I don't think anyone needs to know my gender or such to read my papers.

**Comment by lizzieinvancouver** [comment]
@dbuona Basically, if you like your initial or such, you should include it! But if not, `go with whatever you fancy' (says Jonathan Davies, who notes `12 million people have my name ... the whole of Wales for a start').

**Comment by AileneKane** [comment]
@dbuona I do it simply because I like to have a remnant of my maiden name- and also in case there is some other A. Ettinger out there! I will add the arb to your affiliations!

**Comment by lizzieinvancouver** [comment]
@AileneKane I think we can close? Please do quick review and close if possible.
