### ISSUE TITLE
when is earliest budburst in Fig 2 and Fig 3?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#284]
Add to caption somehow ... at least keep in comments ... and we need it for the constant temps version of Fig 2 (this could go in supp as 'these two methods predict (or don't) a similar earliest day of BB at xx forcing and xx chill)....

Should help readers understand why we used 3D.

**Comment by AileneKane** [comment]
I have added this to Figure 2. Still need to do Figure 3

**Comment by lizzieinvancouver** [comment]
This is done! A while ago....
