### ISSUE TITLE
work on budburst cover letter

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#287]

**Comment by AileneKane** [comment]
@lizzieinvancouver I pushed the cover letter [here](https://github.com/lizzieinvancouver/ospree/blob/master/docs/budburst/CoverLetter_Science.pdf) though I think we may not want to final version with list of recommended reviewers on git. could you edit?

**Comment by AileneKane** [comment]
@lizzieinvancouver I like your edits and have pushed an updated version for your review!

**Comment by lizzieinvancouver** [comment]
@AileneKane Thanks! Jonathan pointed out one dull sentence in a critical spot (I wrote it, sorry!) so I have pushed a new version with a little more oomph. See what you think....

**Comment by AileneKane** [comment]
@lizzieinvancouver I think this looks great! I recompiled and i believe the cover letter is ready to go!
