### ISSUE TITLE
add to supp how we estimated forcing and photo ...

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#290]
I started this in the supp Rnw:

> Our studies included a diversity of designs for forcing and/or photoperiod, including studies with constant forcing temperatures, forcing temperatures that varied between day and night. Additionally several studies ramped forcing or photoperiod. For all studies we used the daylength of light as our photoperiod estimate (e.g. a study with 8 hours of light and 16 hours of dark was recorded as `8'). For forcing we adjusted the temperature based on the studies design as follows: if forcing was constant (same temperature applied 24 hours/day) we used that temperature, if forcing varied with photoperiod with estimated the mean daily temperature weighted by the hours that temperature was applied, we similarly weighted forcing for ramped studies each day, then averaged over the period until budburst.

But could use help ... @AileneKane @cchambe12 could you check this? @cchambe12 Can you add a line about what photoperiod we used for ramped studies?

**Comment by AileneKane** [comment]
loosk good! I think we can close this after @cchambe12 adds a line.

**Comment by cchambe12** [comment]
I'm ready to add it, I just saw you were working on the supp. Is it okay to add it now @AileneKane?

**Comment by AileneKane** [comment]
@cchambe12 could you just paste it below and i will add it in?

**Comment by cchambe12** [comment]
Good thinking! 

"For studies that ramped photoperiod, we used the photoperiod individuals initially experienced (e.g., studies with photoperiod lengthening from 6 hours until budburst, we recorded as `6')."

**Comment by AileneKane** [comment]
@cchambe12 thank you!
