### ISSUE TITLE
enter new papers (that are not about strawberries)

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#291]
Time to enter new papers! Want to know how? [Check out this great wiki page](https://github.com/lizzieinvancouver/ospree/wiki/Entering-new-Data-2019-and-Beyond)

**Comment by cchambe12** [comment]
For richardson18, one of the figure panels shows daystobudburst for two dominant shrub species but does not distinguish between the two since they used PhenoCams to capture the data. How should I enter this?

**Comment by lizzieinvancouver** [comment]
@cchambe12 Can you check how we did it for the Fu studies already entered? I am pretty sure those were also ambient + XX degrees (or you can search for those studies ... there would be a + sign in the forcing column) ... as for the PhenoCam. Good question! We previously ruled out anything that was not IDed to species (NDVI etc.) so I guess we should skip that figure also? What do you think?

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan @DarwinSodhi Time to enter papers! Please take a data/ospree_2019update.xlsx (but do **not** update this file!) for your assignments. Can you try to enter them by end of the day Friday?

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver Deirdre and I are going to meet tomorrow and tackle our papers! we will let you know if we come across any insurmountable challenges!

**Comment by cchambe12** [comment]
@lizzieinvancouver we ended up not using Fu13 because it wasn't clear when the forcing started. I checked the other `ambient +' studies - most weren't included for various reasons except for guak98, which didn't have too high of response times.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Thanks! Fu13 is in the full OSPREE database but not in the current days to budburst work? Or did we not even enter the data?

**Comment by cchambe12** [comment]
@lizzieinvancouver it's in the full OSPREE database but not in the days to budburst work so we didn't correct for the high response.time values!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Okay, then we should still include the Richardson data for the update to OSPREE, and follow whatever we did in fu13 and similar studies (I imagine they too had really late days to budburst)?

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver the figure I have to scrape is 7 graphs in one, based on Tim's instructions should I scrape every single graph separately? I have attached the screenshot I have here!
<img width="1108" alt="Screen Shot 2019-07-11 at 1 27 45 PM" src="https://user-images.githubusercontent.com/43154379/61083770-66d95900-a3e1-11e9-95b6-5cab5d0944f1.png">

**Comment by DarwinSodhi** [comment]
I am attempting to scrape the data but I am having two problems: 1. The multi point tool doesn't let me select multiple points & 2. when I measure something I get this (look at attached screen shot). Anyone know what I can do? @lizzieinvancouver @dbuona @cchambe12 
<img width="444" alt="Screen Shot 2019-07-11 at 1 59 06 PM" src="https://user-images.githubusercontent.com/43154379/61085110-570f4400-a3e4-11e9-946e-bf7dc150df1c.png">

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi I don't know ImajeJ well enough to help with your second query ... but hopefully @cchambe12 @dbuona or @DeirdreLoughnan can help? 

For the query on the 7 panel figure -- yes! They look like all unique datapoints so you will have to scrape each panel separately.

**Comment by DeirdreLoughnan** [comment]
I think the issue is the rectangle masking the figure, but @DarwinSodhi, let me know if you are still having this issue and we can look at it together again.

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver @DeirdreLoughnan figured out the problem thanks to Deirdre!

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver I have a few more questions. when entering data into the data_detailed tab what do you do if there is a column that should be filled out but isn't mentioned in the methods? also, another figure I need to scrape is shown below, should I be getting both flushed and unflushed data?
<img width="969" alt="Screen Shot 2019-07-11 at 4 40 23 PM" src="https://user-images.githubusercontent.com/43154379/61092383-df98df00-a3fa-11e9-96d8-22511476ca68.png">

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi What's the column? (Sometimes it means we don't enter the paper, sometimes we leave it blank... often we try to convert the data in the paper so we have the data/info.)

For the above data  ... you need to figure our a %budburst for 'abnormal' to enter the data, if you can then you'd enter that number repeatedly for abnormal and you would enter unflushed as 0% budburst and you'd need to enter the percent seedlings in another column ....

You got a hard paper!

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver it is the field sample date, the authors used seedlings so there weren't any cutting and they also had an outside trial (which I assume means field chilling)!

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi There is field sample date. From Man et al. 2017 Budburst Experiments section:

`Batches of seedlings were sequentially moved into the climate chambers from outdoors at 10-day intervals between October 1st and January 1st and 20-day intervals thereafter to mid-April, which resulted in a time series of 16 budburst experiments for each species (15 in the climate chambers and 1 outdoors). `

If you read the paper closely I assume you can connect the chilling hours to those 16 dates ... It's a pain, but we have done it before.

Also, there is a lot of info of the whole life of the seedlings, but they appear to be outside in Ontario right before they are chilled ("Both broadleaf and conifer seedlings remained outdoors to undergo natural hardening and dehardening under ambient photoperiod and temperatures."). And the chilling is in chambers:

> The experiments were conducted in two computer-controlled walk-in climate chambers (i.e., two replications) set at 15◦C (day)/5◦C (night) and a 14-h photoperiod at 350 μmol m−2 s−1 photosynthetic photon flux density (PPFD).

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver it is unclear whether Fu et al 2019 used 12 or 11 chambers (the text suggests both) and what the 11 open circles in Fig 2 represent. Should I just include the mean values shown in Fig 3, the exact values of which are in a table in the supplementary material?

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan That sounds good (esp. being able to use the exact values from the table). You should ask Mika or Kelley to double-check the chamber number and then put in your best guess (and make a note).

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver Having an issue with figure 4 again, the authors don't provide a value for %budburst for abnormal, instead, the authors state that "Budburst was considered abnormal if it started first in lower branches, stems, and roots in broadleaves and if bud and needle expansion were constrained in conifers". As for connecting the chill hours to the dates, that is relatively straightforward as the authors have that information in the supplementary information!

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi Okay, I would enter 'abnormal' in the % column (or 0% for the other points) and add the definition of it in the notes.

**Comment by kfslimon** [comment]
![Screen Shot 2019-07-12 at 11 07 34 AM](https://user-images.githubusercontent.com/52802928/61150847-42d94e80-a499-11e9-886a-407a4a6482fd.png)
![Screen Shot 2019-07-12 at 11 31 55 AM](https://user-images.githubusercontent.com/52802928/61150866-55ec1e80-a499-11e9-9b31-e03e5942ef73.png)

The figures I am attempting to scrape have arrows pointing to the lowest point with what look like coordinates for that point. This is not explained in the caption. Should I enter data for these points based on what I get from imageJ or from the information given by the arrow?

**Comment by lizzieinvancouver** [comment]
@kfslimon Hmm, if you are 90% sure the coordinates are the temperature then I would use the temperature (you probably know this but in Europe they use commas for decimal places). You can ask @DeirdreLoughnan for a quick review of the paper and second opinion (we do that a lot).

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver I have all the data which is good! but I am unsure which column to put the chill hours for each measurement and also where to indicate if the measurement was from an abnormally flushed or unflushed seedling.

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi Good questions! `abnormal' (and 0 etc.) should go in the column `response`.  For the field chilling you use two columns:
```
field.chill.units
cu.model

```

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver another question what do you do if the provenance lat and long are ranges rather than specific values?

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi If they do not break the data out by each population (often they do) you should pick the most central ... you may need to enter them all in Google earth to do that. Be sure to give the population a name that indicates this, like: central BC-central latlong of multiple locations

Also given your study you need to carefully review ALL the columns. You have info for growing lat and growing lon columns etc..

**Comment by m-yasutake** [comment]
Hi @lizzieinvancouver, Deirdre and I worked on the Vitra et al. paper today and came across a couple questions:

1) Does dehardening count as an "other treatment"?
2) Should we extract data from Fig. 2 if it's unclear if it represents the mean across treatments or under ambient conditions?
3) Do we want to extract data from Fig 3b and c?
4) Should the error bars from Fig 3 be extracted if the error type and error values are unclear?

**Comment by lizzieinvancouver** [comment]
@m-yasutake @DeirdreLoughnan 
1. Yes!
2. I am a bit out of time to help on this in the next while, @cchambe12 could you check if you know the answer to any of this query and/or could provide a second review? 
3. No, since it's not phenology ....
4. Yes, put in all the info you can. (Again @cchambe12 could you see if you can deduce what the error bars are?)

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver @cchambe12 for each point in this figure there should be 15 points for both the black and white dots but none of these graphs actually have the 15 points. I don't quite know why and for Larix decidua it's hard to see all of the white points and I don't know how to proceed with that when scraping the data.
<img width="796" alt="Screen Shot 2019-07-16 at 10 43 21 AM" src="https://user-images.githubusercontent.com/43154379/61316856-a673bc80-a7b6-11e9-8674-96757159f55f.png">

**Comment by cchambe12** [comment]
@DarwinSodhi I am guessing the data points are overlapping each other. In the past, I have done my best to find each point. For the points I can't see, I just don't record them. I would check the rest of the paper or the supplement for a table to see if the missing points are listed. Sometimes they also list information in the caption. Hope this helps!

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver @cchambe12 The below panel in the picture above is a graph of the forcing unit sums by chilling unit sums. I am unsure if this in data that I should scrape or not?

**Comment by cchambe12** [comment]
@DarwinSodhi is it is the same data as in the row above? If so, we probably don't need the same data twice. If not, check out how we did laube14a, gheraldini10, or heide93! The respvar will be thermaltimetobudburst. We may decide later that we'll want to look at GDDs or chill utah to budburst so it may be useful to include.

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver @cchambe12 a few more questions. wouldn't photoperiod_night just be (24-photoperiod_day)? my paper does have field units but they use an equation to calculate it (showed below? for cu model what should I put?
<img width="506" alt="Screen Shot 2019-07-16 at 2 31 34 PM" src="https://user-images.githubusercontent.com/43154379/61331360-aedbef80-a7d6-11e9-9549-5c7e149fdd09.png">

**Comment by kfslimon** [comment]
Two quick questions:

1. My last paper (ramos17) does not include the years they did their experiment anywhere in the paper or supplement. How big of a problem is this/ is there anywhere else I might find this info?

2. Is there a proper procedure in imageJ for getting the length of the error bars? Also, is the number recorded meant to be half of the bar (ex. +/- 1.5) or the whole bar (combined length of the bar below and above the data point). 

Thanks!

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi Okay! Yes, photoperiod_night is usually 24 hours minus photoperiod day ... unless they did something weird (which can happen, you can have a longer or shorter day in a chamber!).

And, I would call those harrington_chillunits .... not great, but people can look up what they did and we will know not to use them as Utah or such. Thanks!

**Comment by lizzieinvancouver** [comment]
@kfslimon Re: "Is there a proper procedure in imageJ for getting the length of the error bars? Also, is the number recorded meant to be half of the bar (ex. +/- 1.5) or the whole bar (combined length of the bar below and above the data point)."

As long as entered correctly, it's fine. So if these error bars are SE you could take the upper or lower half and report the error units as SE ... or you could take the whole error bar and report as 2SE.

**Comment by lizzieinvancouver** [comment]
@kfslimon Addressed year in a [new issue](https://github.com/lizzieinvancouver/ospree/issues/294)

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan I looked at Vitra Fig 2 and I agree it seems hard to know what data they are reporting and thus how to enter it. So we should skip it.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Can you update your xlsx file to include raw data means and standard errors for each treatment from Flynn & Wolkovich?

**Comment by cchambe12** [comment]
@lizzieinvancouver For the chilling units reported in the supplement, should I report just the dynamic model? And why are the field chilling until Apr 1 and until May 1 reported in Table S2? I just want to make sure I'm not missing something!

**Comment by lizzieinvancouver** [comment]
@cchambe12 for Flynn & Wolkovich: 20-22 January 2015 for HF (so say 21 Jan 2015?) and 25-28 January 2015 for SH ... say 26 or 27 Jan 2015?

**Comment by cchambe12** [comment]
Thanks, Lizzie! All updated.

**Comment by lizzieinvancouver** [comment]
1000+ rows of new data entered!
