### ISSUE TITLE
Variance changed?

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#292]
@lizzieinvancouver @dbuona @cchambe12 I noticed in checking over the tables and our manuscript that a statement we make is no longer true: chilling does NOT have lower variance than forcing in our current models. Could someone else fit the main model with z-scored predictors and check that you get the same result? I will refit my models to be sure that this is correct with z-scored predictors, too. If it IS correct, than I will take out the following statements in the ms: `Species also showed fairly consistent responses to chilling (variance = 2.07 days per chill unit, Fig. \ref {fig:mu}). Responses to forcing, in contrast, were the most variable across species (variance = 0.91 days per \degree C of warming).'

**Comment by AileneKane** [comment]
@lizzieinvancouver @dbuona @cchambe12  never mind. in looking at models_bb_compare.xlsx it looks like the variance has not changed recently - in march it was also true that variance was higher for chilling than for forcing for UTAH. I think this text was written when we were using chill portions (which does have higher variance in chilling than forcing).

**Comment by lizzieinvancouver** [comment]
@AileneKane Here's what I get on the z-scored main model (37 sp. 1729 datapoints):

```
sigma_b_force_sp  5.681076
sigma_b_photo_sp  5.316710
sigma_b_chill_sp  7.334929
```
These numbers don't really line up with the figure though...

**Comment by AileneKane** [comment]
@lizzieinvancouver Thanks! Glad your results agree. I have adjust the text, replacing the above two sentences (which didn't make sense given that chilling variance was HIGHER than forcing variance) to say:
'Species also showed fairly consistent responses to chilling, with all estimates less than zero (Fig. 1).
Responses to forcing, in contrast, spanned positive and negative estimates across species (Fig. 1).' 
What do you think?

**Comment by AileneKane** [comment]
OK, lizzie and i talked and decided instead to report the variance of forcing in chilling. so the above text has been replaced with 
`Species responses to chilling were slightly more variable
(variance = 2.07 days per chill unit in the standardized model, Fig. 1) than responses to forcing (variance =0.91 days per forcing unit in the standardized model ,Fig. 1).' 
Lizzie, I realized that the values you reported are what i get for the uncentered model (which is the default with the main flags in models_stan.R). closing this...

**Comment by lizzieinvancouver** [comment]
@AileneKane I changed the default in the code so I did report the z-score estimates ... so I think the numbers I reported should be what you also get in the z-score model (and you report the uncentered sigmas in the main text). What am I missing?

**Comment by AileneKane** [comment]
@lizzieinvancouver i get z sigmas of 2.07 (chill) and 0.91 (force), and nonz sigmas of 7.36 (chill) and 5.67 (force). Originally i did report the nonz sigmas, but I'm thinking that if our goal is to compare their magnitude then we should use the z sigmas, right?

**Comment by lizzieinvancouver** [comment]
@AileneKane Yes! I was thinking we should just report both ... I am jumping on a call now, but will check what I get carefully and post it this afternoon so we can triple-check.

**Comment by lizzieinvancouver** [comment]
Okay, first model!

```
use.flags.for.mainmodel <- TRUE
use.flags.for.allsppmodel <- FALSE
use.yourown.flagdesign <- FALSE

if(use.flags.for.mainmodel==TRUE & use.flags.for.allsppmodel | use.flags.for.mainmodel==TRUE & use.yourown.flagdesign |
    use.yourown.flagdesign  & use.flags.for.allsppmodel | use.flags.for.mainmodel==TRUE & use.flags.for.allsppmodel
    & use.yourown.flagdesign) print("ALERT! You have set too many master flags to true, you must pick only one!")

if(use.flags.for.mainmodel){
use.chillports = FALSE
use.zscore = FALSE
use.allspp =FALSE # for the main model this is false
use.multcuespp = FALSE
use.cropspp = FALSE
# Default is species complex use  alltypes of designs
use.expramptypes.fp = TRUE
use.exptypes.fp = FALSE
use.expchillonly = FALSE
}
```
Any my sigmas are ...
```
> m2lni.sum[grep("sigma_", rownames(m2lni.sum)),]
                       mean     se_mean        sd       2.5%        25%
sigma_a_sp       19.1990839 0.044817138 2.6272853 14.6884338 17.3382872
sigma_b_force_sp  0.9159290 0.003112437 0.1610490  0.6427159  0.8014531
sigma_b_photo_sp  0.7778001 0.004582057 0.1631722  0.4985011  0.6611260
sigma_b_chill_sp  2.0660130 0.006533794 0.3486132  1.4753310  1.8179917
sigma_y          15.8234300 0.003825964 0.2831660 15.2694233 15.6356143
```

**Comment by lizzieinvancouver** [comment]
So, here's the z-score model:

```
# Master flags! Here you pick if you want the flags for the main model (figure in main text) versus the all spp model (supp)
use.flags.for.mainmodel <- TRUE
use.flags.for.allsppmodel <- FALSE
use.yourown.flagdesign <- FALSE

if(use.flags.for.mainmodel==TRUE & use.flags.for.allsppmodel | use.flags.for.mainmodel==TRUE & use.yourown.flagdesign |
    use.yourown.flagdesign  & use.flags.for.allsppmodel | use.flags.for.mainmodel==TRUE & use.flags.for.allsppmodel
    & use.yourown.flagdesign) print("ALERT! You have set too many master flags to true, you must pick only one!")

if(use.flags.for.mainmodel){
use.chillports = FALSE
use.zscore = TRUE
use.allspp =FALSE # for the main model this is false
use.multcuespp = FALSE
use.cropspp = FALSE
# Default is species complex use  alltypes of designs
use.expramptypes.fp = TRUE
use.exptypes.fp = FALSE
use.expchillonly = FALSE
}
```

And my sigmas are ...
```
> m2lni.sum[grep("sigma_", rownames(m2lni.sum)),]
                      mean     se_mean        sd      2.5%       25%       50%
sigma_a_sp        9.449358 0.021517274 1.2810117  7.249944  8.549048  9.327872
sigma_b_force_sp  5.661933 0.020135994 0.9772854  4.004583  4.980988  5.585098
sigma_b_photo_sp  5.258016 0.033671312 1.1591561  3.373889  4.417937  5.103593
sigma_b_chill_sp  7.353842 0.023650418 1.2519630  5.156445  6.469034  7.244178
sigma_y          15.767574 0.003583553 0.2764378 15.233567 15.586485 15.764659
```

**Comment by lizzieinvancouver** [comment]
@AileneKane We get the same answers but your comment above:

> i get z sigmas of 2.07 (chill) and 0.91 (force), and nonz sigmas of 7.36 (chill) and 5.67 (force)

Is just the reverse of what I get ... 7.36 (chill) and 5.67 (force) are my *z-score sigmas*

**Comment by AileneKane** [comment]
@lizzieinvancouver wow- thanks for checking that! I had switched the models in the main ms (i.e. i was loading the nonstandardized model and calling it the zmodel and vice-verse). All good now!
