### ISSUE TITLE
small things to double-check before submitting

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#293]
- title matches across cover letter, supp and main text
- search the PDFs for 'still need' and '??' and 'XX' and 'lat, lon'
- uncertainty intervals should be the term so search that 'percentiles' is removed

**Comment by lizzieinvancouver** [comment]
@AileneKane One more! It occurred to me we should double check we actually present Utah units when we say we do (and Chill portions) ... if the natural-scale models still use chilling/240 as an input then we need to convert our parameters for chill from any of those models (or explain clearly that we are using 'adjusted chill units').

**Comment by AileneKane** [comment]
@lizzieinvancouver I converted everthing to be utah units (i.e. by multiplying by 240) in the figures. Let me know if there are particular instances where you think this should be done!

**Comment by lizzieinvancouver** [comment]
@AileneKane Great. Have you also converted parameter estimates when mentioned in the text? I think would be it! (I am not sure how to convert the variance ... if that is an issue you could just focus on the standardized model there.)

**Comment by AileneKane** [comment]
I did not convert parameter estimates in the text where we used the term "chill units" rather than utah untis. Perhaps I should define this i the supp?

**Comment by lizzieinvancouver** [comment]
@AileneKane Yes! I think we should just define the term in the supp (and maybe explain it was necessary for model fitting). Thanks for putting up with all my niggling requests!

**Comment by AileneKane** [comment]
@lizzieinvancouver I really appreciate your attention to detail!
