### ISSUE TITLE
check out PERPHECLIM data

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#296]
@cchambe12 Check for how much data they have on leafout or budburst for common species (betpen and fagsyl?)

**Comment by lizzieinvancouver** [comment]
[The link I meant to include...](https://www6.inra.fr/projet-accaf-perpheclim_eng/The-PERPHECLIM-project)

**Comment by cchambe12** [comment]
Alright so I checked out Perpheclim for BETPEN and FAGSYL:

BETPEN: 818 data points for BBCH 15 - for 56 sites from 1880-2015

FAGSYL: 514 data points for BBCH 9 - for 45 sites from 1997-2014
                711 data points for BBCH 15 - for 59 sites from 1881-2015

Neither species had BBCH 19 recorded but spread of data covers France. 

I'd be happy to look into more species if we think it would be useful!

**Comment by cchambe12** [comment]
Not enough data to pursue.
