### ISSUE TITLE
response again

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#30]
How to recode 'no break' or 'no response' ? Probably just treat as NA? It's really a failure time analysis, but that is too much work!

**Comment by danfbflynn** [comment]
For daystobudburst, best we can do is NA
For anything which is a percentage or count, see if we can make these 0

**Comment by lizzieinvancouver** [comment]
See also issue #147 ... we do have some data with this issue. Not enough (maybe 200 rows out of 4000) in my mind to do a survival analysis approach but we could: 

- label them all as some giant number (999)
- try the analysis with them set to the max budburst date
- # important note! If we do this we must remember that we also set a minimum %budburst threshold for data (see clean_bbperctodays.R) and so we would need to go back and incorporate those tossed data too...

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver Recode true non budburst as 999.

**Comment by lizzieinvancouver** [comment]
These data for BB are recoded to 999 and I made a note in bbcleaningresp_README.txt about the 'important note!' mentioned above
