### ISSUE TITLE
set up new climate data to estimate chilling

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#301]
If we want to use most of the new data we've added; we may new climate data ... I have looped in @AileneKane @MoralesCastilla @cchambe12 for help. 

First things first ... @AileneKane Can you tell us when the E-OBs and Livneh data currently end?

**Comment by lizzieinvancouver** [comment]
If we need more recent data we have options:

> Hi Lizzie,
> 
> I ran into the same issue, using Livneh through 2015 and then wanting to extend to present. 
> 
> To get through 2016, I suggest Justin Sheffield’s v3 of the Princeton Global Forcing dataset, which covers 1948-2016: http://hydrology.princeton.edu/data/pgf/v3/0.25deg/
> 
> To get beyond 2016 I think your best bet is a reanalysis product. I think NASA’s Merra-2 has Tmin and Tmax. Unfortunately I don’t think the NARR does. The new ERA-5 does as well.
> 
> For my purposes, I only needed daily data for a subset of western NA, from southern Canada through northern Mexico. For that, I made dailies from the NLDAS2 hourly data.
> 
> If it turns out that all you need is western NA, I’d be happy to share my dataset with you. It’s 1/8-degree, covers 1901-2018, and has been reasonably carefully calibrated to stitch together the variety of datasets out there (in the US, using TopoWx for 1948-2016 and then PRISM for 2017-2018). However, my dataset has not yet been published or used in any publications, so that might be a complication.
> 
> Good luck and do let me know if you’d like the dataset.
> Park
> 
> 
> -----------------------------------------------------------------------
> Park Williams
> Lamont Associate Research Professor, Junior Staff
> Lamont-Doherty Earth Observatory of Columbia University
> 61 Rt 9W; Palisades, NY 10964
> williams@ldeo.columbia.edu

**Comment by cchambe12** [comment]
I found information about this in [ospree/notes/dailyclimatedata.txt](https://github.com/lizzieinvancouver/ospree/blob/721ab668bb3b697efe6abbf88ee96507eb25dda5/notes/dailyclimatedata.txt)

It looks like the best we have is through 2013. I followed the link [mentioned](https://data.nodc.noaa.gov/nodc/archive/data/0129374/daily/) which was last updated 11-Oct-2014...

**Comment by lizzieinvancouver** [comment]
@cchambe12  Thanks! Can you check if Livneh is updated through 2015? I wonder if that would be easier than switching to a new dataset, depending on how much 2016 data we have.

**Comment by cchambe12** [comment]
@lizzieinvancouver It has not been updated unfortunately. I will look into Merra-2 and ERA-5!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Okay, but I think we'd probably start with the first suggestion: Justin Sheffield’s v3 of the Princeton Global Forcing dataset, which covers 1948-2016: http://hydrology.princeton.edu/data/pgf/v3/0.25deg/ ... but we should see how far beyond 2016 we need, maybe one of the others will be best....

**Comment by cchambe12** [comment]
Oh okay, I assumed we would need data past 2016. I will look into that now! 

As an aside, the Merra-2 _could_ work but we would need to use hourly data (so it would be much slower) at 0.5 degree resolution - which doesn't seem ideal.

**Comment by cchambe12** [comment]
@lizzieinvancouver Okay, so the Princeton Global Forcing dataset seems great! You have to download the data by year but it seems very manageable and is at the same resolution as the E-OBS data. Temperatures are recorded in Kelvin and the layer names are not the dates so it takes some finagling but seems straightforward enough. I think we should switch to this if we need to. Hopefully we don't need temperature data past 2016!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Awesome, thanks! I will make it a priority once we have reviewed data to figure out sample date years so we can decide next steps.

**Comment by lizzieinvancouver** [comment]
@cchambe12 @AileneKane 
I just took a quick look at the new data and almost all the field sample dates are in 2016 or before. The latest is in January 2017 ... (Prevey & Harrington 2018 ... they took most of their cuttings in 2016 though, it looks like), it's on _Alnus rubra_, which is super cool, but it's also on effective chilling temperatures, also cool (but just one cue) so I think we should go with the 2016 climate data. I will email you both to see if we can discuss sometime.

**Comment by lizzieinvancouver** [comment]
Looks like Livneh data is 4X higher spatial resolution than what we're switching to now (and to E-OBS) so that explains the slowness compared to E-OBS I imagine. 

@cchambe12 Thanks for taking a first stab at this! Goal is to edit pullclimate_nam.R to now run off the Princeton Global Forcing dataset. Me and @AileneKane @MoralesCastilla stand at the ready to help.

**Comment by cchambe12** [comment]
@cchambe12 fix fieldsample.date issues in clean_misc.R - just move code from chilling/fieldchillcalc_latlong.R

**Comment by cchambe12** [comment]
This is very close! Currently *seems* to work on the new data but I still need to download all of the climate files to check on the older data in ospree. Unsure how long the code will take with the entire dataset but the code seems elegant and *possibly* faster than using the raster package - nice work @AileneKane!

**Comment by AileneKane** [comment]
Thanks @cchambe12! I'm so glad it seems to be working for you.

**Comment by lizzieinvancouver** [comment]
@AileneKane Would you be willing to take a first look and then pass to me? I would like the chance to review it (so I can learn!) but am not sure I will be good at catching things so could use an extra set of eyes ....

Cat, did we do the below yet? Or can I help do it? (Just trying to keep track of things.)

> @cchambe12 fix fieldsample.date issues in clean_misc.R - just move code from chilling/fieldchillcalc_latlong.R

**Comment by AileneKane** [comment]
@lizzieinvancouver  @cchambe12 I will do this by Friday!

**Comment by cchambe12** [comment]
@lizzieinvancouver yes I moved everything over to clean_misc.R and thanks @AileneKane for checking it out!

**Comment by AileneKane** [comment]
@cchambe12 I am not done checking the climate/chilling code yet but I do have some questions for you:

1. 5 of the new studies are missing from the new climate pulling code. These are:

- fu19 and richiardso18 (missing because no field sample date- can we add this? have these been checked?)

- anzanello16- missing becuase its brazil- do we want to add this, since we have global data in the new climate dataset? (though some of the earlier experiments could be added then to- I'm not sure if we want to open this can of worms)

- ramos17- could not figure out why its missing- do you have any idea?


2. I think we will need to add the "addtoexpwarm" column which is not currently active, correct? Is this intentional? I think this will be necessary to convert all the "ambient plus XX" studies, of which there are at least a couple, to usable climate data.

**Comment by cchambe12** [comment]
@AileneKane 
1) 
- richardson18 is an open-top-chamber study so there aren't any cuttings or anything so I'm not sure how to deal with this one...
- Looks like I can add a field sample date for Fu19, I'll dive into this paper more though to make sure
- Not sure how to deal with anzanello18 or where to get that climate data from @lizzieinvancouver @MoralesCastilla any ideas or thoughts on this one?
- ramos17 probably wasn't added because it looks painful! I'll work on this too

2. I actually don't know where this is so this was not intentional from my end! I think we do have a handful of studies that have ambient plus XX so I'd say we should add this back in.

Thanks!

**Comment by AileneKane** [comment]
@cchambe12 
for 1. I'm not sure that we WANT to add the anzanello studies- they are from south america, which I thought was included in the global princeton database we are now using for north america- i thought it might be an opportunity to add south america if we want to.

 for 2.  the column is added in fieldchillcalc_latlong.R, with the new studies (and old ones are commented out so I think it is not working for the old studies either). The new studies that would require this, beause they use "ambient + XX" are  nanninga17, ramos 17, richardson18, prevey18

**Comment by lizzieinvancouver** [comment]
@cchambe12 It looks like you did comment out the two lines that deal with the two previous ambient studies 15 days ago ...

https://github.com/lizzieinvancouver/ospree/commit/d47e4fb2be7322ff5c9c0990d97a8a69d13e0e9c

**Comment by cchambe12** [comment]
@lizzieinvancouver hahah well great that makes it easier to fix. Thanks Lizzie!

**Comment by AileneKane** [comment]
@cchambe12 i found a few more coding errors in pullcimate_nam.R:

Lines 51-54 did not work for me. Are you using the daily data from the link above? If so, I had to change "tmax" to be "tmax_daily_" and "tmin" to "tmin_daily_" for it to work. 

Also, in line 54, to generate tminprev, you currently call on tmax rather than tmin. I didn't push my updates to the code in case you are using a different climate file that names them differently. Please let me know if you are (we should also update ospree/notes/dailyclimatedata.txt with this information)

**Comment by AileneKane** [comment]
@cchambe12 I'm actually having problems with the netCDF files from http://hydrology.princeton.edu/data/pgf/v3/0.25deg/  my computer is not able to read them for some reason, so I may not be able to fully check your code.

**Comment by cchambe12** [comment]
@AileneKane I will check on these things more deeply on Monday but nice check with line 54! Otherwise, I changed the file names, which isn't necessary it just made more sense to me. As for the download, I can email them to you on Monday if that helps.

**Comment by AileneKane** [comment]
@cchambe12 i have downloaded them all again and it seems to be working properly now. no need to email them to me but thank you! the last thing i wanted to do was just compare the temperature values obtained from each source to check that they are correlated. i'll let you know if i noticed anything strange but other than that your code looks ok!

**Comment by cchambe12** [comment]
@AileneKane Awesome! Thanks for checking on this and for all of your help so far!

**Comment by AileneKane** [comment]
@cchambe12 I have looked at this a bit more and other than what i noted above, i think it looks good! The new climate data yields chilling and forcetemps that are correlated, though certainly not identical to the old data. Here is a plot if you're interested
[oldnewclimplot.pdf](https://github.com/lizzieinvancouver/ospree/files/3602239/oldnewclimplot.pdf)

**Comment by cchambe12** [comment]
@AileneKane Awesome thanks for making the plots! Cool, I think I have addressed all of the above. Thanks again for all of your help.

**Comment by cchambe12** [comment]
I am working on cleaning chilling/clean_chilltemp.R

For now, it looks like ramos17 is not working is due to the missing year. Can we fill this in? @DeirdreLoughnan @lizzieinvancouver

**Comment by lizzieinvancouver** [comment]
@cchambe12 Sorry about this! I think @DeirdreLoughnan added the field sample date but not the year. I will fix this now.

**Comment by DeirdreLoughnan** [comment]
@cchambe12 @lizzieinvancouver  Sorry, I can also fix it this afternoon if you are traveling Lizzie.

**Comment by lizzieinvancouver** [comment]
@cchambe12 If you pull, I think it is fixed. Let me know if not! And thanks for catching this. @DeirdreLoughnan It was an easy fix, so all set, but thanks!

**Comment by cchambe12** [comment]
All set thank you both!

**Comment by cchambe12** [comment]
@AileneKane I am rerunning the chilling code and it seems like I'm missing some chilling estimates for a handful of European studies. One example is the ramos17, it now has fieldsample.date, provenance latitude and longitude information and year but still doesn't have chilling, is there another requirement to have chilling calculated? I think it may be related to chilltemp being NA but for those studies there aren't even field calculations. 

And just to triple check, I should be using E-OBS v16 correct? Thanks!!

**Comment by cchambe12** [comment]
All set!! Issues are resolved and chilling should be updated.
