### ISSUE TITLE
figure out if we can convert Biasi chill units

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#302]
Email the corresponding author in case we can convert to days of chilling ... otherwise the entered data won't be much use (see also issue #294 for a sample email).

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver  I sent an email and can follow up in a week if I do not hear back.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Nice! We can given them two weeks seeing as it's summer.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan I think we can add a note about whether you heard back and close this?

**Comment by DeirdreLoughnan** [comment]
I did not receive a reply to my follow up email two weeks later (August 5) and could get the data needed to convert the days of chilling.
