### ISSUE TITLE
move forward with repo, introducing bbculdesac branch

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#303]
See also #300 ...
We need to think of branching the repo so we can maintain code for the manuscripts but work on adding new papers which will take some effort.

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver how does one "Create a .gitignore file that ignores all .RData and all .DS_Store files"?

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi Good question! As a start, can you let us know what online resources you have looked at that look most promising and what part you're first confused on (totally okay if it's very early in the process, but it would help to know what resources you're using to get started)? 

Also, let's keep our questions open to the the whole lab group .... it's not just me (hopefully) who may know the answer to these questions.

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi I guess no one is jumping at gitignore excitement so much on a Monday, so let me know if this helps ....
[This tutorial](https://coursework.vschool.io/create-a-gitignore/) has some good info, though I personally would use `nano` instead of `vim` ... (more info on [setting up your text editor](https://github.com/temporalecologylab/labgit/wiki/helpful-unix-stuff))

**Comment by lizzieinvancouver** [comment]
@AileneKane raised a good point about things like edits to the bib files that we may want in both master and bbculdesac, I think [we use git cherry-pick](https://git-scm.com/docs/git-cherry-pick)

**Comment by DeirdreLoughnan** [comment]
Here are the links I found useful when [creating a repo in terminal](https://help.github.com/en/articles/adding-an-existing-project-to-github-using-the-command-line) and for [editing text files with nano](https://askubuntu.com/questions/54221/how-to-edit-files-in-a-terminal-with-nano)
