### ISSUE TITLE
new respvar.simple for days to budburst NOT since forcing

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#305]
@cchambe12 @dbuona @AileneKane .... I don't think we had a respvar.simple for daystobudburst NOT since forcing conditions, did we? Does this just get handled in bb analyses when we add ambient forcing in such? 

Help! Can someone remind me?

Depending on the answer do we perhaps want a new respvar.simple type?

**Comment by cchambe12** [comment]
@lizzieinvancouver I agree, I think this was cleaned in bb_analysis/cleaning/clean_respvarmore.R. 

I vaguely remember a 'dayofyeartobudburst'... but I'm not sure if that was a respvar.simple option or a respvar option.

**Comment by lizzieinvancouver** [comment]
We talked about this and decided just to do what we did before -- deal with it later (e.g., in bb cleaning).
