### ISSUE TITLE
How do intxns work?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#307]
@AileneKane @MoralesCastilla @cchambe12 @dbuona 

[Here's the code](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/nonlinearities_intxns.R) I wrote to look at how interactions work ... 

We generally discuss main effects of forcing, photoperiod and chilling that are negative (earlier days to budburst with greater forcing or chilling and/or longer daylength) and interactions that are positive ... somehow I thought this might lead to non-linear effect of increased forcing where at higher forcing you see less of an advance. But I don't easily see it. Am I:

1. Thinking about this wrong? (I think so ... but how exactly?)
2. Have a coding error (I don't think so, but do check)?

And, what is required to get the response I expected? Any and all help welcome ... perhaps for safety (avoid merge conflicts), if you edit the code just push a new version with your initials at the end. 

Thanks!

**Comment by AileneKane** [comment]
@lizzieinvancouver I think it may just be a matter of the magnitude of the interaction, compared to the magnitude of the main effects (if the interaction is super small you will not see the expected effect). I modified your code a bit to show this [here](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/nonlinearities_intxns_AE.R) and made a couple of figures [here](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/figures/intxnsims_allintsAE.pdf) and [here] (https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/figures/intxnsims_onlyfpAE.pdf)

**Comment by lizzieinvancouver** [comment]
@AileneKane This is super helpful and it seems like when the intxn is 5-10% of the main effect we see it more (maybe we want some of this in a paper ... by we should check if it mathematically works across other numbers). It also looks like the subadditive effects do work the way I think. I need to check more. For now I updated the code so all of it is in one place, in case others want to work on it. Thanks again!

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver Will make a 4 (or 8? or whatever) panel plot showing what Ailene showed across:
- F increases, P, C constant
- F increases, P decreases, C constant
- F increases, P constant, C decreases
- F increases, P and C both decrease

Maybe we should also see what outcomes look like given sigmoidal responses (similar to threshold)?

**Comment by lizzieinvancouver** [comment]
@cchambe12 @AileneKane @dbuona @MoralesCastilla  I did the suggested plots ... please check out commit 1b2c7bbcdec1f3d85df31408ec95a17654b97db8 and/or analyses/limitingcues/figures/intxnsims_changingFP.pdf and analyses/limitingcues/figures/intxnsims_changingFC.pdf

My takehome is that interactions do NOT cause non-linearities, they only cause them alongside multiple cues also shifting (i.e., forcing increases and chilling decreases)

**Comment by lizzieinvancouver** [comment]
Yes! I am right as of December 2019 ... we have some useful code in limitingcues/nonlinearities_intxns.R and nonlinearities_more.R.
