### ISSUE TITLE
vitra17 thermal time

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#309]
See also issue #304 

@DeirdreLoughnan If you read Vitra17 "The method is well known and is used in studies that aim to determine the date of dormancy break (Dantec et al., 2014) or to assess the rela- tionship between chilling and forcing temperatures (Laube et al., 2014)." It sounds like perhaps the method to calculate thermal time in those papers. Could you check Dantec and Laube and if they use the same method, put it here so I can update the data?

Laube J, Sparks TH, Estrella N, H€ofler J, Ankerst DP, Menzel A. 2014. Chilling outweighs photoperiod in preventing precocious spring development. Global Change Biology 20: 170–182.

Dantec CF, Vitasse Y, Bonhomme M, Louvet J-M, Kremer A, Delzon S. 2014.
Chilling and heat requirements for leaf unfolding in European beech and sessile oak populations at the southern limit of their distribution range. International Journal of Biometeorology 58: 1853–1864.

Thanks!

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver 
Dantec et al (2014) use two methods for calculating heat accumulation, and found the best method to be the sum of a function of the temperatures starting at a base threshold of 0C up to the temperature minus the base temperature (eqn 2). I may be misinterpreting the equation, however.   

Laude et al (2014) calculate the total absolute amount of forcing as the sum of degree days both from the field and the chambers starting January 1st, with a base temperature of 0C. They cite Heide (1993), who defines thermal time as the total day degrees over 0C, and Basler & Korner (2012) (who in turn cites Heide (1993)).

**Comment by lizzieinvancouver** [comment]
We will try GDD with base 0 and see if it makes sense ...

**Comment by lizzieinvancouver** [comment]
@dbuona Will take over because Lizzie is making no progress. Try GDD model with 0 as base temp, see if it makes sense.

**Comment by dbuona** [comment]
@lizzieinvancouver @DeirdreLoughnan If I understood this task correctly, I was supposed to assume this paper used GDD model with basetemp 0 and then back out the calculations to see if the time to budburst seemed reasonable. I did that for their Fagus and Prunus entries.

The Fagus twigs cut in Feb burst bud in 26 day and the ones cut in April 9.5 days. May cutting  burst bud in 2.5 or 0 days.
Prunus days to bb in April were  ~3.

These values seem intuitively pretty low, but actually comparable  to values for twigs in April from gianfagna85 and calme94 and cook00b. Not sure if this give us any kind of authoritative answer...

**Comment by lizzieinvancouver** [comment]
@dbuona Thanks! I believe you understood it correctly. Perhaps best now just to contact Vitra and Yann (one email) and see if one can respond that these values and/or our method is correct. If we don't hear I think we should go forward with these values -- so let's add your work to the code flow for now so we can include Vitra in analyses.

**Comment by cchambe12** [comment]
@cchambe12 check Dan's code!

**Comment by DeirdreLoughnan** [comment]
Vitasse replied to my inquiry into their methods with the following explanation:

"Typically for temperate trees a GDD with a base temperature of 5°C is used. In this paper because the samples were put in transparent climate chambers setup at 20°C it does not matter whether we used 5 or 0°C threshold as temperature remained constant around 20°C. So here we used growing degree days by accumulating the daily average temperature (which should be around 20°C each day)." 

A follow up email was sent on November 13 to confirm the base temperature used.

**Comment by lizzieinvancouver** [comment]
I saw the follow-up, where Yann said he did not know. Let's move forward with 0 ... and then not close this until we hear back (or if we don't, we should discuss what to do).

**Comment by lizzieinvancouver** [comment]
@dbuona Will try 5C base temp and see how different estimates are...

**Comment by dbuona** [comment]
We couldn't decide if it was 5 or 0 degrees for the GDD model. They are fairly similar with maximum difference of 9 days so we split the  difference with a 2.5 base temperature. Now we know its wrong but can be no more than 4.5 days from the true value.
