### ISSUE TITLE
prevey18: What to do about temperature treatments

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#312]
This paper is confusing!

> Temperature conditions averaged 4 ◦C in the colder growth chamber, and 9 ◦C in the warmer growth chamber (Fig. 1). Ambient conditions in the lathhouse and at Webster Nursery averaged 4.4 ◦C, and 4.3 ◦C, respectively, from November 2nd 2016–January 31st 3017, and there were multiple freezing events (Fig. 1).

**Comment by lizzieinvancouver** [comment]
> I think chilling conditions are: We placed one cutting from each sampled tree (ten cuttings per treatment in total) in one of three different experimental treatments. The three treatments were: 4 ◦C: a 4 ◦C temperature regime in a growth chamber starting on November 2nd 2016, 9 ◦C:
> a 9 ◦C temperature regime in a growth chamber starting on November 2nd 2016, and ambient/greenhouse: ambient temperatures in a lathhouse starting on November 2nd 2016 (Table 1). We also had an ambient treatment where cuttings remained in a lathhouse over winter and spring. 
> 
> On January 31st 2017, cuttings from the 4 ◦C, 9 ◦C, ambient/greenhouse, and Webster/greenhouse treatments were moved to a greenhouse with a variable temperature that averaged 16 ◦C to simulate forcing conditions. Temperature regimes for treatments were accomplished with a combination of growth chambers, ambient conditions in a lathhouse, and forcing conditions in a greenhouse. 
> 
> Then forcing is:

**Comment by lizzieinvancouver** [comment]
I think this written rather confusing but Fig 1 shows the actual temperature regimes I believe. Do we want to take the means, which they give (and which we have entered), or try to extract ambient ourselves or what?

Sidenote: Photoperiod was always ambient I believe. "Photoperiods in growth chambers were set to match ambient photoperiods."

**Comment by lizzieinvancouver** [comment]
@dbuona (@lizzieinvancouver can help) ...

- 'ambient' for lathouse/Webster nursery conditions
- 16 C in forcing
- 4 and 9 for growth chamber chilling
- Adjust field sample date for when plants went into forcing conditions

**Comment by dbuona** [comment]
done in clean_misc.R

**Comment by dbuona** [comment]
@cchambe12 check dan's code at bottom of clean_misc.R and close issue if its okay

**Comment by cchambe12** [comment]
@dbuona all checked and looks good! I'm going to close this now
