### ISSUE TITLE
Fit new ospree bb model with continent (for response to reviewers)

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#314]

**Comment by AileneKane** [comment]
Because we only have chilling for NA and Europe options are continent a fixed effect or a model of bb ~ photo + force with continent on the intercept (latter seems better to Lizzie, include just in supp).

**Comment by AileneKane** [comment]
the models with continent are difficult...I'm having trouble interpretting the results. I've tried a few different random effects structures, to compare (using rstanarm across these different structures). here is a model with only the interecpt on species (6 species are consistent across north america and eurpope)
![image](https://user-images.githubusercontent.com/9097640/69188467-7411fd00-0ad1-11ea-8abb-44adfca4ce94.png)

**Comment by AileneKane** [comment]
a different model structure: with no interactions, but allowing species differences for all fixed effects:
![image](https://user-images.githubusercontent.com/9097640/69188686-dd920b80-0ad1-11ea-85bd-2ab184477be6.png)

**Comment by AileneKane** [comment]
They both (and all the other iterations I've tried) look weird, I think because the species on both continents are few and some are oddballs (e.g., Fraxinus had positive forcing in the main bb model)  The species are: "Picea_abies"           "Quercus_rubra"         "Acer_saccharum"       
 "Pseudotsuga_menziesii" "Acer_complex"          "Fraxinus_complex"

**Comment by lizzieinvancouver** [comment]
Did as best possible (also occurred to me after the fact we could pull the species estimates from each continent and compare those! Not great, but okay approach too...).
