### ISSUE TITLE
Summarize sliding windows results and add to supplement

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#317]
Reviewer 1 asked about the sliding windows approach from the Simmonds et al paper so we want to look into how this affects our simulation work in the supplement. Simmonds et al  used R package climwin and claim all code and data are at: https:// github.com/emilygsimmonds/Cue_Identification .

**Comment by cchambe12** [comment]
Okay so I reran the sliding window using the BETPEN PEP data.

The output from these results: (using May 31st as a reference day for the window)
## Pre CC SWA results
#   WindowOpen WindowClose  Variable     Int         EST           SE               R2
#1        -22          52                       1       157.0947   -5.50605    0.262991    0.4934151

## Post CC SWA results
#   WindowOpen WindowClose Variable   Int            EST              SE                     R2
#1        -34          22                     1         126.703   -3.588456    0.2071495    0.3998027

Compared to Lizzie's calculations:
#cc               meanbb     varbb      sdbb       meanclim   varclim   sdclim climslope   climslopese
#1 post       106.3356  45.47136  6.510241 14.49351  1.391118 1.110196 -2.048819  2.111988
#2  pre       113.8089 132.02667 11.087655 10.81471 10.969837 2.826528 -2.683118  1.468094


I have an updated script in bbculdesac: analyses/bb_analysis/pep_sims/simmonds_slidingwin/sw_simmonds.R

My overall takeaway is that the standard error is much closer using the simmond sliding window approach but we cannot evaluate variance. That said, the intercepts are very high!

**Comment by cchambe12** [comment]
@cchambe12 check out what mean temperature is within the window. Needs to have gone up!

**Comment by AileneKane** [comment]
@cchambe12 Could you make a tale with these results and write a few sentences summarizing the methods? These can then be added to the supplemental methods into a new section that I have currently entitled "Applying the shifting windows approach to Central European data"

**Comment by cchambe12** [comment]
@lizzieinvancouver @AileneKane So mean temperature for post cc is lower within the window than for pre cc... I'm not sure what our next steps should be with this information. 

Mean Temp PreCC: 7.86 degC
Mean Temp PostCC: 5.68 degC

And the slope and intercept are in days/degC. 

I will work on the table and write-up now so we have it and we can discuss more how we want to deal with the temperature information.

**Comment by cchambe12** [comment]
@AileneKane I finished and pushed the table and write up for the sliding window. I was unable to compile the .Rnw though so please let me know if the table looks wonky or needs to be fixed!!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Awesome work! I think we're close, we just need some credible intervals ... the issue here is to divide out that temperature so (please check my work!)  ...

```
> -5.50605/7.86
[1] -0.7005153
> # post-cc
> -3.588456/5.68
[1] -0.6317704
```
Are the equivalent estimates per equal thermal-day ... they look pretty similar so we probably need to add uncertainty estimates around them to see how similar they are.

**Comment by cchambe12** [comment]
@lizzieinvancouver Ahhh okay... apologies for struggling through this but if I have the mean temperature across the window that will be in °C. If the model is in days/°C and we take the slope (in days/°C) and divide it by temperature (°C) then won't our units be days/(°C)^2? Your answers look correct but I'm struggling to figure it out! 

Anyways, if this is correct, then would I just divide the calculated standard error from the SE from the model output to find our credible intervals? Thanks!!

**Comment by lizzieinvancouver** [comment]
@cchambe12 @AileneKane Yes, someone should think harder on this (maybe not me right now, as I am getting really tired). But I guess I was thinking it's days per C but then we need to correct for the thermal sum of each day ... so I guess I was thinking one is  -5.5 days per C per 7.86 degree C day and one is -3.6 per 5.7 C day but maybe the correct is multiplying or such? If you multiplied them then the pre-cc would be 2X bigger than post-cc. But I don't know what is right just now or how to interpret these windows ....

**Comment by AileneKane** [comment]
@lizzieinvancouver @cchambe12 If I am  understanding this correctly, we just need to get both sliding windows estimates to have the same denominator. If we choose the pre-waming degree day deonominator (7.86C) then that would by (-3.6*7.86)/5.7 = -4.96 per 7.86 degree C day. IS it possible to use confint() on the models you get from this analysis?

**Comment by AileneKane** [comment]
@lizzieinvancouver @cchambe12 Also, the variance in bb declines a long from pre to post cc. Was this true with the non slidding windows approach too?

Thank you for all your work on this!

**Comment by cchambe12** [comment]
@AileneKane Yes! Variance declined from pre to post cc in the sims and the PEP data. 

As for the sensitivity: when we were using Lizzie's method the model was bbday~dailytemp and we calculated sensitivity difference by taking the slope from the post CC data and subtracting it from the pre CC slope, can't we apply the same method here? 

confint() PreCC:
`2.5 %     97.5 %
#(Intercept) 152.960357 161.229140
#climate      -6.022899  -4.989201`

confint() PostCC:
`#                2.5 %     97.5 %
#(Intercept) 124.322906 129.083060
#climate      -3.995561  -3.181351`

**Comment by lizzieinvancouver** [comment]
@AileneKane @cchambe12 Thank you guys! I could not see through the math ... but it looks like the estimates are the same again. If you use Ailene's approach and compare pre-cc range of -6.0 to -5.0 and then do the below math to get post-cc, it's -5.5 to -4.3, so they overlap.

```
> (-3.995561*7.86)/5.7
[1] -5.509668
> (-3.181351*7.86)/5.7
[1] -4.386916
```
And I totally think we should write a short note on this and send it around the journals! Something to discuss next week....

**Comment by AileneKane** [comment]
@cchambe12 Thanks so much for adding the standardized slopes to the SWA table- could you add in paranetheses, the  95 percent uncertainty intervals?

Also, the "results_swapre_mayref.csv" and "results_swapost_mayref.csv" files do not appear to have been pushed so that part of the code does not run. Could you push those files?

**Comment by cchambe12** [comment]
@AileneKane I've updated the files and code! But the standardized slopes are going to be the same for both correct? Just the intervals should change slightly?

**Comment by AileneKane** [comment]
@cchambe12 thank you! i fixed the code just now- you had accdentally referenced post code instead of pre code in one location.

**Comment by AileneKane** [comment]
@cchambe12 actually, you don't seem to have divided by temperature, which i think was the point. i am correcting this

**Comment by cchambe12** [comment]
@AileneKane Thank you!!

**Comment by lizzieinvancouver** [comment]
Thank you @AileneKane @cchambe12 !
