### ISSUE TITLE
fit main bb mod without zohner16 to see how it affects estimates

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#319]
![image](https://user-images.githubusercontent.com/9097640/68976619-0a30e500-07ab-11ea-851c-6b180232cbd1.png)

**Comment by AileneKane** [comment]
n_sp=30

**Comment by AileneKane** [comment]
this is now added to the supplement for the main bb ms

**Comment by lizzieinvancouver** [comment]
@AileneKane Awesome! looks great ... and interesting that chilling effect goes up and photoperiod goes down ... suggests to me part of difference could be that we don't treat chilling as a factor as zohner did.

**Comment by AileneKane** [comment]
I think this is all set so I'm closing it
