### ISSUE TITLE
okie uh-oh

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#320]
see also #2 and #310 ...

So, if you look at okie, you see this in the figure cell: 

"fig3 --   data are % budbreak ~ day, see okie11 tab for all data"

I entered the data ... I have 576 rows of data that look like maybe they never got added. I will upload the file now and we should discuss what to do.

**Comment by lizzieinvancouver** [comment]
Actually, it's already there 00 see input/okie11tab.csv ... I think we just never merged it in?

**Comment by legault** [comment]
okie11 data added

**Comment by lizzieinvancouver** [comment]
@legault Can you add a readme to okie_cleaning folder for how okie was merged? i.e. ... around XX date, Geoff L. added okie to the ospree... file like this. We want to add dantec in the same way... Thank you!

**Comment by legault** [comment]
Sure thing. Is there a previous example of how this has been added/handled for other data sets?

**Comment by lizzieinvancouver** [comment]
@legault Thanks! And yes, Dan has an example: analyses/cleaning/zohner_cleaning/zohnercleaning_README.txt 
This was maybe not the best way to add the data, but it is pretty clear (to me at least) what happened and how the data was added, which is the most critical bit.

**Comment by legault** [comment]
README added.
