### ISSUE TITLE
check dantec14

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#322]
From issue #310:

> There is no reference to the figure in ospree but I am assuming it is figure 3b.
> It is similar to Ramos in that there is no response time in the figure, rather it is percent budburst from different durations of chilling. That said, figure 3a, has growing degree days~chilling, so I'm not totally sure why we didn't capture those data originally as well.

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi @FaithJones @md-garner Will enter these data, add to current data on this file.

**Comment by DarwinSodhi** [comment]
I just checked @md-garner Data and it looks good to go!

**Comment by DarwinSodhi** [comment]
I just checked @FaithJones 's Data and it looks good to go!

**Comment by lizzieinvancouver** [comment]
@md-garner Flash back to last year! Let's talk about this today as I am confused by the dantec14 data still:
1. There is variable chill (in chill units) but no variable field sample date or experimental chill, so how is that possible?
1. We should add the figure we scraped from, if we know it.
1. I just wanted to check where we put notes on how we did this.

**Comment by lizzieinvancouver** [comment]
@md-garner 
* Figure out where data Faith and Mira scraped went!
* Check field sample date for both experiments (leaf unfolding versus dormancy) -- if we do not know the exact field sample date (

> e.g., they say At intervals of about 2 weeks, from mid- October 2010 until mid-April 2011, twigs containing numerous buds were sampled from each selected tree in each population, at height of about 10 m, with a pole pruner (or from higher up, with a shotgun)

We should enter the full range possible 
* Figure out which figure data came from make sure all accurately entered (clean_misc.R)
* Make sure chilling data are included if applicable, with a note on how they are calculated

And then I sort of think we should consider a good way to make sure these data are deleted from any further analysis we do because we may not know the dates of sampling well enough ...

**Comment by md-garner** [comment]
I found Faith and my data from October ([ospree/data/Dantec14add](https://github.com/lizzieinvancouver/ospree/tree/master/data/Dantec14add)) but the problems with the original data were carried over to these datasets. 

 Can I change the .xlsx files since they are not yet added to the ospree database?

**Comment by lizzieinvancouver** [comment]
@md-garner We only change the xlsx when it's a major pain to do code the change; is that the case here? 

Side note: Why is there a PDF in the folder? It should be deleted and double-check it's in the proper place on google drive.

**Comment by lizzieinvancouver** [comment]
@md-garner To discuss! Remind me about this at the end of the meeting Thursday if you can.

**Comment by lizzieinvancouver** [comment]
@md-garner I worked on this! I think you follow what Geoff did for okie11, see ospree/analyses/cleaning/okie_cleaning/okiecleaning_README.txt ... so, get it all formatted, then merge it in in clean_addata.R. 

At this point, since the data is now on git and in xlsx I think the best approach is to do all fixes in R, not just change things in the xlsx files ... though tempting, we end up with effectively no record of it since we cannot monitor changes in Excel files via version control.

**Comment by md-garner** [comment]
@lizzieinvancouver It should hopefully be finished! It's in a couple pieces now:

1. There's a [ospree/analyses/cleaning/dantec_cleaning](https://github.com/lizzieinvancouver/ospree/tree/master/analyses/cleaning/dantec_cleaning) folder with a readme explaining what I've done with all of the dantec14 data and the cleaning script for the new dantec14 data.
2. The new cleaned dataset is [analyses/input](https://github.com/lizzieinvancouver/ospree/tree/master/analyses/input) for merging
3. I updated [clean_addata.R](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/cleaning/clean_addata.R) to include the new dantec data
4. I updated [clean_misc.R](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/cleaning/clean_misc.R) to clean the dantec data from Dan Flynn that is already in ospree

**Comment by lizzieinvancouver** [comment]
Finally checked this briefly and looks good. The main error I found was broader -- we have wonky numbers in our main cleaning file and README. Updated those in commit ebee289457416aff7cbc455f4ac4e38f7063ee10
