### ISSUE TITLE
Run the models without pooling ...

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#345]
@MoralesCastilla Can I ask you to run two more models and see how they compare in R2 and LOO? Could you run (1) eqns 1 and 2 (from your outline) but WITH phylogeny and WITHOUT spp on the intercept (aka eqns 3-4 but drop spp on the intercept)? What I think is an issue here is that *both* partial pooling and phylogeny correct for the non-independence of species, and I think we should show that without partial pooling you do get an improvement from phylogeny.

**Comment by MoralesCastilla** [comment]
I have only checked the model coefficients so far and they seem. Still need to check phylosignals and accuracies (R2s and LOOs)

The estimates of the effects of each cue, remain qualitatively similar for eq 1, but do not converge for eq 2

- Model eq 1 - Forcing (-6.65) ; Chilling (-5.33) ; Photo (-0.95) - none overlaps with zero

- Model eq 2 - it does not converge // crashes

**Comment by lizzieinvancouver** [comment]
We switched to a PMM model and no longer need this (I believe). @MoralesCastilla re-open if you disagree.
