### ISSUE TITLE
phenology  and ranges lit review

### ISSUE THREAD

**Issue by dbuona** [lizzieinvancouver/ospree#346]

**Comment by dbuona** [comment]
Hi Everyone,
I have started putting together a lit review for the role the relationships between species' phenology, cues, and ranges. The good and bad news is it seems like pretty slim pickin's as far as thinking about how phenological cues are related the the environment of a species range. I've pulled about 15 papers so far (that may not even be very useful), but we probably need more. So here's what would help

2-3 people to help me go through the papers I've already found to see if there is anything useful within.

1-2 people to keep searching the literature to see if you can find anything better.

I have added all the papers I found, plus the search terms I've already tried to a sub folder "Range Papers" in the  "OSPREE Papers" folder on the lab google drive.

Once people volunteer, I can make a new spread sheet about dividing up the papers more concretely.

Thanks for you help!
Best,
Dan

**Comment by cchambe12** [comment]
@dbuona I'm happy to go through the first four papers to start!

Osada2018
Morin2008
Liang2019
Kramer2017

And then I'm happy to do another search and see if I can find anything else you may have missed.

**Comment by DarwinSodhi** [comment]
@dbuona 

I can do: 

Brown et al 2016
Chuine et al 1999
Chunie 2010
Clark et al 2014

**Comment by DeirdreLoughnan** [comment]
@dbuona 

I can also review the papers you found and do:

Muffler et al. (Distribution ranges and spring phenology...)
Doi et al 2008
Ford 2001
Guilbault 2012

**Comment by dbuona** [comment]
@DarwinSodhi @cchambe12 @DeirdreLoughnan Thanks yall. I will make some sort of spread sheet to track things and push it to git hub later today

**Comment by dbuona** [comment]
said spread sheet is in ospree/analyeses/ranges/lit_review_ranges.csv

**Comment by DarwinSodhi** [comment]
@dbuona it would be helpful for procrastinators like myself to have a firm deadline when this needs to be done!

**Comment by dbuona** [comment]
@DarwinSodhi @cchambe12 @DeirdreLoughnan As for a deadline is Friday March 6 reasonable?

**Comment by FaithJones** [comment]
I cant find the right google folder. The only one that might be it is the Wolkovich general Lab folder, but I dont see any OSPREE stuff there. Could someone share it with me please?

**Comment by lizzieinvancouver** [comment]
@dbuona The paper Ally Phillimore suggested mentions 'northern species' responding one way in the abstract, maybe worth a skim? https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.12896

@FaithJones In case no one has yet I will email you the link now!

**Comment by DarwinSodhi** [comment]
@dbuona I added my comments on the CSV!

**Comment by lizzieinvancouver** [comment]
@dbuona Can you update us on this issue this week?

**Comment by dbuona** [comment]
first pass of lit review is now over.  It wasn't super helpful, but the info is here:
 ospree/analyeses/ranges/lit_review_ranges.csv
