### ISSUE TITLE
Check n and error in ospree bb papers

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#350]
Instructions for Getting n and error for OSPREE papers
1)	To see what papers you are assigned to check, see [need.n.errorcheck.csv](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/output/need.n.errorcheck.csv) (the “person_checking” column)
2)	The goals are:
a.	to get n (per group/treatment) as well as the number of groups/treatments, if that’s possible without scraping. 
b.	To know if it is possible to get some measure of error/variation (i.e. via scaping) or not. I am not asking you to actually scrape any papers (YET)- just say if we would need to scrape to get the error. We will decide if scraping is necessary/useful at some point.
c.	This will allow us to: report the total sample size as well as the sample size per group, and to simulate data, if necessary, to examine the effect of study-level error on our model estimates. 
3)	Your assigned papers can be found on the [google drive](https://drive.google.com/drive/folders/0B8nEumYJJb_4Y2lKRjRDd0piOWc)
4)	First, check the “To Do” column- some papers have already been done or partially done by you. For some, we only need to know the number of treatments/groups or more information about whether the n is per group or treatment or ??
5)	Columns 2-7 (B-G) are currently in ospree. You do not need to add anything to these columns. Please add the information you find to columns 8-14 (H-N; for "error.type to "To Do"). Write “Done” in Column 14 ("To Do") when you have finished your task. I suggest creating a personal copy of need.n.errorcheck.csv on your computer to use as you complete the work. Then, when you’ve completed everything, add all the studies at once to the copy on Git and commit/push to avoid merge conflicts.
6)	Please do this by March 30 (we each now have only 4-5 papers!)

**Comment by AileneKane** [comment]
We may need to revisit this- I want to make sure that what we're getting is the error and sample size associated with each scraped data point in OSPREE (that is how to make this most useful).

**Comment by AileneKane** [comment]
UPDATE: Please add the n, error, and error type (SD, SE, VAR, etc) to OSPREE, IF these can be gathered without scraping,  in the following script:  analyses/bb_analysis/cleaning/clean_addnanderror.R
I have also added a new column to need.n.errorcheck.csv to verify that you've done this additional step.  
(So far, I'm finding n is possible, SE is not without scraping)

**Comment by cchambe12** [comment]
@AileneKane None of my papers reported error!! I'd be happy to check out more papers if you need help with the rest.

**Comment by AileneKane** [comment]
@cchambe12 Ok! Thanks for checking them! Can you add sample size to analyses/bb_analysis/cleaning/clean_addnanderror.R for those that have sample size and need it entered?

**Comment by AileneKane** [comment]
Yay! this is done!
