### ISSUE TITLE
Make maps of min and max treatments of chill, force, photo

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#353]
To address comments about treatments varying spatially.

**Comment by MoralesCastilla** [comment]
@AileneKane 
Hi Ailene, should I extract the min and max values for each species and then plot them? I wonder if it would make sense to do this by studyID (I guess not). Let me know how do you prefer to proceed.

**Comment by AileneKane** [comment]
@MoralesCastilla it should be by unique location (growing lat/long) and species, i think, since we're mapping it. if you can use the symbols/colors to match particular species in the model, that would be great, but there are definitely some sites that we may want to just say "multiple spp"...Let me know if you have questions or want to talk anything through!

**Comment by AileneKane** [comment]
Thank you @MoralesCastilla these are beautiful!
