### ISSUE TITLE
Please check that I've added the slope/intercept covariance matrix correctly!

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#356]
The model is [here](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/bb_analysis/stan/nointer_2level_cov.stan)

**Comment by AileneKane** [comment]
@lizzieinvancouver i found it very challenging to add the covariance matrix to our model, the way it is currently coded- i think i did not do it correctly as the model had incredibly poor fit! I have not pushed the code, because i found myself basically replicating the map2stan code. 
Both map2stan and brms estimates were very simple for the model with centered predictors (see below). 
shall we include a table comparing these estimates, and include the correlation cov matrix (also below) in our response/the supp?
From what I've read online, this may not affect the estimates much when there are many groups: https://discourse.pymc.io/t/covariance-of-multiple-varying-coefficients-in-hierarchical-models/850
here is brms:
![image](https://user-images.githubusercontent.com/9097640/78103062-bd882800-73a0-11ea-8216-c2c5dc9ee4d2.png)
![image](https://user-images.githubusercontent.com/9097640/78103107-dabcf680-73a0-11ea-9909-686a00256ddb.png)

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver said I would try to vectorize code for fun, but I think we can close this issue.

**Comment by lizzieinvancouver** [comment]
I am going to admit that I will not get around to this soon and close it. Hopefully some other day!
