### ISSUE TITLE
Add info on joint models

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#357]
@legault Can you add notes on marginalizing over the joint distribution as a potential alternative approach to [here](https://github.com/lizzieinvancouver/ospree/tree/master/notes/jointlatentmodels)

**Comment by lizzieinvancouver** [comment]
Chatted with Mike B and I think our code is okay for this! We just need to give the code some more checks and maybe optimize it.

**Comment by legault** [comment]
Here's another way of thinking about error in the trait measurements:
https://mc-stan.org/docs/2_22/stan-users-guide/bayesian-measurement-error-model.html

Note that their version includes data on uncertainty in their measurement (see "tau" in their data block) which we may not have.

**Comment by lizzieinvancouver** [comment]
@legault Thanks! I think this could also be a good link if we ever want to try to integrate study-level error from OSPREE into our models.
