### ISSUE TITLE
work on anzanello18

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#360]
@md-garner Check on these issues and fix (maybe @AileneKane can hopefully suggest where in code to do changes, depending on what they are).

- What should the chilltemp and chilldays be entered as? You'll need to read the paper to check we didn't calculate the average temp here? (I tried but too complicated to figure out on quick glance.) We do this conversion in analyses/chilling/cleaning_chilltemp.R ... so if it is wrong work with @cchambe12  to fix it (once you are sure we need to).
- Check if other half of data should have field chilling. 

Good news though! Precocity is something weird (from the paper, "aximum budburst, precocity and uniformity data were estimated using a reparameterized Gompertz function (Fialho, 1999), as shown in Figure 1") so not what we want and thus we do not need to include Figure 4.

**Comment by lizzieinvancouver** [comment]
See also #355

**Comment by lizzieinvancouver** [comment]
@md-garner will add chilling info (probably in clean_misc.R), possibly back-convert chilling to chilldays and report back

**Comment by lizzieinvancouver** [comment]
Some notes for future me or future you (if you're reading this). The tricky bit about this study seems to be that they do NOT report the days to budburst after forcing started, so I am not sure we can use these data (we can still enter them).  

Here's what they do:

1. They take a ton of winegrape cuttings when dormant (don't be alarmed, it's in South America so the dates are fall, not spring)
1. They have two cutting dates (field sample)
1. The cuttings go into experimental chill treatments (three different types)
1. They take cuttings out ever 24-96 chill hour (a chill hour is any temp below 7.2 ... the treatments have varying chill hours per 24 hours: I. has 24 CH per day, II. has 12 CH per day and II has 18 CH per day) and put them in forcing (25 C)
1. Then they plot the data as max and min budburst across CH (CH here includes the experiment and the observational CH added on) ... but you can't seem to get days to budburst since forcing anywhere.

**Comment by lizzieinvancouver** [comment]
So ... we think the response.time data (chill hours) actually belongs in chilldays and we don't think we have response.time (as in OSPREE our response.time should be days since forcing applied).

**Comment by AileneKane** [comment]
@md-garner Do you want me to look at this? Or do you have questions about how/what changes to enter?

**Comment by md-garner** [comment]
@AileneKane @lizzieinvancouver I just added my code to cleaning_misc.R. One of you could check it and then I need to add into totalchillcalc.R, correct?

**Comment by lizzieinvancouver** [comment]
Thanks @md-garner, I will check this now. @AileneKane

**Comment by lizzieinvancouver** [comment]
Looks good!
