### ISSUE TITLE
correct man17 data

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#361]
see also #355

**Comment by lizzieinvancouver** [comment]
I think we can use the man17 data. Here's what I understand of their experiment that's especially relevant for how we enter data (but please re-read and check my work!): 
* They tell us their field sample dates in the text and in Figure 1.
* They tell us their forcing treatments: "the experiments were conducted in two computer-controlled walk-in climate chambers (i.e., two replications) set at 15◦C (day)/5◦C (night) and a 14-h photoperiod at 350 μmol m−2 s−1 photosynthetic photon flux density (PPFD)."
* In Figure 2 they show the budburst dates (I checked Supp Table 2 to confirm, the caption reads: "Parameter estimates for an exponential decay curve (a, b, and c) illustrating the relationship between chilling accumulation (cumulative weighted chilling hours) and heat requirement (cumulative growing degree hours >0 °C) for budburst in the 7 tree species examined.")
* We'll need to extract the CGDH from Figure 1 to translate Figure 2 into both sample dates and budburst dates.
* We should additionally extract their chilling hours in Figure 1 and thus convert the data extracted (only Figure 4 currently) into field sample dates. (Though we probably will end up just using our own chill calculations for current analyses.)

Extracting the data properly from this paper will take some effort, but it looks doable to me and so we should do it.
@cchambe12 and @dbuona Can you work with @DarwinSodhi who originally extracted these data to get these data extracted and properly entered. I strongly suggest reviewing the paper closely including the supp (see [here](https://www.frontiersin.org/articles/10.3389/fpls.2017.01354/full#supplementary-material)) as I think it has the conversion from sample date to chill hours already.

Let me know if I am missing anything that makes this not possible

**Comment by cchambe12** [comment]
@DarwinSodhi @dbuona I'm going over this now and it does look like we can figure this out. I will start the code in bb_analysis/cleaning/clean_thermaltimetodays.R. 

In the meantime, the entered data looks great but I am not sure where the 31-May-2015 field sample date is coming from. Would either or both of you check this out and see if it needs to be fixed or if it is correct?

**Comment by cchambe12** [comment]
@DarwinSodhi @dbuona Okay, I added notes and code to bb_analysis/cleaning/clean_thermaltimetodays.R

Would you both mind checking it? I'm not terribly confident it's completely correct!

**Comment by DarwinSodhi** [comment]
@cchambe12 Hello Cat, I will take a look after scrum!

**Comment by DarwinSodhi** [comment]
@cchambe12 Hello Cat I looked through your code and it makes sense to me to subtract field forcing and divide by gdh based on being in the climate chamber. For the outdoor treatment it never goes into the climate chamber so we shouldn't divide by gdh but subtracting field forcing makes sense to me.

Yes 31-May treatment is the one left outside. So AB is for abnormal flushing and 0 is for unflushed based on "A bud was considered to have flushed when its scales were broken and
new green foliage was clearly visible. Budburst was considered abnormal if it started first in lower branches, stems, and roots in broadleaves and if bud and needle expansion were constrained in conifers"

I had a follow up question looking at the materials and method section it seems like for a number of species the researchers put them in a green house to grow and then in field conditions as well, do we need to account for this information at all considering species had multiple seasons of chilling and forcing before undergoing the experiment?

**Comment by cchambe12** [comment]
@DarwinSodhi Okay great! That all makes sense. As for accounting for multiple field seasons, since they aren't monitoring budburst for the first couple of seasons we do not need to include this in our database. They just gave a lot of details about their study. @dbuona Do you agree we do not need to included these other details? 

As for the 31-May treatment, since it was left outside for the entire treatment, I am going to change the fieldsample.date column to blank. Otherwise, I think we are all set here! 

@dbuona Do you mind looking over the code one more time to make sure it looks okay to you?

**Comment by dbuona** [comment]
@cchambe12 I'll look at it today. And I agree, it doesn't seem like the preseason conditions were treatments.

**Comment by dbuona** [comment]
@cchambe12 code looks good to me

**Comment by AileneKane** [comment]
It looks like most of the man17 resp entries are converted to be in "days"  in ospree_clean_withchill_BB.csv but some are not and remain in units of total chilling (7 entries are >1000 for resp, and 18 are >100). Is this intentional or unfixable or do we need to do more cleaning? Just checking @cchambe12  @dbuona

**Comment by cchambe12** [comment]
@AileneKane Those entries are from experiments that were left in the field and do not have field sample dates so we can't calculate chilling or forcing based on the figures given. The respvar.simple should not be changed either!
