### ISSUE TITLE
double check ramos17

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#362]
See also #355 @AileneKane

**Comment by AileneKane** [comment]
ramos17 has  chilling data calculated from field chilling with the climate data, as it should. It also has forcing and photoperiod treatments. The chilling code seems to to pull the climate data, and We should be able to use this study, i think. It disappears from the d dataframe in step 5c of bb_cleanmergeall (clean_ambientforcingfromdailyclimate.R).  ramos17 doesn't show up in the "chilly" file but I think it should? This requires checking bb_daily_dataprep_get_expclimdat.R to figure out why its not there...

**Comment by AileneKane** [comment]
@lizzieinvancouver @cchambe12 Shall I check the bb_daily_dataprep_get_expclimdat.R file?

**Comment by cchambe12** [comment]
@AileneKane I'm looking now, it seems that ramos17 is missing info in the response.time column so it's being removed in clean_ambientforcingfromdailyclimate.R on line 70

**Comment by AileneKane** [comment]
@cchambe12 Oh- great catch! I was thinking it didn't need that column because it is a percentbudburst response, but you're right. I can add this in clean_responsetime.R at least for some of the experiments (e.g., for Fig. 1 it says they were forced at 30 degrees for 3 weeks, so responsetime would be 21 days).

**Comment by AileneKane** [comment]
@lizzieinvancouver @cchambe12 I have added the response time from figs 1-4 in ramos 17. for some of the responses, the paper says forcing occurred for "2-3 weeks" in which case I entered 18 (the mean) for response time. For some other responses, they said "2-5 weeks" and I did not enter the mean for those- it seemed to variable. Do you want me to do anything different?

**Comment by AileneKane** [comment]
also,  i'd love a double check if someone doens't mind looking at the paper...

**Comment by cchambe12** [comment]
@AileneKane It looks great to me! I just fixed the exp 2, 12.5C forcing treatment. In the very fine print it looks like the time was denoted in weeks not days so I just updated that in clean_responsetime.R in your new code block. Thanks Ailene! I am going to close this now.
