### ISSUE TITLE
anzanello16 issues

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#364]
@legault @MoralesCastilla I agree it seems like we have Fig 10 entered when it looks like it should be fig 5 (as there is no Fig 10) ... @DeirdreLoughnan before we bother Kelley (who entered this), can you tell me if you remember anything about it and check any old notes? (see also #355)

**Comment by DeirdreLoughnan** [comment]
@legault @MoralesCastilla I second that it looks like the entered data is from figure 5. I don't have anything in my notes about it. Are there concerns about the values entered?

**Comment by MoralesCastilla** [comment]
@DeirdreLoughnan the values should be ok, but I guess we need to change the reference to the correct figure in the database.

**Comment by lizzieinvancouver** [comment]
Lizzie wrote Kelley today ... will see what she says hopefully.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla @legault Here's the reply from Kelly. Please fix this in clean_misc.R, double-check it's working and close the issue.

> Sorry for the late reply, it's been a hectic month. I took a look and it does seem like that data comes from figure 5, and I didn't find a supplement for that paper so that seems like the best choice to make. Sorry for the typo there! 
> 
> I hope you are doing well and staying healthy. 
> 
> Best,
> 
> Kelley Slimon

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @legault 

`clean_misc.R` is now edited to change `fig 10` by `fig 5` in anzanello16. I'm closing this issue.
