### ISSUE TITLE
share best citations supporting that experimental growth chamber studies are the best way to disentangle chilling vs forcing

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#365]
Perhaps basic plant phys text book or classic articles?

**Comment by AileneKane** [comment]
@lizzieinvancouver @cchambe12 @dbuona @MoralesCastilla you can add ideas below or to the reviewer response letter that  I send you on Monday April 6!

**Comment by cchambe12** [comment]
@AileneKane I've been doing a lot of digging through my books. The best I have so far is Sakai and Larcher, 1987 (Frost Survival of Plants) they talk about cold acclimation a lot and chilling requirements along latitudinal gradients. They definitely talk about using growth chamber studies to disentangle chilling and photoperiod but still looking for chilling and forcing.

**Comment by AileneKane** [comment]
@cchambe12 Thank you! These are great!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Thank you! That one sounds great. 

@AileneKane Yes, I think some of the old papers might work best with a few more current ones. In OSPREE I recommend Junttila & Hänninen 2012 (which says, "Bud dormancy is released by an exposure to chilling temperatures in late autumn and early winter (Worrall and Mergen 1967, Sarvas 1974, Leinonen 1996).") and Worrall & Mergen 1967 (mix of experiments and controlled environment). One that I think is quite good includes a literature review: Harrington et al. 2010 (see Fig 5, trying to separate out these two), I will send over email.

I think you could say something like, decades of work have relied on controlled environment experiments (CITES here and from Cat)---those that we use here---to estimate chilling requirements, and equally to robustly estimate photoperiod and forcing requirements (plenty of CITES for this in OSPREE).

**Comment by AileneKane** [comment]
@lizzieinvancouver Thank you for these suggestions!

**Comment by lizzieinvancouver** [comment]
Lizzie also suggested Bonhomme et al 2010.
