### ISSUE TITLE
organize the ranges folder

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#368]
Would be good to clean this up, suggested @dbuona and @cchambe12 coordinate on this, ideally do this by 22 April if possible.

**Comment by cchambe12** [comment]
@dbuona I took a stab at cleaning this up. The `climoutput' folder is the only folder that has to stay as it is, I open all the climate folders at once to make a master .csv file. Otherwise, make any changes you think I missed!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Thanks! @dbuona this looks good to me, but perhaps you can check, do any final tidying and close this? Thanks!

**Comment by dbuona** [comment]
I did some cleaning too and I think its in good shape
