### ISSUE TITLE
add latlong for Fu18

### ISSUE THREAD

**Issue by dbuona** [lizzieinvancouver/ospree#373]
Check with group if this is worth it, but we think we need it because forcing, chilling and photoperiod all have ambients in the (open top chambers)

**Comment by cchambe12** [comment]
@dbuona we are using the growing.lat and long for the chilling but for some reason this isn't being picked up in ambient forcing! I will check that out

**Comment by lizzieinvancouver** [comment]
@cchambe12 Just checking in on some issues, like this one.

**Comment by cchambe12** [comment]
This has been fixed!
