### ISSUE TITLE
ospree trait lit rev. 

### ISSUE THREAD

**Issue by DeirdreLoughnan** [lizzieinvancouver/ospree#374]
@lizzieinvancouver @DarwinSodhi @dbuona @MoralesCastilla @cchambe12 @FaithJones @legault @md-garner 
Thanks everyone for your help with the trait literature review!

I have added the papers to the ospree papers folder on the drive and have shared a file here:
docs/traits/traits.litrev

If you have any questions or suggestions for additional data to collect, please let me know.

**Comment by DarwinSodhi** [comment]
@DeirdreLoughnan I reviewed three papers and added my notes to the docs/traits/traits.litrev file. Let me know if you want me to review more papers!

**Comment by cchambe12** [comment]
@DeirdreLoughnan I also did three! Happy to do more as well if you need more help!

**Comment by DeirdreLoughnan** [comment]
Thanks @DarwinSodhi and @cchambe12! 
We would like to summarize the lit review before the ospree traits lab meeting next week. @md-garner @FaithJones @legault @dbuona @MoralesCastilla if you have time to read a few papers, please do so before Sunday May 24. Thanks!

**Comment by MoralesCastilla** [comment]
My three papers are in too!
