### ISSUE TITLE
check dates ...

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#375]
@cchambe12 When time allows, can you rerun all the cleaning code and check the fieldsample dates for malyshev:

goo <- subset(d, datasetID=="malyshev18")
goo$fieldsample.date

They should all look normal now ... ? 

Also, @cchambe12  and @AileneKane do either of you know where we clean field sample dates? I noticed they come in lots of formats!

**Comment by AileneKane** [comment]
@lizzieinvancouver @cchambe12 we clean the field sample dates in clean_misc.R

**Comment by cchambe12** [comment]
@lizzieinvancouver And then @AileneKane was extra on top of it in chilling/fieldchillcalc.R where she makes a new column (fieldsample.date2) that converts all field sample dates to as.Dates and further checks are done!

**Comment by cchambe12** [comment]
@lizzieinvancouver malyshev dates look great!!

**Comment by lizzieinvancouver** [comment]
Working on closing out cleaning issues today -- one that is done without more effort. yay!
