### ISSUE TITLE
make sure ambient studies are labelled as such

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#376]
@dbuona Could you help with this ... I figured out where these should get force_type and photo_type properly labelled (in bb analysis):

Clean force_type in clean_rampedandexpforcing.R

Clean photo_type in clean_photoperiod.R 

definitely ambient:
richardson18
fu19
fu18

And maybe vitra17?

I am not sure of:

- man17
- malyshev18
- anzanello16
- anzanello18
- nanninga17
- ramos17
- prevey18

But do ask others if you are not sure! Thank you!

**Comment by lizzieinvancouver** [comment]
@dbuona We need to work on this issue to make OSPREE progress ... can you spend an hour on it and report back to me next week? We can find you more help if it is taking a while.

**Comment by dbuona** [comment]
@lizzieinvancouver  I'm on it

**Comment by dbuona** [comment]
@lizzieinvancouver I checked my commit history and found that I did this on June 1, 2020

**Comment by lizzieinvancouver** [comment]
@dbuona Amazing!
