### ISSUE TITLE
check crop species

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#378]
(@cchambe12 including you as I know you know these files) @MoralesCastilla I just updated speciescomplex.nocrops.R to include olive:

` cropspp <- c("Actinidia_deliciosa", "Malus_domestica", "Vitis_vinifera", "Ribes_nigrum", "Olea europaea")`

@MoralesCastilla You should check it gets excluded. 

We have so many species now! It might be worth asking someone to check the species list for any possibly domesticated species. We have some Rubus and Pyrus that I think lots of people grow, but mat not be domesticated, but some may be (e.g., "Prunus persica"). But we need a reference list to do this ... Jonathan said he can send one.

**Comment by lizzieinvancouver** [comment]
I just added a crop list, see commit 8a5d1d82b2090eae850d5498f606c46fdfcf3cde

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 
The crop list from Millá et al. is a pretty good reference to have! I included it in the phylogeny code, so I guess we can close this issue already.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Thanks! Can you point me to the code? I wanted to check what is excluded and compare to what we have in speciescomplex.nocrops.R
