### ISSUE TITLE
You say hazelnut, I say dogwood! Tomato, tomahto...

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#380]
OSPREE says there is a species called Cornus cornuta that we (yes, us!) sampled, but it's untrue. @lizzieinvancouver will fix this.

**Comment by lizzieinvancouver** [comment]
It shows up early so I fixed it in clean_misc.R (see commit 1ddfebf939c42086c6a609de9a307b362f15c3bc). @cchambe12 No rush, but when you have time, can you update the data and then close this issue? For now we can just remember the change.

**Comment by cchambe12** [comment]
I think we're all updated for ranges!
