### ISSUE TITLE
karlsson03 photoperiod

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#381]
This is a small issue, but it's worth fixing I think. I believe karlsson03 has 'ambient room' photoperiod but it's been entered as 'constant' (which I thought might mean 24 hr or such). @DeirdreLoughnan No rush on this but could you review the paper and see if you agree or can find any other info on daylength (photoperiod) in the paper?

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver there is actually no mention of photoperiod in the methods of this paper. The closest we can get to understanding the set up is the section that reads "one branch from each tree were placed in three rooms with different temperatures."

I agree with you that "ambient room" is a better description of the photoperiod than "constant". Do you want me to modify the cleaning code to address this?

**Comment by lizzieinvancouver** [comment]
> I agree with you that "ambient room" is a better description of the photoperiod than "constant". Do you want me to modify the cleaning code to address this?

@DeirdreLoughnan Yes, that would be great! I suspect clean_misc.R is a good place for it, but see what you think. Thanks.

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I also thought clean_misc.R was the best file to modify, I just pushed the edits and ran the cleanmerge_all.R to check that is worked.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Thanks! I will check and close this (hopefully).

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Looks good, thanks (I reviewed see 20882104d4ab0bf57d96bbff2a2aea0262a34c24).
