### ISSUE TITLE
Cleaning duplicate data

### ISSUE THREAD

**Issue by DeirdreLoughnan** [lizzieinvancouver/ospree#392]
@legault I was taking a last look at clean_duplicates.R and was struck by how much of the bien data is being removed. If we add Latitude, Longitude, and Reference to the target variables (~line 45), we are left with 65% of the total dataset as opposed to only 2%. 

Could you take another look over the code and see if there is anything other variables we should include, or reasons why we should not add these target variables? 

I think our data cleaning is still pretty conservative and errs on the side of removing data when there is uncertainty (ie NA values for the lat, long, and references. Most (99%) of the removed bien data appears to be height data from G. Reams. And we are still removing 48.6% of the TRY data.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan I know Nacho's original code a fair bit (Ailene and I did the peer code review on it) so let me know if I can help. Based on what I know it would be critical to include Latitude, Longitude, and Reference, as the code (Nacho's original for the OSPREE budburst data) only compares values if the relevant columns are the same -- in the original code that was a bunch of treatments and provenance etc.. so you would need to include a similar suite of columns in the trait data to use his basic code design (if I am understanding the trait data). If I can help let me know, and definitely let me know what file to look at.

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver that would be great. 

I realized that the lat/long included in the dataset were the original values (which special characters) and not the standardized values. I went back into the cleaning code (TRY_cleaning_Nov2020FJ.R) and added the standardized values, but in doing so, a number of special characters were introduced into the reference column. @legault @FaithJones do you know why this would happen or have a better way of fixing them?

I inelegantly fixed this in the clean_duplicates.R and it runs fine. I am just not sure why changing the lat/lon values would also change the reference column.

**Comment by legault** [comment]
@DeirdreLoughnan I'm not sure why that's happening. Looking at TRY_cleaning I don't see a place where the reference column is altered. If you revert the change to lat/long, can you reproduce the effect on the reference column? Relatedly, are any of the special characters commas or things that might affect how the data is read into R?

**Comment by DeirdreLoughnan** [comment]
@legault the issue seems to have resolved itself on my end, but I don't understand what caused it. I only changed the ExtraInfoColumns section of TRY_cleaning_Nov2020FJ.R (lines 117-146) and then it was no longer reading the umlaut or accents on authors names. Oh well!

**Comment by DeirdreLoughnan** [comment]
For related notes on TRY's explanation for how to find duplicate data, see [here](https://github.com/lizzieinvancouver/ospree/issues/396). 

Ultimately we are sticking to our current methods of removing duplicated data, which removes 434905 rows of data, 5028 rows more than would be removed using the OrigObsDataID's alone.
