### ISSUE TITLE
Help with conceptual non-linearity figures!

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#393]
Hello! I desperately need help with some conceptual figures. Right now I have them as three separate ones, all in [this folder](https://github.com/lizzieinvancouver/ospree/tree/bbculdesac/docs/limitingcues/figures) ... I will also paste them below in a separate comment.

Could both of you work together to figure if we should include them and, if so, how? (Three figures, one big figure, two figures?). They are currently figures 1,2 and 4 in the main text and they are referenced in the sections 'How do phenological cues produce non-linear responses?' and 'How will chilling, forcing and photoperiod shift with climate change?' (pdf pages 4-6). 

Once that is figured ... I thought:
@AileneKane Could you work on the code to make them? It is all in nonlinearities_more.R  and need someone thoughtful to fix it. 
@MoralesCastilla Could you help make these pretty?

Here's the relevant text though I think best just to read the PDF perhaps (section 1.1-1.2; starts at bottom of page 4, ends on page 7!

```
Controlled environment studies show two major ways these cues can produce non-linear response---each cue alone, or through interactions between cues (Figs. \ref{fig:onecue}-\ref{fig:intxncues}). Each cue alone may produce a non-linear phenological response when examined across a sufficiently wide range of values (Fig. \ref{fig:onecue}). Cues may be linear in the mid-range of values, while extremely high or low values of some cues may produce alternative response \citep{gauzere2017}. For example, at very low photoperiod (short days) plants often will budburst erratically \citep{Heide:1993,Partanen:1998aa,Singh:2017,rinne2018}, similarly maximum growth may occur at sufficiently long photoperiods, meaning photoperiods longer than some threshold will have no additional effect on budburst timing \citep[e.g., $>$18 hours for several crop species][]{major1980}. Similarly, extremely cool or very hot temperatures may limit forcing as plant developmental processes slow \citep{parent2012}. Such extreme values of cues, however, are likely less common than interactions between cues that can produce non-linearities.\\

More commonly research has focused on how the interaction of cues may produce non-linearities. For example, multiple studies now show that the threshold of forcing needed for budburst depends on the sum of chilling over the fall and winter and by the photoperiod while forcing is accumulating in the spring \citep[e.g.,][]{zohner2014,flynn2018}. Higher forcing is generally needed given lower chilling (Fig. \ref{fig:gddbyutah}) and short photoperiods \citep{Basler:2014aa,fu2019}---producing generally a subadditive effect of forcing x chilling and forcing x photoperiod (i.e., both cues together produce a more muted response than the addition of each cue's effect alone). This interaction of cues produces a non-linearity in environments where levels of cues are correlated over time or space---for example, if chilling declines are correlated with greater forcing (Fig. \ref{fig:intxncues})---and may be critical to accurate forecasts with climate change.
```
...
```
Unfortunately, these predictions are based on models developed almost solely for agricultural crops \citep[but see][]{harrington2015}, especially stone fruits, and have rarely been robustly adapted to forest trees. While the development of classic models of chilling for peaches and related fruit trees benefited from data on these species being planted far outside their range into regions with extremely low or potentially no chilling, equivalent data on forest trees is almost never available \citep{dennis2003}. Thus chilling models to date generally use limited observational and experimental data from forest trees to try to re-parametrize the basic stone fruit models \citep{Chuine2000}. This in turn makes any current observations of shifts in chilling---and all forecasts with warming---uncertain. Thus we believe is especially important to consider both increases and decreases as potential outcomes of warming (Fig. \ref{fig:intxncues}, \ref{fig:chilling}). 
```
....
```
These shifts---in forcing, chilling and photoperiod experienced near the time of an event (henceforth `experienced photoperiod')---can produce non-linearities when they push a single cue across a critical threshold or inflection point in its effect. For example, if some species have a critical photoperiod for budburst and warming means forcing cues are met before the critical threshold, then we would expect incomplete or highly delayed budburst \citep{Singh:2017,rinne2018}. Alternatively, the threshold could be crossed in the other direction. For example, if pre-climate change conditions generally caused budburst to occur at the extremes of some cues and climate change has now pushed budburst into periods where these cues are at the more linear part. This is often the mechanism suggested for declining responses to warming in some temperate trees \citep{fu2015,piao2017,gauzere2019}, specifically that plants previously accumulated sufficient chilling for a minimal effect of chilling---making forcing the dominant cue---whereas warming has now reduced chilling such that more forcing is needed for budburst (producing an overall muted effect when estimated with current methods). As this example highlights, however, changes in a single cue are unlikely to occur without additional effects on other cues---complicating how well we can understand them in long-term data without robust understanding of the exact cue requirements from experimental studies.\\

We expect most non-linearities from climate change will come from the effects of interactive cues, as in the previous example where one cue pushed beyond an inflection point triggers shifts in other cues, and due to other covarying shifts the cues caused by environmental change. While simple linear interactions between cues may not alone produce non-linearities (Fig. \ref{fig:intxncues}), they quickly become non-linear when changes occur together---for example if increased forcing also occurs in step with shorter experienced photoperiods (Fig. \ref{fig:intxncues}). Predicting these non-linearities, however, requires a refined understanding of the interaction and whether there are critical inflection points that may be crossed with continued warming. These complexities highlight how difficult predictions may be without careful efforts to tease out how each cue works alone and interactively.
```

**Comment by lizzieinvancouver** [comment]
fig:onecue currently looks like:

![limcues_nonlin_onecue](https://user-images.githubusercontent.com/2153556/106529528-86424600-649f-11eb-863e-81d09060e647.png)

**Comment by lizzieinvancouver** [comment]
fig:intxncues looks like

![limcues_intxns](https://user-images.githubusercontent.com/2153556/106529551-8fcbae00-649f-11eb-8340-9946633e6cb9.png)

**Comment by lizzieinvancouver** [comment]
and fig:chilling ...

![limcues_chilling](https://user-images.githubusercontent.com/2153556/106529573-99551600-649f-11eb-9474-1e8558a0a507.png)

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 

Ailene and I met last week and have started working on this. Ailene is working on the code for figs 1-2, which we thought could be merged (new suggestions expected by the end of this week, beginning of next week).

For fig. 4, we both agreed it is already nice as it is but, as a suggestion, we thought the information could be displayed in a single panel. Here is a [1 panel draft of figure 4](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/figures/utahchill_limiting_1panel.png?raw=true). Let us know any ideas or comments either to keep exploring 1-panel versions or stick to 3-panels.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla This looks great! I really like the change (feel free to change colors etc. as you see fit). Thank you and @AileneKane for working on this.

**Comment by AileneKane** [comment]
@MoralesCastillaThank you for making it look so pretty! I was realizing that I think we should extend the chilling accumulation line below 1.4 degrees C (it currently stops abruptly there).  It should be a horzontal line at 0 below 1.4 degrees (no chilling accumulates, based on the utah model). I can update the code to reflect this. Perhaps you want to add it in AI for this figure?

**Comment by MoralesCastilla** [comment]
@AileneKane that makes a lot of sense. I've updated the figure to account for zero accumulation of chilling at lower temperatures.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 
Here's a first stab at fig 2, which would kind of incorporate fig 1 and scenarios when chilling decreases with warming. We thought this could simplify things a bit, but I think both Ailene and I would like some feedback and perhaps brainstorm on how to improve this one. Looking back at the original figure I realize perhaps the point was making something still more conceptual? I'm happy to tweak this version more: see it at https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/docs/limitingcues/figures/intxnsims2021photoaltwithchill_2cols.png

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla @AileneKane Thank you for this! I think it looks great and seems like it could work for Fig 1-2 (which I would like as they seem pretty overlapping). 

I think one thing to clarify is whether the top row is photoperiod or just a 'second cue' that declines (that could be photoperiod or chilling)? Or a mix? I think a mix will be hard without some edits to the figure, but maybe not with a good caption.

The only other piece I see as confusing is that the linear cues are non-linear because we have forcing and the other cue shift TOGETHER. That's why the old figure had something on the x axis trying to show that with temperature you get a shift in forcing and another cue -- that creates the non-linearity.  

One idea (not sure is this works) would be a fourth panel that is second from the left that shows the two responses when the cues are not coupler or such? Then the interactions will be linear. Or we could have as a top row with just one example of the far left panels (threshold versus linear)? Then the top is a 'second cue' linear vs. threshold example, plus a linear interaction example where one cue shifts alone ... then what you have but omit the left panel. 

I think the photoperiod left panel should have less of the negative Y range (as it means budburst advances).

**Comment by AileneKane** [comment]
Thank you @lizzieinvancouver for these points (and @MoralesCastilla for your work on improving the figure)! I agree that it would be helpful to add a panel- perhaps that shows how each cue changes with warming to more explicitly show that we are showing the effect of two cues changing together. I will work on this- @lizzieinvancouver perhaps we can talk about this in our meeting today (Feb 23).

**Comment by AileneKane** [comment]
@lizzieinvancouver  and @MoralesCastilla I gave a rough try at this [here](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/figures/intxnsims2021photoaltwithchill_8panels.pdf)

**Comment by AileneKane** [comment]
@lizzieinvancouver and @MoralesCastilla I have[ updated this a bit]([url](https://github.com/lizzieinvancouver/ospree/blob/872bc89544b8164819d857af9acad75a72cc2958/analyses/limitingcues/figures/intxnsims2021photoaltwithchill_6panels.pdf))- still needs work to make it look pretty!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane here go a couple of tweaks to the [figure](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/figures/intxnsims2021photoaltwithchill_6panels_imc.png). I was wondering if it would make sense to zoom in panel C to avoid the clumping of lines and labels. Other than that, I think this version tells a clearer story than the previous one.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla This looks amazing to me! Do you mean panel E? Ailene and I had discussed her changing where the threshold is, which I think would also help.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver  Ups, sure, I meant panel E. Changing the threshold would actually a better idea to keep the x-axis in the same scale across panels!

**Comment by AileneKane** [comment]
@MoralesCastilla I love how you've improved it! I will remake the figure with a different threshold and also add an example chilling line showing a decline in chilling to panel A.

**Comment by AileneKane** [comment]
ok @lizzieinvancouver and @MoralesCastilla I have modified the [figure](https://github.com/lizzieinvancouver/ospree/blob/5909c16b4fe403bb4ce7747217c474f457f3fe78/analyses/limitingcues/figures/intxnsims2021photoaltwithchill_6panels_new.pdf) a bit by removing the units on the axes and changing the threshold. I also added a third chill line that shows a decline in chilling. We could consider showing chilling as a polygon showing the range between the lines, rather than as distinct lines. Let me know if you'd like me to change anything else!
Last thing I plan to do is confirm that the interactions we use are reasonable (i.e. negative for forcing by photo, positive for forcing by chilling)

**Comment by lizzieinvancouver** [comment]
@AileneKane Looks good! I think a polygon for chilling would be more intuitive. It would be great if you can also note your methods clearly here or elsewhere (esp. on how you got the panel A trend lines).

Thank you both for working on this!

**Comment by AileneKane** [comment]
@lizzieinvancouver and @MoralesCastilla I've modified the conceptual figure to include a polygon [here](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/figures/intxnsims2021photoaltwithchill_6panels_polygon.pdf)
I've also tried to check that the magnitude of interactions we use in the simulations for this figure are reasonable but all the studies that I checked that have significant interactions between forcing and photoperiod or forcing and chilling do not report the actual effect, only the p-value. (This is likely because most treatments are categorical- e.g., high vs low photoperiod). I kept track of the papers I looked at [here](https://github.com/lizzieinvancouver/ospree/commit/3dfa9d31b92253b81065e3e20fa98a31b614c028)

**Comment by AileneKane** [comment]
Here are my methods:
We simulated budburst dates, using the following linear models:

1. Forcing only (e.g., bbforce <- interceptbb + feff*df$force); interceptbb set to 120

2. Forcing and photo or forcing and chilling main effects only, with linear responses of both cues (e.g., df$bbforcephoto <- interceptbb + feff*df$force + peff*df$photolinear) 

3. Forcing and photo or forcing and chilling main effects only, with threshold responses for photo or chilling (e.g., df$bbforcephotohinge <- interceptbb + feff*df$force + peff*df$photohinge

4.  Forcing and photo or forcing and chilling with main and interactive effects and linear responses of both cues (e.g., df$bbforcephotoint <- interceptbb + feff*df$force + peff*df$photolinear + fpeff*(df$force*df$photolinear)
5. Forcing and photo or forcing and chilling with main and interactive effects, with threshold responses for photo or chilling (e.g., df$bbforcephotohingeint <- interceptbb + feff*df$force + peff*df$photohinge + fpeff*(df$force*df$photohinge)

For models 4 and 5 we simulated data using both strong and week cues, and the resulting relationships are plotted in Panels B-E.

For Panel A, we show expected shifts in cues with warming: 

- Forcing will increase by definition
- changes in chilling depend on the current climate and may decrease or decrease with warming (to show a reasonable range of how chilling may shift with warming we used the estimates from Figure ED6 in Ettinger et al 2020 (the main budburst OSPREE paper).
- changes on experienced photoperiod occur due to forcing-induced shifts in budburst. we estimated these shifts using the simulated budburst data driven by forcing and photoperiod linear model with no interactions at 48 degrees latitude.

Code located in [nonlinearities_more.R](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/nonlinearities_more.R)

**Comment by MoralesCastilla** [comment]
@AileneKane @lizzieinvancouver I have tweaked Ailene's figure keeping the polygon and new values. Let me know if you want to change anything else. See new version [here](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/figures/intxnsims2021photoaltwithchill_6panels_polyg_imc.png)

**Comment by AileneKane** [comment]
I think it looks great @MoralesCastilla ! Thank you!

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I also think it looks great! @AileneKane and @MoralesCastilla thank you both! Any edits on the current caption?

Interactions can produce nonlinearities, even in simple linear models if there are correlated shifts in cues. Much research focuses on how warming increases forcing (A), but it may also alter other cues (B), including photoperiod experienced near the time of the event, which is expected to shorten, and chilling, which may either increase or decrease. Shifts in forcing alongside shifts in a second cue (A) produce non-linearities due to the interaction between cues (C-F showing the effect of: forcing-only in yellow, both cues without an interaction in light blue, and both cues with an interaction in darker blue), with the overall change in budburst day predicted with warming dependent on the sign ($+/-$), strength (weak and strong), and shape of the second cue (showing two simple examples: linear in C-D and threshold E-F).

**Comment by AileneKane** [comment]
@lizzieinvancouver I think the caption is great!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver me too, nothing to add/change

**Comment by lizzieinvancouver** [comment]
@AileneKane I started through some of the papers that have F x P interaction designs ...

Our countintxns.R code estimates 17 interactive p x f experiments ... 

limitingcues/output/ospree_studyinxns.csv

- Basler_2014 -- does photo x forcing, but does not give effect sizes ... and I could not tell quickly if they found a significant interaction (though they did test for it).
- Sanz-Perez 09 -- "At 12 °C, Q. faginea opened 20 days earlier than Q. ilex, while at 19 °C this difference was reduced to 5 days (Fig. 1). Photoperiod only affected days to bud- burst in Q. faginea, where the longer the daylength, the earlier the date of budburst at all temperatures (an advance of 8 ± 1 days) (Fig. 1, Table 1). There was a temperature by photoperiod interaction for the two species (Table 1); the advance of budburst by temperature being greater at longer than at shorter daylengths, especially in Q. ilex. "
- devries 82 -- more about irradiance than photoperiod so not sure.
- heide 2005 -- did not check
- heide 2008 -- suggests a sub-additive effect ("Growth rates increased progressively with increasing temperature under long day (LD) conditions in all species, and this was associated with increased internode length in LD compared with SD conditions. Production of new leaves was unaffected by photoperiod at high temperature, but was higher in LD than in SD at lower temperatures.")

I am not sure we need to do more, I just wanted to keep the notes here.

**Comment by lizzieinvancouver** [comment]
MS submitted, this is done for now, @AileneKane and @MoralesCastilla -- Thank you!
