### ISSUE TITLE
help with studydesign figures!

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#395]
@dbuona Can you review my code in studydesignplots.R? See what outstanding issues remain and try to figure out if there is any way to add the non-numeric values ('variable' etc.) of experimental chilling to the final heatmaps (heatmapphotoxforcexchill I believe).

**Comment by dbuona** [comment]
@lizzieinvancouver Wow that's a lot of code! I came up with a rather hacky way of adding character values to the heat maps (adding a boarder around each cell value colored by character). I can't quite figure out why the borders are different thicknesses for different cells but if you like the general approach I can keep playing with it. see heatmapphotoxforcexchill.

**Comment by lizzieinvancouver** [comment]
@dbuona Thanks! I think this could definitely work if we can make it more faint or somehow less dramatic -- I don't want it to draw all the readers' attention since we're also trying to show the values and compare to field sample dates. 

One alternative would be to give different numeric values to 'other' and 'variable' and then manually do the gradient? I am not sure if that would work, but here are a couple posts:
[stackoverflow](https://stackoverflow.com/questions/23879639/rggplot-heatmap-specific-color-if-value-x)
[guide to elegant heatmaps](https://www.royfrancis.com/a-guide-to-elegant-tiled-heatmaps-in-r-2019/)

Also ... feel free to improve the colors! And do check that 'variable' and 'other' are experimental chill in all cases. 

Good luck and thanks again!

**Comment by lizzieinvancouver** [comment]
@dbuona One more request (from looking over my notes) ... can you check my work? I have a note that says:
Make sure that I gather correctly: see [here](https://stackoverflow.com/questions/48772829/heatmap-in-r-with-ggplot2) AND [here](https://www.worldfullofdata.com/three-ways-create-heatmap-r/)

**Comment by dbuona** [comment]
@lizzieinvancouver I made a new draft of the heat map (heatmapphotoxforcexchill_alt.pdf) as conceived of above.

I'll keep working on checking the code. Are there specific lines or chunk that you are worried about the gathering?

**Comment by lizzieinvancouver** [comment]
@dbuona Thanks! This looks good -- can you put slightly bigger gaps between 20 to variable/other when coding them, so it's pretty obvious where the numeric coloring stops? Perhaps just lump variable and other into 'variable/other' even.

And yes! I am most worried about the code under "TO DO for heatmap:  (1) Make sure I am counting correctly" specifically when I build dsumm.treat and any of the dsumm.nums summaries. 

Thank you again!

**Comment by lizzieinvancouver** [comment]
@dbuona To finalize the new exp chill figure, can you switch to a viridis palette (https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) and make an updated heatmapphotoxforcexchill2panel.pdf (two panels)?

**Comment by lizzieinvancouver** [comment]
@dbuona Me again! Could you update the supp (exciting, I made a supp!) with `\Sexpr` for the current text, and add any more text and figures you think we should have on latitudinal trends? And pretty up those figures so they are publishable (axes with full words etc.)?

**Comment by dbuona** [comment]
@lizzieinvancouver 
1. I checked the gathering using an alternative dplyr syntax that I am more familiar with and it yielded the same answers so I think we're good there.
2. I upated the heatmaps with viridis.  I wasn't sure if it was good to have the two maps on the exact same color scale or not, so I went with a "similar but not identical" viridis palette  for each one but I am happy to tweak them.
3. I'll continue to work on the Supp and latitude figures throughout this week

**Comment by lizzieinvancouver** [comment]
@dbuona Thanks! Re (2) -- good point, I don't know what the rule/best-practice is there either, but I like the figure! It looks good to me and the other/variable really nicely stands out now (thank you!). We can see what the co-authors say.

**Comment by dbuona** [comment]
@lizzieinvancouver 
I changed the axis labels on the supplement plots. Let me know if there is anything else you want done to make them even prettier. 

I added Sexpr{} numbers, but I couldn't get the supplement to compile (I think there might might be broken paths between my file structure and yours). Could you take a look and see if there is any easy fix and if not I will keep chipping away at it?

**Comment by lizzieinvancouver** [comment]
@dbuona Thanks! The two issues I found in the Rnw were
1. It was first error-ing on results='hide' (I think it wanted results="hide" -- two quotation marks -- but it's not necessary so I just cut it)
2. Next it thought the PDFs were corrupted so I re-rain studydesignplots.R and then it seemed fine.

For the plots can you:
1. Make the with viridis?
2. Put all in one PDF file with a legend?
3. Are there any other ones you think we should show? If so, please add them!

**Comment by lizzieinvancouver** [comment]
@dbuona So .... I just noticed that in countintxns.R I have a line of code ...

`write.csv(datsm14d, "limitingcues/output/osp14d_forheatmaps.csv", row.names=FALSE)
`
Any chance see you an easy way to switch to this in the studydesign code? As best I can tell from my own code this file is just the data subsetted to woody species, removing one dormancy study and making sure all field.sample dates are 14 days apart....

**Comment by lizzieinvancouver** [comment]
@dbuona I can also work on this if you like.

**Comment by lizzieinvancouver** [comment]
@dbuona And if you do make the switch it would be good to check that there are not dramatic changes ... it should be a small adjustment.

**Comment by lizzieinvancouver** [comment]
@dbuona I just tried to find a tidy place to add datsm14d and it seems not a great idea ... that file has so few columns, I am not sure it will work. So I made a note in the code where I write datsm14d and I just deleted spann04 from the data as that seems to potentially be treatments applied when plants were growing.

**Comment by lizzieinvancouver** [comment]
@dbuona Two more requests:

1. Cat wants to know if we can make the axis labels larger? We might be able to, if we fill in missing values and go every two digits or such ... I am not sure it is worth it. See what you think. 
2. Can you add a title to each panel? My idea is 'Force x photo cue-space with experimental chilling' and Force x photo cue-space with field chilling' (maybe two lines!) but I am up for suggestions. Feel free to wait on doing this until we hear what @MoralesCastilla says in his ms comments.

**Comment by lizzieinvancouver** [comment]
@dbuona Okay, I am wrapping up a new draft so need an updated figure. Here are my overall requests:

1. Cat wants to know if we can make the axis labels larger? We might be able to, if we fill in missing values and go every two digits or such ... I am not sure it is worth it. See what you think after estimating how much work it would be. 
2. Please add a title to each panel. My idea is 'Force x photo cue-space with experimental chilling' and Force x photo cue-space with field chilling' (maybe two lines).
3. Please check what the faint colored lines around gray squares mean. I think/hope we don't need them given the nice yellow for other/variable now? 
4. Please change axes to 'Photoperiod (hours)' and 'Forcing temperature (degree sign C)'
5. Please make legend on right panel with an italics 'n'
6. Please check/fix my caption: Studies have manipulated a range of forcing temperatures (vertical axis) and photoperiods (horizontal axis) across two methods to manipulate chilling: experimentally (left) or using multiple field sampling dates (right). Gray squares indicate a combination of forcing x photoperiod not present for that method of chilling design, while a value of `NA' indicates that we could not estimate a level of a particular cue because it was not clearly reported.

Thank you!

**Comment by dbuona** [comment]
@lizzieinvancouver 
1. I just made the font bigger and I think it works for the 2 pannel figure
2. Done
3. I could not figure out why this was happen. The only way I was able to get rid of it was to change the cell color background to black instead of white. You can let me know if you think it looks worse now.
4.  Done
5. Done (but surprising difficult to get the formatting right)
6.  Will do this afternoon!

**Comment by lizzieinvancouver** [comment]
@dbuona Any caption comments?

Also ...

When I run:

```
> pdf(paste("limitingcues/figures/heatmapphotoxforcexchill2panel.pdf", sep=""), width = 16, height = 8)
> plot_grid(heatmapphotoxforcexchill, heatmapphotoxforcexfs.date, 
+      labels = c('(a) Force x photo cue-space with experimental chilling', '(b) Force x photo cue-space with field chilling'), hjust=c(0.0005,0.00001), # 
+     ncol=2)
There were 50 or more warnings (use warnings() to see the first 50)
```

I get this warning:
```
50: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  font metrics unknown for character 0xa
```

Do you? If not I will assume it's an error because I a missing a font that you have. (I get the same error slightly above this code also.)

**Comment by dbuona** [comment]
@lizzieinvancouver I made only very minor changes to the caption. 

I will run the code and see if I can figure out the error, but I think if the figure looks okay, we are probably good to go.

**Comment by lizzieinvancouver** [comment]
@dbuona 

Any chance you can help me with this issue Ailene raised about Supp figure S3:

> If we're going to use this to support the statement that treatments are correlated with latitude, do you think we should report the r or r2 values for the correlations?

I was wondering if we could add stats (R2?) to the figure itself?  I updated the figure to supplatplots4panel.pdf

... I know you're slammed though so if you don't have time just ping me back on this issue so I don't forget about it.

Thanks!

**Comment by lizzieinvancouver** [comment]
@dbuona And I mean ... I updated the figure last week (or before, all is a blur) to a 4-panel version, so it's called supplatplots4panel (same R file). It's still in base R so I think text can be added with `mtext`

**Comment by AileneKane** [comment]
@dbuona let me know if you need me to do it! I have capacity for it this week!

**Comment by lizzieinvancouver** [comment]
@dbuona I am working on this just now ... so hoping you aren't.

**Comment by lizzieinvancouver** [comment]
MS submitted, this is done for now.

**Comment by lizzieinvancouver** [comment]
@dbuona Thank you!
