### ISSUE TITLE
Resampling height trait data

### ISSUE THREAD

**Issue by DeirdreLoughnan** [lizzieinvancouver/ospree#397]
Thanks @lizzieinvancouver for offering to help resample the height data to make the size of the dataset more manageable. 

Please let us know if there is anything we can do to help!

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan I did this already! (Wow, this never happens) Check out commit #1bace95b6f3e14a2cc8a8bfe6eccb1e91e06cc6a

**Comment by lizzieinvancouver** [comment]
commit 1bace95b6f3e14a2cc8a8bfe6eccb1e91e06cc6a

**Comment by DeirdreLoughnan** [comment]
Amazing , thanks!
