### ISSUE TITLE
finalize the map figure

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#400]
@cchambe12 Can you track down the code for the map map_studyspp.pdf and update it by ...

- Check your numbers, it says basler12 is 28 spp, but it should be 14
- Perhaps adjust the breaks in the circles? Maybe just do it for all studies but zohner and then we can note that zohner is giant in the caption?

**Comment by cchambe12** [comment]
@lizzieinvancouver I think this is fixed!
