### ISSUE TITLE
finalize cues over time figure

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#402]
@cchambe12 Can you update analyses/limitingcues/figures/studyyearcues.pdf to make sure we use the same methods as in countinxns (maybe we should just use that code?) and make the figure shorter? Thank you!

**Comment by cchambe12** [comment]
@lizzieinvancouver Done! I have moved this code to the countinxns.R script and have moved this script to a new zarchive folder in limitingcues. I have also made a new figure that is much shorter haha that was a very tall original!
