### ISSUE TITLE
finalize map

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#408]
@cchambe12 Could you ...

- Explain why some studies don't show up (e.g., dantec14 and devries82)?
- Change DatasetID to just Dataset

Thank you!

**Comment by cchambe12** [comment]
@lizzieinvancouver I was using the bb dataframe again! The new map should now include all studies. I have also changed the legend to read just 'Dataset' and I have updated the colors to use the 'viridis' package. Let me know if you'd like any other changes!

**Comment by lizzieinvancouver** [comment]
Thank you @cchambe12
