### ISSUE TITLE
Traits paper outline

### ISSUE THREAD

**Issue by DeirdreLoughnan** [lizzieinvancouver/ospree#414]
Thank you everyone who has participated in our Traitors Journal Club! I had fun with our discussions and we have made so much progress towards having an outline for our paper! 

I have updated the outline from today's meeting for anyone who wants to review it soon!

For those who could not make it today, the plan is to communicate using issues moving forward, but to have at least one more meeting in 2-3 weeks to discuss the outline and give everyone one last opportunity to contribute.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Thanks! I took a look this morning made a few edits and added some comments. I suggest you set a deadline for everyone to send comments.

**Comment by DeirdreLoughnan** [comment]
Thanks Lizzie! 

Let's aim for everyone to have read and added any comments to the outline by May 5!

**Comment by DeirdreLoughnan** [comment]
In late May we met and agreed on an outline for the introduction and hypotheses, I am now working on a first draft that we will all read over during the late September 2021 mini retreat.
