### ISSUE TITLE
Running traitors model for each trait

### ISSUE THREAD

**Issue by DeirdreLoughnan** [lizzieinvancouver/ospree#417]
@lizzieinvancouver @legault @FaithJones I have been working on the traitors model and could use help working out some kinks and with interpretation.

The general traitors model developed using the test data can be found [here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/stan/joint_forcingchillingphoto.stan). 

I started by running the model on sla using [this stan code](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/stan/joint_3cue_sla_stan.stan) and [this Rcode](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/Rfiles/joint_3cues_sla.R). 

For SLA: the model runs and does not produce any error messages, but the n_eff of several of the muSp and muStudy are low (around 750) and the chains mix poorly. Such as for muSp[1]: 
<img width="599" alt="Screen Shot 2021-08-05 at 5 10 29 PM" src="https://user-images.githubusercontent.com/16216421/128437037-b2dea617-0b5d-4ba4-a1a4-51aedb822902.png">

I have run the model with more iterations, but neither 8000 or 10000 improved the n_eff. The Rhat's are not bad though. Am I correct that this suggests an issue with the data itself and non-identifiability?

The low n_eff aside, the summary statistics are the following: 
![Screen Shot 2021-08-03 at 8 43 41 PM](https://user-images.githubusercontent.com/16216421/128119998-01eadde2-3176-46db-9368-9285bf15b6fa.png)

My interpretation of these results would be:

-  All cues advance bb
-  Chilling is still the strongest, but not as strong as in the bb ms, followed by forcing and photoperiod
- The negative values for the betaTraitxCues suggests that increasing SLA leads to advances in bb with each cue
- SLA is most responsive to photoperiod cues since it is most negative

**Comment by FaithJones** [comment]
Progress we need to make on this issue:
- [ ] @legault is checking if we can use a substitute for height (stem density)
- [ ] Geoff will then run the traitors model for stem height
- [ ] Prior predictive check (or some other prior check) on SLA
- [ ] run SLA model on real data and check output
- [ ] Prior Predictive check (or some other prior check) on LNC
- [ ] run LNC on real data and check model fit and output
- [ ] Prior Predictive check (or some other prior check) on seedmass
- [ ] run seed mass model on real data and check model fit and output

**Comment by DeirdreLoughnan** [comment]
@legault @FaithJones your comment about the SLA values being odd surprised me and I wanted to quickly check what data files you are using. In the files I was working with SLA ranges 1.4 to 138 and produces this histogram:
<img width="436" alt="Screen Shot 2021-09-23 at 3 28 53 PM" src="https://user-images.githubusercontent.com/16216421/134571511-832dd284-3f6f-4ea6-8b2c-47d336635fec.png">

Are you using the cleaned data files with the data subsetted for the species of interest? 

```
"input/try_bien_nodups_1.csv"
"input/try_bien_nodups_2.csv"

traitors.sp <- c("Acer_pensylvanicum", "Acer_pseudoplatanus", "Acer_saccharum", "Aesculus_hippocastanum", "Alnus_glutinosa", "Alnus_incana", "Betula_pendula", "Betula_populifolia", "Corylus_avellana", "Fagus_grandifolia","Fagus_sylvatica", "Fraxinus_excelsior", "Juglans_regia", "Populus_tremula", "Prunus_padus", "Prunus_serotina", "Quercus_alba", "Quercus_coccifera", "Quercus_ilex", "Quercus_petraea", "Quercus_robur", "Quercus_rubra", "Quercus_velutina", "Rhamnus_cathartica", "Sorbus_aucuparia", "Ulmus_pumila")

```

**Comment by legault** [comment]
@DeirdreLoughnan 

I don't know much about the traits, so I was curious if it is was odd looking? Do those values look reasonable? Should we expect two modes? Do terrestrial plants have SLAs > 100? If yes, great.

Relatedly, there seems to be a problem with the plant heights. Specifically, multiple rows of apparently different data with identical traitvalues. For example
![screenshot](https://user-images.githubusercontent.com/10699779/134588509-f913c4c2-60f4-47f9-aa47-a21b446769ff.png)
:

**Comment by DeirdreLoughnan** [comment]
@FaithJones these are the 26 species that we had a at least one observation for the six traits we decided to explore further in the PCA analysis. OSPREE has data for a lot more species, but we were limited by the completeness of the trait data.

@legault, I could see higher values of SLA for species with thin compound leaves, but that is not the case for the species with high SLA values (Quercus ilex and Acer pensylvanicum). High values close or over 100 would make sense if the units were cm^2/g, but less so for this data which is supposedly in mm^2/mg. There are only four entries with values over 60 mm^2/mg, so it is possible that these are typos. 

I recall us discussing ages ago what to do about extreme values in the trait data. Am I correct in remembering that we decided not to exclude any data because our models would pool towards the species means? For this Quercus and Acer species we do have a lot of data (610 and 910 rows of SLA data respectively), the histograms of which is below:

![Screen Shot 2021-09-27 at 10 19 31 AM](https://user-images.githubusercontent.com/16216421/134956130-d5a919e1-eeef-4675-8b3c-686ad44fa432.png)

Regarding the height data, you are right that there is a lot of repetition in the height values. But that issue was in the original datafile as well and not an issue introduced by our cleaning. We do have a lot of height data (~65000 rows) and most of the height data, and the data in the issue you found above, comes from that dataset from Greg Reams. We could discuss moving forward without that dataset, but we would loose height data for three species.

We can discuss how we want to deal with these extreme values and data issues at our meeting Wednesday.

**Comment by FaithJones** [comment]
@legault is going to ask the Bien team about the duplicated height data. If we don't get answers then we may drop the suspect height data

**Comment by FaithJones** [comment]
@legault @DeirdreLoughnan running the code with twice as many reps caused 12 divergent transitions and no improvement in model fit.

**Comment by legault** [comment]
Weird. When I run simulation_traitsandmore.R with more replicates, I don't get any divergences.

**Comment by legault** [comment]
Fits for SeedMass, LNC, and SSD were added in eeb6c6e8

**Comment by legault** [comment]
Also, the fitted models are all on midge on home/data/Ospree_traits (see *_stan.RDS files)

**Comment by lizzieinvancouver** [comment]
This seems like pretty great progress! Suggested next steps:

- [ ] Run the simulated data with no more reps but up spp and study to 25 and see what happens to muchillsp ... also check that running the chains longer doesn't help.
- [ ] Run the phenology-only model and the traits-only models and plot the posteriors against each other (cue on y, trait on x) so we can get a sense of the data
- [ ] Plot the model results! (Some notes [on a similar model here, see March 26 image](https://github.com/lizzieinvancouver/ospree/issues/406).

**Comment by DeirdreLoughnan** [comment]
@FaithJones @legault The joint model is looking really promising but we discussed a few more things to look into before the retreat:

- [ ] @FaithJones will rerun the model but with more species (~25) and studies (~25). 
- [ ] @DeirdreLoughnan will run the phenology model only and extract the cue estimates. 
- [ ] Make plots comparing the cue estimates from above with either the mean trait values or the estimates from the trait only model. 
- [ ] Height is probably too important a trait for us not to include. We discussed removing the duplicated data and running the model on the remaining data. @legault would you be able to attempt this?

**Comment by FaithJones** [comment]
I ran the model with 25 species and 25 studies, using the wider priors. I got 88 divergent transitions, and the model parameter estimation was not improved.

**Comment by DeirdreLoughnan** [comment]
@FaithJones @legault @lizzieinvancouver I made some rough plots using the cue estimates from the ospree model and the mean. 
[Forcing vs mean traits](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/figures/forcevstraits.pdf)
[Chilling vs mean traits](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/figures/chillvstraits.pdf)
[Photoperiod vs mean traits](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/figures/photovstraits.pdf)

**Comment by FaithJones** [comment]
@legault  I only see .RDS files for SLA and seed mass on Midge. Could you tell me where the fits are for LNC, and SSD  so I can make sure I have a local copy before the retreat? 

ALso @legault @DeirdreLoughnan - Has anyone run the model on clean height data? If so, where do I find the model fit data for this model?

**Comment by DeirdreLoughnan** [comment]
@FaithJones I thought that as a general rule we don't push model output. Is it not too big? 

I have not got around to working on the height data yet, but have it on the to-do for today.

**Comment by FaithJones** [comment]
@DeirdreLoughnan  you are right! We don't push output. @legault put some of the output on Midge, where I downloaded it from. It would be helpful if you could also save the height model output on Midge as well so we can all access it if we need next week without running any models. The folder on Midge is home/data/Ospree_traits

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver @FaithJones @legault @md-garner We left the retreat with several more plotting tasks and additional analyses we would like to include. These tasks span several issues, but in general our next steps are:

- [ ] @legault will get the model running for log seed mass 
- [ ] Once we have the model output for log seed mass, @DeirdreLoughnan will make the plots of the cue responses agains the beta/alpha/difference estimates and run Faith's code to look at the data vs posterior trait estimates
- [ ] [Explore the relationship between early and late species](https://github.com/lizzieinvancouver/ospree/issues/429). @DeirdreLoughnan will pull the Harvard Forest data and look for/request PEP data
- [ ] @DeirdreLoughnan  will [run a basic PGLS on the mean traits vs cue estimates ](https://github.com/lizzieinvancouver/ospree/issues/428)
- [ ] Start an outline of the results and identifying key references

Our goal is to have these tasks completed by December 3rd

**Comment by legault** [comment]
Updated seedmass model added in commit fc5e19d8

FYI, if anyone is still receiving n_effective warnings, try saving more iterations in the final stanfit object (e.g., change the value of (iteration - warming) from 1000 -> 1500 or 2000). This won't fix the problem for *really* inefficient MCMCs, but I have found it useful for the traitors work.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Are we all set here? Can we close?
