### ISSUE TITLE
write up model methods for phylo model

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#423]
@legault Write up briefly how you would explain the phylo PMM model. 

Included in this, in our 8 Sept meeting we discussed Simon Joly's response to PMM ... he wanted the phylogeny on the error and @legault had a nice way of explaining how similar this is to adding it to slope and/or intercept ... so perhaps include that?

**Comment by legault** [comment]
Today I added a draft of the methods to the pmm repository.
