### ISSUE TITLE
Poor mixing and low n_eff for intercept only models

### ISSUE THREAD

**Issue by DeirdreLoughnan** [lizzieinvancouver/ospree#424]
@lizzieinvancouver, @legault, @FaithJones 
As we learned at our last mini-retreat, our intercept only models with two intercepts are producing low n_eff and poorly mixed chains. The post @lizzieinvancouver made on this issue [is here](https://discourse.mc-stan.org/t/simple-intercept-only-hierarchical-model-with-two-groups-deadly-slow-poor-convergence/24310/6).

We also tried to approach this problem with a simple dataset of scores of figure skating routines from the 1932 Olympics. The code can be [found here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/Rfiles/Olympic1932_example.R) and [Stan code here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/stan/OlympicGames_1932mdl.stan).  But the chains looked poor to us.

![image](https://user-images.githubusercontent.com/16216421/133664565-843c47fb-8cf2-4a8c-ae95-5549ed002180.png)

I also made [a discourse post ](https://discourse.mc-stan.org/t/simple-intercept-only-model-with-poor-chain-mixing/24335/4) for this example. Interestingly both Lizzie and I were told that we should try ncp for the models. But we ran the models in rstanarm, which applies ncp when necessary and the chains still mixed poorly. 

@lizzieinvancouver suggested emailing Andrew Gelman about it. He forwarded our problem to Jonah Sol Gabry, Ben Goodrich, and Lu Zhang. Andrew's first thought was that the issue with the example is that the sample size is small and the model might just be hard to fit with such weak priors. Andrew included Lu since he thought it might be an interesting model to run through [Pathfinder](https://arxiv.org/pdf/2108.03782.pdf).

Jonah replied and very generously wrote the Stan code for the Olympics example with ncp for us. This does improve the n_eff, producing values closer to 775, and good Rhat values very close to 1. But I was surprised since the chains still looked bad to me. 
![image](https://user-images.githubusercontent.com/16216421/133666324-f80d4406-75c7-45ab-b9e0-faeead4dee60.png)

Both Andrew and Jonah did not seem to think this was concerning. Andrew's response was to look at the Rhat's and Jonah replied that he thought they looked decent enough given that they do not get "stuck" anywhere with no areas where chains flatline. But he also thinks the model would be improved by by using stronger priors on the sigmas.  

I saw this [recent post on Andrew's blog](https://statmodeling.stat.columbia.edu/2021/09/15/the-bayesian-cringe/) about using tighter priors as well!

**Comment by FaithJones** [comment]
We decided to run with the model how it is for now, and not worry too much about the problems in this issue
