### ISSUE TITLE
maybe run basic PGLS on mean trait versus cue estimates from model?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#428]
Try running PGLS (I think in the caper package, make sure you let the lambda value vary) on the MEAN traits and the mean posterior estimates from model ... to see check if phylogeny super matters. Step 1: Get a phylogeny (maybe from Zanne tree).

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver @legault @FaithJones @md-garner Step 1 complete, we have a [phylogenetic tree](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/figures/traitors_phylogeny.pdf) for our 26 traitor species! 

The tree was built from a more recent tree by Smith & Brown (2018), it is actually the same tree that Nacho is using in for the phylogeny paper.

**Comment by DeirdreLoughnan** [comment]
I have been working on the [PGLS analysis](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/Rfiles/traitors_pgls.R) and drawing on code from other's in the lab. 

I am unsure how to interpret the missing lower limit in the estimated 95% CI or whether it is not something to be concerned about. Below is an example of the output from a model testing the sensitivity of the mean posterior estimates for the forcing cue to SLA:
![Screen Shot 2021-12-07 at 11 40 13 AM](https://user-images.githubusercontent.com/16216421/145103781-ef244357-82ff-4475-8d9b-7e504bc768c7.png)
:
