### ISSUE TITLE
review new limiting cues draft

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#431]
By 10 December (if feasible) please review new drafts and send comments (on PDF, in email, in Rnw on repo, whatever, just let me know how to find them)... especially looking for thoughts on:

- Title? (Especially shorter ideas)
- Where to cut words/refs -- would like to cut 500 (we're around 4400 now), as well as 30 refs if possible
- Better title ideas for section in supp on chilling.

- Can someone help check these refs? Even when interactions are invoked to explain declining responses to warming, they are often not estimated \citep[e.g.,][]{fu2015,asse2018}. For Asse, they write "We assessed the independent and joint contribution of predicting variables and detected possible interactions between them with variance partitioning using the library Vegan"... but I do not see interactions in the model, but maybe there were there?
- @dbuona Help here (cites, language?) This is unsurprising given that most species leafout before flowering and most species' cuttings become resource limited after leafout.

**Comment by lizzieinvancouver** [comment]
Hoping we might submit to [New Phytologist as research review](https://nph.onlinelibrary.wiley.com/hub/journal/14698137/about/author-guidelines): 

> Short Research reviews should be in the range of 3,500–4,000 words, with up to 60 references and six figures/tables. Following a short introduction, putting the area into context, and providing a ‘way in’ for the non-specialist, these will concentrate on the most recent developments in the field

**Comment by dbuona** [comment]
@lizzieinvancouver I just added comments to the .Rnw file (indicated with %%%DB%%%).

**Comment by lizzieinvancouver** [comment]
@AileneKane @dbuona @cchambe12 @MoralesCastilla  Thank you all! I just pushed a new version with all your edits (commit # a44c3fe2eb5cccabbaa03cae7b729efbff7ffe40).

**Comment by lizzieinvancouver** [comment]
I have a few notes for @AileneKane comments...

1. I liked your point about us having the data now to integrate experiments and observations for some well studied species ... if you see a way to add it to the abstract while not adding more than 4 words, let me know!
2.  I  tried to fix Figure 2, but I cannot figure out how to add the black outside lines to legend. If anyone can, please help! My notes and code below.
3. For Figure 3, Ailene wrote "Forgive me but I do not understand and cannot remember how this differs from white space on the figure?  Also what do the gray squares mean in panel b?"  ... the gray always means we don't have the chilling info -- sometimes it's because the design was as shown in b (for panel a) or as shown in a (for panel b) and sometimes we just can't figure out the right level. I am not sure how to explain this better  ....
4. For figure 4, we report the warming scenario in the supp and there's no green line as there's no chill data for that species, we say that -- but if you see a way to say it better, let me know.

Okay, back to Figure 2: The code this figure is at the end of analyses/limitingcues/GDD_plottinglimcues.R .... Based on [this page](http://www.sthda.com/english/wiki/r-plot-pch-symbols-the-different-point-shapes-available-in-r) thought adding `pch=rep(21, 5), col="black", bg=colz[6:2]` to the legend should work, but it didn't. 

I am hoping to submit on **Tuesday this week** if possible, but can wait (and might run out of time anyway... my days feel very busy just now)

**Comment by AileneKane** [comment]
@lizzieinvancouver I solved the Figure 2 legend issue!  See [here](https://github.com/lizzieinvancouver/ospree/commit/fad77a4eaa9daa43bfa9cc66861a50dcd3fce5c5)

**Comment by lizzieinvancouver** [comment]
@dbuona @cchambe12 @MoralesCastilla @AileneKane Thank you all! It's resubmitted for now.
