### ISSUE TITLE
Traitors - alphaCueSp issue

### ISSUE THREAD

**Issue by DeirdreLoughnan** [lizzieinvancouver/ospree#434]
We realized we might be having some issues with the traitors model for our leaf traits. Unlike with height and seed mass, we actually predict SLA and LNC to have a positive slope with high values being less responsive to cues. But our model seemed to struggle to model any of the variation of SLA onto the slope and it was mostly loaded onto the intercept. 

@FaithJones has been looking into it and might have found the issue. The problem appears to be that positive betaTraitCue values lead to positive betaCueSp values unless the alphaCueSp is very high and balances it. Our current priors do not allow betaCueSP values to be negative, however, since alphaCueSp is constrained to be close to 0. 

@FaithJones tried widening the priors on alphaCueSp to -30, allowing the alphaCueSp value to balance a positive relationship between cue and trait. But this produced a lot of divergent transitions and multi modality. 

After chatting, I tried running the model with a more moderate prior of -15. This model did not produce any divergent transitions, but 8000 iterations exceeded max tree depth and the Rhat were bad. I am also getting modality in the model output. 
![Screen Shot 2022-03-04 at 10 43 01 AM](https://user-images.githubusercontent.com/16216421/156823111-da7efd77-f3b3-4239-a02e-80bac2b08c5a.png)

**Comment by lizzieinvancouver** [comment]
> The problem appears to be that positive betaTraitCue values lead to positive betaCueSp values unless the alphaCueSp is very high and balances it.

Doesn't that just mean the model is non-identifiable? I am not sure we can fix it then ... can we? (Though I am not sure. BTW, are we talking about our data or the test data?)

**Comment by FaithJones** [comment]
I think there might be a problem with my simulation code, because when I ran the model for LNC with wide priors allowing for very negative muCueSp values, the modle ran fine and allowed a positive betaTraitxCue value, like we were hoping. 
![image](https://user-images.githubusercontent.com/29034858/156856676-3483e321-ab6c-4495-bfea-98d32de5cbd0.png)
![image](https://user-images.githubusercontent.com/29034858/156856685-0b8ef24e-793f-4890-9476-2e07417cc033.png)

**Comment by FaithJones** [comment]
Bulk effective sizes are too low, but otherwise SLA also runs, and we see positive effects for chilling and forcing, but a slightly negative one for photoperiod
![image](https://user-images.githubusercontent.com/29034858/156858186-9111238a-cccf-4581-9fd2-b3f2483941b4.png)
![image](https://user-images.githubusercontent.com/29034858/156858192-ea50198d-5413-496d-8960-d407cca19fe9.png)

**Comment by FaithJones** [comment]
Seed mass is ok, and direction of trait/cue response relationship is unchanged. 

![image](https://user-images.githubusercontent.com/29034858/156861395-9af3d7cc-a787-4a1c-b65e-4f0bf0931902.png)
![image](https://user-images.githubusercontent.com/29034858/156861412-33a737d9-59ca-4e68-b71e-42523773254e.png)

**Comment by FaithJones** [comment]
I tried to run the height data, but I cant find the input file height_subsampled.csv. I pushed the updates priors though in case someone with this file wants to run that model. I also haven't managed to put any model output on midge because of a permissions issue.

**Comment by lizzieinvancouver** [comment]
@FaithJones Annoying on the test data, but exciting we seem to be able to improve things for the real data... have a good weekend!

**Comment by DeirdreLoughnan** [comment]
@FaithJones @legault @lizzieinvancouver I just pushed new figures! It is interesting to see that 

[The cues slopes](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/figures/cuetrait_wtrend_nprior.pdf) are now in the direction that makes more sense to me.

And the [figure of the slopes](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/figures/slopesConsAcqu_nprior.pdf) is also now more in line with what we predicted. Surprisingly the effect of height of forcing is now positive though.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan @FaithJones Nice! Excellent catch and fix. Someday we might also re-make the ones that decompose the effect into the two parts and put them together (the ones from the retreat), though not critical.

**Comment by lizzieinvancouver** [comment]
We fixed this!
