### ISSUE TITLE
Clean up zohner stuff

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#64]
Make a zohner folder within cleaning. Move all the zohner R code there and add a readme that explains exactly how all the zohner files were formatted (i.e., where does the raw data come from in the data folder? How are all the other files created). Also, avoid using xls (or xlsx) in R .. stick with reading and writing csv files when possible. 

And create a new zohnerformated.csv which can rbind to ospree.csv (in input folder).

**Comment by dbuona** [comment]
mostly done. The zohner data was already added into the ospree.xlsx data sheet, so I don't think we need separate merging or cleaning files.
such as: zohner_checkifweneed.R

**Comment by lizzieinvancouver** [comment]
Deleted all files that are not written out or read in. And some old R code we no longer need. I think we're good! See commit 6c5b5c756a7c7f0ac0a370adf5998a27a86a290f.
