### ISSUE TITLE
Check out change to clean_photo.R

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#65]
Check this out please, is it okay?
respvar=='plantheightatflowerbudappearance']<-'constant') # Lizzie changed this constant to 'constant' because the code was not running, need Cat to check … also, should we clean this in respvar?!!

**Comment by cchambe12** [comment]
I checked out the change and it looks great, thank you for fixing that!

**Comment by cchambe12** [comment]
And it is using a column in respvar to change the photoperiod column so it should stay in the clean_photo.R script
