### ISSUE TITLE
Finish duplicate code (look at duplicates) and then source (in cleanmerge_all)

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#79]
look at flagged duplicates to decide if they are real data or duplicated rows)

**Comment by lizzieinvancouver** [comment]
Nacho is working on this and will decide on next steps (see clean_duplicates.final.R)

**Comment by MoralesCastilla** [comment]
I have pushed a few edits to clean_duplicates.final.R @AileneKane @lizzieinvancouver 

I have checked the script and it does what it is supposed to: a) remove fully duplicated lines and b) remove additional lines that differ by less than 0.5% in their response variable, and thus are due to either potential duplicates or to human error. We can always mute the part b of the code, but as is, it removes 1190 rows from ospree_clean.cvs. The script is heavily commented and I think it is easy to quickly get what it does. 

Maybe you can double check it, and if you do not find anything weird in the code and give me the thumb's up, I will activate it in the cleanmerge_all.R pipeline and close this issue.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Hello! I worked on this today. I started by just looking at a lot of the files being deleted in the first chunk of code and finding most were unique based on on unused target variables. So I kept adding to tarvar until it seemed to be deleting (as best I could tell) truly duplicated data.

I still think some of the former duplicates *should* be deleted, but only in other cleaning folders (see clean_duplicatesmore.R in bb_analysis).

I am not sure now if the second chunk of the clean_duplicates.R code should be adjusted to match the new tarvar ... see line 51+ ... we can discuss today!

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Okay! I have updated cleaning/clean_duplicates.R but it would help me if you went through and checked what is deleted on line 94. I tried looking at some of subset(ospree.sub.no.dup, remove==1)  and am not sure I can tell why some things are deleted ... I am just not sure what happens with reponse.time:
line 80: if(d.subset.j$response.time[h]%in%d.subset.j$response.time[-h]){
And thus whether it's working. Can you take a look at some of the rows slated for deletion and see if they look right?

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane I have been re-running, re-checking and correcting this code. 

The first chunk looks good to me after adding more target variables to build blocks within which look for duplicates.

I have corrected the second chunk. As it was, it identified, within each block containing duplicated values (according to tar.var) which lines had values of response that were within 0.5% distance to other lines in the block. Then, only if there were lines in the block with the same value for response.time as the target line, it would be flagged and later removed (that is what former line 80 did). This was not correct, as it would remove all similar values within a block if they would coincide in response.time.

After the correction:
1. The code first flags which lines have very similar responses (within 0.25%) to each target line within a block. 
2. If there are, it will ask if those lines are also similar to the target in response.time.
3. In the end it assigns a value of 1 in to.remove to subsequent lines that are very similar in both response and response.time to the target.

I have checked that the code runs and now it deletes only 14 lines that are very very similar in all the variables within tar.var and that differ by less than 0.25% in both response and response.time, so it should be safe removing them. If we want we can raise or lower the desired of similarity. 

I believe after this we should be good to close this issue.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I finally checked this. It looks good. You can close the issue!

**Comment by MoralesCastilla** [comment]
Aaaand closing!

**Comment by lizzieinvancouver** [comment]
Whee!
