### ISSUE TITLE
DaystoBB Cleaning: remove rows with multiresponse=TRUE (select highest percentage) ... warning: this issue mixes up clean_bbperctodays.R and multiresp.R 

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#81]
create new code that goes into budburst cleaning. 
select the highest percentage of budburst OR (better option if possible) value closest to what we use in clean_bbperctodays.R
just for days to budburst cases when there are multiple percentages of budburst.

**Comment by MoralesCastilla** [comment]
I have been looking into this issue, but I would need further clarification.

If I got it right, the code should select rows whose respvar is any of: c("daystobudburst","daysto50%budburst","daysto20%budburst","daysto25%budburst")

and for those studies, species, experiments, that have more than one value, the code will remove all rows except for that with the highest percentage?

As soon as I'm clear about this I'll write the code and insert it in BB cleaning.

**Comment by AileneKane** [comment]
This is separate, but similar to the multiresp issue so perhaps should be dealt with in the same code? I started code but only got as far as identifying the studies that needed to be fixed,

**Comment by lizzieinvancouver** [comment]
Yes! See also issue #95 ... 
We should handle this in multiresp.R and we should:
(1) select daystobudburst if given (aka if daystobudburst is an option for the study, select that one)
(2) select highest percent if no daystobudburst
(3) check that n across different response types is not grossly different (aka >25 off)

**Comment by MoralesCastilla** [comment]
I have now worked on multiresp.R. The code now does the following:

1) identifies studies with multiple responses. There are two types, studies containing "daystobudburst" or studies containing "percentbudburst" (only one of this second type). This was already been done by Ailene.

2) Identify which values (and their corresponding rows in the global dataset) are off (by 25%).

3) Remove the rows that are off from the global dataset. This bit is not activated as I would like you to have a look to ensure I'm not doing something weird.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Thanks Nacho for all this! 

Can you check the code that does (1. identifies studies with multiple responses. There are two types, studies containing "daystobudburst" or studies containing "percentbudburst" (only one of this second type). This was already been done by Ailene.)? 

I tried the below chunk of multresp.R:

#start with output/ospree_clean_withchill.csv file
d<-read.csv("output/ospree_clean_withchill.csv", header=TRUE)

multdatsets_days<-unique(d$datasetIDstudy[d$multiresp==TRUE & d$respvar.simple=="daystobudburst"])#only 3 studies for which there are multiple response variables and days to budburst
multdatsets_percbb<-unique(d$datasetIDstudy[d$multiresp==TRUE & d$respvar.simple=="percentbudburst"])#only 1 study for which there are multiple response variables and percent to budburst

Then added: 
goo <- as.data.frame(table(d$datasetIDstudy, d$respvar.simple))
daystobbID <- subset(goo, Var2=="daystobudburst" & Freq>0)
otherID <- subset(goo, Var2!="daystobudburst" & Freq>0)
otherID[which(otherID$Var1 %in% daystobbID$Var1),]

This suggest a lot of studies have percentbudburst and daystobudburst (I wonder if the original code to flag multresp need work?):
965        boyer exp1 percentbudburst   83
970  caffarra11b exp2 percentbudburst   16
971  caffarra11b exp3 percentbudburst    8
987     falusi90 exp1 percentbudburst  160
1002 guerriero90 exp1 percentbudburst    7
1003 guerriero90 exp2 percentbudburst    7
1004 guerriero90 exp3 percentbudburst    6
1017     heide12 exp1 percentbudburst    8
1019     heide12 exp3 percentbudburst   36
1024    heide93a exp1 percentbudburst   12
1025    heide93a exp2 percentbudburst    6
1026    heide93a exp3 percentbudburst   30
1070   sogaard08 exp2 percentbudburst    8
1075  sonsteby14 exp1 percentbudburst   63
1076  sonsteby14 exp2 percentbudburst   80
1077  sonsteby14 exp3 percentbudburst   90
1078  sonsteby14 exp4 percentbudburst   54
1079  sonsteby14 exp5 percentbudburst    6

Also, we should toss out the thermaltime part of studies where we have daystobudburst and thermaltime (two studies I think).

We should also make a note that THIS code only does percentbudburst and thermaltime, not percentflower or growth or .... 

Let me know how this goes, then I can check again... getting close!

**Comment by lizzieinvancouver** [comment]
One check to do once multiresp.R is done: make sure the below are down to one response variable:
# Both thermal time and daystobudburst were entered for basler12, 
# Both thermal time and percentbudburst were entered for ghelardini10

**Comment by lizzieinvancouver** [comment]
@cchambe12 Quick query ... in looking through clean_thermaltimetodays.R I noticed heide93 gets changed but I think it is another multiresp issue. If I look at d before thermaltime is cleaned I get this:

goo1 <- subset(d, datasetID=="heide93")
> table(goo1$study, goo1$respvar.simple)
      
       daystobudburst percentbudburst thermaltime
  exp1              0             180          60
  exp2              0             180         176
  exp3             24               0           0

After I run this:

# 2. Need to deal with thermal time to days
source("bb_analysis/cleaning/clean_thermaltimetodays.R") I get this:

goo1 <- subset(d, datasetID=="heide93")
> table(goo1$study, goo1$respvar.simple)
      
       daystobudburst
  exp1            240
  exp2            356
  exp3             24

So ... should we (1) actually just leave heide93 alone (like basler12) and make sure it is slimmed down through multiresp or (2) do something else or (3) am I missing something?

**Comment by cchambe12** [comment]
@lizzieinvancouver 

I think I may have messed up the code somehow then in clean_thermaltimetodays.R !

Good catch! My initial thought is it is another multiresp issue and should be treated similarly to basler12. I'll investigate more and we can discuss at our next meeting.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Okay, definitely check more! If it should be treated like basler12 then please change your code and post here so I can update one file that reminds me to check on the multiresp output ... also, you missed the exciting news that Nacho decided we should set a deadline for all cleaning so we did and it's  .... 7 JUNE!  So please work on this soon.

**Comment by AileneKane** [comment]
@cchambe12 please let me know what you decided after looking at this more- there doesn't seem to be anything specific about this in multiresp yet so i'm not sure if you have taken a look at this?

**Comment by cchambe12** [comment]
@AileneKane 

Sorry I forgot to post here! It is a multiresp issue, I made notes in the bbcleaning_README.txt and the clean_thermaltimetodays.R script describing that the percentbudburst was already converted to daystobudburst so thermaltime did not also need to be converted.

**Comment by AileneKane** [comment]
May need to update this to use one of the new multiresponse columns?

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla What does 90 in line 125 in clean_bbperctodays.R do? (Note that changing it 85 would give us a few more rows.)

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
I think clean_bbperctodays.R is close! But I noticed it is deleting datasets, why is this?

length(unique(d$datasetID))
length(unique(d.subset$datasetID))

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
So, just to slowly catch up --- I think my memory that we picked 90% as our target and then took any values within 25% of that (picking the one closest) is correct, right? This would explain why we lose studies. Maybe we could be more generous? And say 80% with a 35% target? So we would include 50-115%, right? (A little over a 100% is okay since we extracted the data using extraction software).

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla And just to wander on ... I will just do this myself. Please semi-ignore this thread!

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
I updated the code and will push changes in a minute. Please pull them and then for clean_bbperctodays.R could you:
(a) Check why we do lose so many studies? Even if I set the acceptable range down to allowing 10%, we still lose them.... (try length(unique(d$datasetID)) before and after running the clean_bbperctodays.R)
(b) Male a note about what the warnings mean in bb_cleanmergeall.R or in related README. 

And while I am here:
(c) Please make a note about what the warnings in clean_moreduplicates.R mean ... (and clean_duplicates.R if applicable). Something simple like 'warning is just about X change made, it's okay.' would do.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 

I think I've figured out why we were loosing so many studies in clean_bbperctodays.R:
The key line is (69):
`values.in.target<-which(dat3$response>(target.percent-target.percent*acceptablerange)&dat3$response<(target.percent+target.percent*acceptablerange))`

Which in many cases yields values.in.target = Integer(0), and thus, those lines are not flagged and are removed in the final subset. I'm trying to add some workaround to it, to not remove those lines. 

I will let you know when it is working.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla @AileneKane I don't think the change can be working because:
before you run step 6 (clean_bbperctodays.R) in bb_cleanmergeall.R you have 10308 in d, after you run step 6 you get MORE rows (not fewer), 10561.

Also, this ends up not deleting rows here, but we now delete >3000 rows when running step 7 (clean_moreduplicates.R) ... last I checked that code deleted only 3. 

Nacho, can you check your work again?

**Comment by MoralesCastilla** [comment]
@AileneKane @lizzieinvancouver 
I found an error at the end of the function (where d was subsetted by `respvar.simple==daystobudburst` instead of `respvar.simple==precentbudburst` as it should be). I have corrected it and now it passes from 10308 rows to 10224. Subsequently, cleanmoreduplicates removes 4 additional rows. 

I just checked this, but it will be great if you can run it and make sure it works.

**Comment by lizzieinvancouver** [comment]
I ran it, I checked it a little more, the spot-checking made things look good, so I am gonna close this puppy!
