### ISSUE TITLE
can we move chillcheck.R?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#83]
Maybe move to chilling folder and explain what it does in README there?

**Comment by AileneKane** [comment]
Yes! This can definitely be moved. i'm not sure that its even relevant any more so it may be better to go in the archive? it was just used to create a list of papers that needed their chilling values checked, as they were non-numeric- last july, after the retreat on cape cod. l

**Comment by lizzieinvancouver** [comment]
Archived ... see commit e728780c5f9bff9c951ca152fee4d90030195b5b
