### ISSUE TITLE
Finish chilling units by forcing units figures 

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#86]
... maybe make one set for days to BB and one set using just thermaltime studies?

**Comment by cchambe12** [comment]
done! sources code from /analyses/bb_analysis/cleaning/clean_thermaltimetodays.R

use script /analyses/bb_analysis/figures_forcingbychilling.R - only interesting for daystobudburst studies, unable to do anything meaningful with remaining thermal time studies
