### ISSUE TITLE
Make figures based on rstanarm models and the model I built

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#87]
Make a figure for each model (similar to Dan Flynn's figures):
rstanarm model: bbmodel1_rstanarm.R
stan model: M1_daysBB_2level.stan which is referenced in bbmodel1_stan.R ... you will need to run this model. 

Let me (Lizzie) know if you hit any issues!

**Comment by MoralesCastilla** [comment]
code to plot the figures can be found [here](https://github.com/lizzieinvancouver/ospree/tree/master/analyses/bb_analysis), and preliminary figures are in the analyses/figures folder
