### ISSUE TITLE
BB > 200

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#93]
I went through all the current studies with response.time > 200

- charrier11: Looks reasonable from histogram of data. Would be good to check the calculations that created these days (they come from Fig. 1 which is some sort of thermal time).

- falusi90: went back to original paper, this is legit

- falusi96: went back to original paper, this is also legit

- partanen05: data goes from Aug 31 to May 10, so dates above 200 are real

and ...

- swartz81: These are the values >600 (!) ... ugh! This study is hard. The data come from Fig 1 and must have been converted from thermal time. From my reading plants went into 22 C chambers for two weeks but then if you look at Fig 1 and do a simple GDD calculation (thermaltime/(22-4.5)) you get something like 85 as a max.

**Comment by lizzieinvancouver** [comment]
Dan: Could you read all of Swartz81 (it's short) and see if you can figure where the data we have in OSPREE come from? 

Cat: Can you double-check charrier11? 

Be sure to use the UNCLEANED and full ospree.csv and take a look at all the data that were entered for each study before making an assessments.

In both cases if we think someone converted from thermaltime when inputting the data into OSPREE we should add info on how to ospreexlsx_README.txt (data folder).

**Comment by lizzieinvancouver** [comment]
co,,it 0bb0fa246493dd3f38fa704aa52270ac707e0266

**Comment by dbuona** [comment]
It's hard for me to tell from the figure, but my best approximation is that Swartz81 has been converted from growing degree hours to growing degree days by dividing the values in figure 1 by 24. 
see #commit 3debb39 #

**Comment by cchambe12** [comment]
I am not sure how entries were calculated. Charrier11 uses MTB (Mean Time until Budburst) which is calculated in hours. The numbers in Table 1 and the entries are very different and I cannot figure out how the entries were calculated. For Figure 2, the data was divided by 24 to get number of days. Seem accurate.

**Comment by cchambe12** [comment]
Charrier11 looks great, all set, no changes necessary.

**Comment by cchambe12** [comment]
For Swartz81, Tim just divided growing degree hours by 24 which I think is okay. The paper clarifies in the Methods section that they use the same calculation as the Richardson et al, 1974 paper. This paper uses a Utah Chilling model which states 5 degC at 1 hour is the equivalent of 1 chill unit. So just dividing the response by 24 should give the give the days to budburst. I have added this information to the ospreexlsx_README.txt (data folder) . And I think I can close this issue... *fingers crossed this time*
