### ISSUE TITLE
Finish the BB cleaning

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#97]
Need to make a list of what to deal with. Here's a start:
- multiresp.R
- folder needs a better readme and all readme files should be TXT format

**Comment by MoralesCastilla** [comment]
I have made and pushed some edits to readme file.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I looked at bbcleaning_README.txt and bb_cleanmergeall.R which look good, but we need to finalize issue #95 ...

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I think we're close on this, I pushed my edits to clean_duplicatesmore.R which deletes not too much data, but we should wait to finalize it until we also finalize clean_duplicates.R (see issue #79)

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver Since clean_duplicates.R is now finished (or so I think) should we edit clean_moreduplicates.R to do the same (i.e. copying tar.var and editing the second chunk accordingly)?
I'll do that as soon as you give me the thumbs up.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane I have edited the second cleaning chunk of clean_moreduplicates.R to conform it to clean_duplicates. I have not changed the selection of variables to look for duplicates in this piece of code. If you think the variables should coincide with those in clean_duplicates I will change it, and then it should be ready.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Yes! Please do it and let me know when it's done so I can finalize the BB cleaning ... Thank you!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver This has been done already

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Okay! I will work on checking it. Thanks!

**Comment by lizzieinvancouver** [comment]
Lizzie thoughts: This looks pretty damn close to done to me. To discuss.

**Comment by MoralesCastilla** [comment]
Yep, I have checked that variable selection in clean_moreduplicates.R is the same as in clean_duplicates.R.

**Comment by AileneKane** [comment]
I was running this code and wonder if we could now stop the printing of rows/things to remove in source("bb_analysis/cleaning/clean_bbperctodays.R") (line 57 I think)?

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla @AileneKane 
Thanks for all your help on this issue! I cannot believe it is only 3 months old, feels sooo much older.
