### ISSUE TITLE
Add "year" to studies that are missing that data

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#98]
Zohner 2016 (and two others i think?)

**Comment by lizzieinvancouver** [comment]
Heide03 is a seed study, no year is thus correct IHMO.
heide05 "vitro micropropaga- ted plants of the commercial apple and pear rootstock cultivars listed in Table 1 were obtained from an authorized horticulture nursery" -- no year is thus correct IHMO.


Not quite sure why some of these were not entered:
cook05: year is 1999 and fieldsample.date is 7 Jul 199

**Comment by lizzieinvancouver** [comment]
Wait! I have even more with issues:

basler12 -- Sampling of the cuttings took place on 2 and 3 March 2009
charrier11 (exp 2 only; exp 1 is actually field observations) -- they don't really say but they are doing phenological observations in spring 2008 and 2009 and they clipped on 29 November, so probably 29 Nov 2009 is field sample date
karlsson03 -- says "monthly intervals 15 January to 15 May, 2001" -- data from Fig 1 should have fieldsampledate

Data are in the paper but someone else should look at it:
ghelardini10

Here are a few I think are okay to have no field sampling date (though I did not check as hard as I did for the above in the previous comment):
caffarra11a
falusi90
granhus09
Heide03 (see previous comment)
howe95 -- cutting rooted in greenhouse
linkosalo06 -- plantlets
morin -- is in field warming expt
myking95 -- seeds
myking97 -- seeds
sogaard08 -- seeds
thielges75 -- see previous comment
worrall67 -- clones derived from root cuttings
falusi96 -- seedlings
junttila12 -- seeds
li05 -- seeds
rinne94  -- seeds
rinne97 -- seeds

**Comment by AileneKane** [comment]
Yay lizzie! Thank you!
